<? $this->headTitle($this->article['page_title'])?>
<? $this->headMeta()->prependName('keywords', $this->article['meta_keywords']); ?>
<? $this->headMeta()->prependName('description', $this->article['meta_description']); ?>

<div id="newslist" class="contentContainer100">
	<h1><?=$this->article['title']?></h1>
	<p>
		<span class="date">
			<?=$this->translate('Published')?>: <time pubdate="<?=$this->Date($this->article['published_on'])?>"><?=$this->Date($this->article['published_on'])?></time>
		</span>
		<span class="author"> <?=$this->translate('by')?> <?=$this->Authors()->getName($this->article['published_by']);?></span>
	<!-- AddThis Button BEGIN -->
	</p>

	<?=$this->SocialWidgets()->addThis(); ?>

	<? if($this->article['image'] != '' || $this->article['header'] != '') { ?>
	<div id="preamble">
		<? if($this->article['image'] != '') { ?>
			<img src="<?=$this->article['image']?>" alt="<?=$this->article['page_title']?>" style="max-width: 196px;max-height:196px;"/>
		<? } else { ?>
				<img src="<?=$this->baseUrl() ?>/templates/default/images/euromillions_news.png" alt="<?=$this->article['page_title']?>" align="left" height="196" width="196" />
		<? } ?>
		<? if($this->article['header'] != '') { ?>
			<h2><?=$this->article['header']?></h2>
		<? } ?>
	</div>
	<? } ?>

	<div id="mainContent" class="ColF">
		<?=$this->article['content']?>
	</div>
</div>