<? foreach($this->list as $item){ ?>
	<div class="articleContainer">
		<img border="0" src="<?=$this->baseUrl() ?>/templates/default/images/latest_news_label.png" alt="" />
		<h2><a href="<?=$item['detail_link']?>" style="font-size:16px;"><?=$item['page_title']?></a></h2>
		<p>
		<span class="date"><?=$this->Date($item['published_on'])?> | <?=$this->translate('published_in')?>: <a href="<?=$this->url(Array("module"=>"news","controller"=>"index","action"=>"index","page"=>1),"News_Index");?>"><?=$this->translate('euromillions-news')?></a></span></p>
		<p>
		<? if($item['image'] != ''){?>
			<img src="<?=$item['image']?>" align="left" height="64" width="64" alt="<?=$this->translate('seo-news-title')?>" />
		<? } else { ?>
			<img src="<?=$this->baseUrl() ?>/templates/default/images/news/blue-star.png" align="left" height="64" width="64" alt="<?=$this->translate('seo-news-title')?>" />
		<? } ?>
		<?=$item['meta_description']?>
		</p>
	</div>
<? } ?>