<div class="medArticle lotteryList">
	<h3><?=$this->translate('euromillions-news')?></h3>
   <div class="latestNews">
	<? foreach($this->list as $item){ ?>
	<div class="item">
		<p><a href="<?=$item['detail_link']?>" alt="<?=$item['page_title']?>"><?=$item['page_title']?></a></p>
		<p class="smallIntro">
			<? if($item['image'] != ''){?>
				<img src="<?=$item['image']?>" alt="<?=$this->translate('seo-news-title')?>" align="left" height="32" width="32">
			<? } else { ?>
				<img src="<?=$this->baseUrl() ?>/templates/default/images/news/blue-star.png" alt="<?=$this->translate('seo-news-title')?>" align="left" height="32" width="32">
			<? } ?>

			<?=$item['meta_description']?>
		</p>
	</div>
	<? } ?>
	</div>
</div>