---
- name: Install packages to allow apt to use a repository over HTTPS
  become: yes
  apt:
    name: "{{ packages }}"
    update_cache: yes
  vars:
    packages:
    - apt-transport-https
    - ca-certificates
    - curl
    - software-properties-common

- name: Add Docker official GPG key
  become: yes
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add Docker repository
  become: yes
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
    state: present

- name: Install Docker CE
  become: yes
  apt:
    name: docker-ce
    update_cache: yes

- name: Install Docker Compose (via PIP)
  become: yes
  pip:
    name: docker-compose

- name: Add 'vagrant' user in Docker Group
  become: yes
  user:
    name: vagrant
    groups: docker
    append: yes
  when: is_vagrant