---
- hosts: localhost

  vars:
    enable_frontend_watchers: false
    enable_frontend_react_build: true
    is_vagrant: false # overwritten via Vagrantfile for Windows OS Hosts
    update_geoip_database: false # should update the geoip databases?
    do_docker_setup: false # should install docker and docker-compose on host?

  pre_tasks:
  - debug: msg="{{ lookup('env','BUILD_TAG') }}"

  - name: Debug
    stat:
      path: "{{ playbook_dir }}/../src/data/geoipdatabase/GeoIP.dat"
    register: check_geoipv4

  - name: Get GeoIP IPv4 database
    get_url:
      url: http://geolite.maxmind.com/download/geoip/database/GeoLiteCountry/GeoIP.dat.gz
      dest: "/tmp/"
    when: not check_geoipv4.stat.exists