app\entities\Translation:
  type: entity
  table: translations
  id:
    translation_id:
      type: integer
      generator:
        strategy: IDENTITY
  fields:
    key:
      type: string
      unique: true
    used:
      type: boolean
  oneToMany:
    translatedTo:
      targetEntity: app\entities\TranslationDetail
      mappedBy: translation
