app\entities\Language:
  type: entity
  table: languages
  id:
    id:
      type: integer
      generator:
        strategy: AUTO
  fields:
    ccode:
      type: string
  oneToMany:
    usedIn:
      targetEntity: TranslationDetail
      mappedBy: language