EuroMillions\entities\TranslationDetail:
  type: entity
  table: translation_details
  repositoryClass: \EuroMillions\repositories\TranslationDetailRepository
  id:
    id:
      type: integer
      options:
        unsigned: true
      generator:
        strategy: IDENTITY
  fields:
    value:
      type: string
    lang:
      type: string
      length: 6
  manyToOne:
    translation:
      targetEntity: EuroMillions\entities\Translation
      inversedBy: translatedTo
      joinColumn:
        name: translation_id
        referencedColumnName: translation_id
    language:
      targetEntity: EuroMillions\entities\Language
      inversedBy: usedIn
