EuroMillions\entities\EuroMillionsDraw:
  type: entity
  repositoryClass: \EuroMillions\repositories\LotteryDrawRepository
  table: euromillions_draws
  id:
    draw_id:
      type: integer
      options:
        unsigned: true
      generator:
        strategy: IDENTITY
  fields:
    draw_date:
      type: date
      unique: true
  manyToOne:
    lottery:
      targetEntity: \EuroMillions\entities\Lottery
      inversedBy: draws
  embedded:
    result:
      class: \EuroMillions\vo\EuroMillionsResult
    jackpot:
      class: \Money\Money