EuroMillions\entities\LotteryDraw:
  type: entity
  repositoryClass: \EuroMillions\repositories\LotteryDrawRepository
  table: lottery_draws
  id:
    draw_id:
      type: integer
      options:
        unsigned: true
      generator:
        strategy: IDENTITY
  fields:
    draw_date:
      type: date
      unique: true
    jackpot:
      type: bigint
    message:
      type: text
    big_winner:
      type: boolean
      default: false
    published:
      type: boolean
      default: false
  manyToOne:
    lottery:
      targetEntity: \EuroMillions\entities\Lottery
      inversedBy: draws
  oneToOne:
    result:
      targetEntity: \EuroMillions\entities\LotteryResult
      inversedBy: draw
