EuroMillions\entities\Translation:
  type: entity
  table: translations
  id:
    translation_id:
      type: integer
      options:
        unsigned: true
      generator:
        strategy: IDENTITY
  fields:
    key:
      type: string
      unique: true
    used:
      type: boolean
  oneToMany:
    translatedTo:
      targetEntity: EuroMillions\entities\TranslationDetail
      mappedBy: translation
