EuroMillions\entities\Language:
  type: entity
  repositoryClass: EuroMillions\repositories\LanguageRepository
  table: languages
  id:
    id:
      type: integer
      options:
        unsigned: true
      generator:
        strategy: IDENTITY
  fields:
    ccode:
      type: string
      length: 6
      unique: true
    active:
      type: boolean
      options:
        default: 0
  oneToMany:
    usedIn:
      targetEntity: \EuroMillions\entities\TranslationDetail
      mappedBy: language