EuroMillions\entities\LotteryResult:
  type: entity
  table: lottery_results
  inheritanceType: SINGLE_TABLE
  discriminatorColumn:
    name: lottery
    type: string
  discriminatorMap:
    EuroMillions: EuroMillionsResult
  id:
    id:
      type: integer
      options:
        unsigned: true
      generator:
        strategy: IDENTITY
  oneToOne:
     draw:
      targetEntity: \EuroMillions\entities\LotteryDraw
      mappedBy: result
      joinColumn:
        name: draw_id
        referencedColumnName: draw_id