EuroMillions\entities\LotteryResult:
  type: entity
  table: lottery_results
  inheritanceType: SINGLE_TABLE
  discriminatorColumn:
    name: lottery
    type: string
  discriminatorMap:
    EuroMillions: EuroMillionsResult
  id:
    id:
      type: integer
      options:
        unsigned: true
      generator:
        strategy: IDENTITY