build_failure_conditions:
    - 'elements.rating(<= D).new.exists'
    - 'issues.new.count > 5'
    - 'issues.severity(>= MAJOR).new.exists'
    - 'project.metric("scrutinizer.quality", < 8.75)'
    - 'project.metric("scrutinizer.test_coverage", < 0.45)'
    - 'project.metric_change("scrutinizer.test_coverage", < -0.045)'
checks:
  php:
    verify_property_names: true
    verify_argument_usable_as_reference: true
    verify_access_scope_valid: true
    variable_existence: true
    useless_calls: true
    use_statement_alias_conflict: true
    use_self_instead_of_fqcn: true
    uppercase_constants: true
    unused_variables: true
    unused_properties: true
    unused_parameters: true
    unused_methods: true
    unreachable_code: true
    too_many_arguments: true
    switch_fallthrough_commented: true
    sql_injection_vulnerabilities: true
    single_namespace_per_use: false
    simplify_boolean_return: true
    side_effects_or_types: true
    security_vulnerabilities: true
    return_doc_comments: true
    return_doc_comment_if_not_inferrable: true
    require_scope_for_properties: true
    require_scope_for_methods: true
    require_php_tag_first: true
    psr2_switch_declaration: true
    psr2_class_declaration: true
    property_assignments: true
    prefer_while_loop_over_for_loop: true
    precedence_mistakes: true
    precedence_in_conditions: true
    phpunit_assertions: true
    php5_style_constructor: true
    parse_doc_comments: true
    parameters_in_camelcaps: true
    parameter_non_unique: true
    parameter_doc_comments: true
    param_doc_comment_if_not_inferrable: true
    overriding_private_members: true
    optional_parameters_at_the_end: true
    one_class_per_file: true
    non_commented_empty_catch_block: true
    no_unnecessary_if: true
    no_unnecessary_final_modifier: true
    no_underscore_prefix_in_properties: true
    no_underscore_prefix_in_methods: true
    no_trait_type_hints: true
    no_short_open_tag: true
    no_short_method_names:
        minimum: '3'
    no_property_on_interface: true
    no_non_implemented_abstract_methods: true
    no_goto: true
    no_global_keyword: true
    no_exit: true
    no_eval: true
    no_error_suppression: true
    no_empty_statements: true
    no_duplicate_arguments: true
    no_debug_code: true
    no_commented_out_code: true
    naming_conventions:
        local_variable: '^[a-z][a-zA-Z0-9_]*$'
        abstract_class_name: '^[A-Z][a-zA-Z0-9]*$'
        constant_name: '^[A-Z][A-Z0-9]*(?:_[A-Z0-9]+)*$'
        property_name: '^[a-z][a-zA-Z0-9_]*$'
        method_name: '^(?:[a-z]|__)[a-zA-Z0-9]*$'
        parameter_name: '^[a-z][a-zA-Z0-9]*$'
        interface_name: '^I[A-Z][a-zA-Z0-9]*$'
        type_name: '^[A-Z][a-zA-Z0-9]*$'
        exception_name: '^[A-Z][a-zA-Z0-9]*Exception$'
        isser_method_name: '^(?:is|has|should|may|supports)'
    more_specific_types_in_doc_comments: true
    missing_arguments: true
    method_calls_on_non_object: true
    instanceof_class_exists: true
    function_in_camel_caps: true
    foreach_usable_as_reference: true
    foreach_traversable: true
    fix_use_statements:
        remove_unused: true
        preserve_multiple: true
        preserve_blanklines: false
        order_alphabetically: false
    fix_doc_comments: false
    encourage_single_quotes: false
    encourage_shallow_comparison: true
    encourage_postdec_operator: true
    duplication: true
    deprecated_code_usage: true
    deadlock_detection_in_loops: true
    code_rating: true
    closure_use_not_conflicting: true
    closure_use_modifiable: true
    classes_in_camel_caps: true
    catch_class_exists: true
    blank_line_after_namespace_declaration: true
    avoid_useless_overridden_methods: true
    avoid_usage_of_logical_operators: true
    avoid_unnecessary_concatenation: true
    avoid_superglobals: true
    avoid_perl_style_comments: true
    avoid_multiple_statements_on_same_line: true
    avoid_length_functions_in_loops: true
    avoid_entity_manager_injection: true
    avoid_duplicate_types: true
    avoid_corrupting_byteorder_marks: true
    avoid_conflicting_incrementers: true
    avoid_closing_tag: true
    avoid_aliased_php_functions: true
    assignment_of_null_return: true
    argument_type_checks: true
    align_assignments: false

filter:
  paths:
    - src/*
  excluded_paths:
    - src/tests/*
    - src/vendor/*
    - src/apps/web/controllers/TestController.php
    - src/apps/web/services/card_payment_providers/payxpert/GatewayClientGCP.php
    - src/apps/web/migrations*
build:
  environment:
    variables:
      EM_ENV: 'scrutinizer'
    mysql: 5.6
    php:
      version: "5.6.16"
      ini:
        'date.timezone': 'UTC'
    redis: true
    postgresql: false

  dependencies:
    before:
      - sudo apt-get -y install wget
      - wget http://geolite.maxmind.com/download/geoip/database/GeoLiteCountry/GeoIP.dat.gz
      - cp GeoIP.dat.gz /home/scrutinizer/GeoIP.dat.gz;gunzip /home/scrutinizer/GeoIP.dat.gz
      - wget http://geolite.maxmind.com/download/geoip/database/GeoIPv6.dat.gz
      - cp GeoIPv6.dat.gz /home/scrutinizer/GeoIPv6.dat.gz;gunzip /home/scrutinizer/GeoIPv6.dat.gz
      - chmod 755 dev-scripts/build_phalcon_scrutinizer.sh
      - command: dev-scripts/build_phalcon_scrutinizer.sh
        not_if: 'test -d cphalcon'
      - command: cp cphalcon/ext/modules/phalcon.so /home/scrutinizer/.phpenv/versions/5.6.16/lib/php/extensions/no-debug-zts-20131226/phalcon.so
        not_if: 'test -f /home/scrutinizer/.phpenv/versions/5.6.16/lib/php/extensions/no-debug-zts-20131226/phalcon.so'
      - sed -i '$ a \\n[Phalcon]\nextension=phalcon.so\n'  /home/scrutinizer/.phpenv/versions/5.6.16/etc/php.ini
      - composer install --no-interaction --working-dir=src
  cache:
    directories:
      - cphalcon
      - src/vendor

  project_setup:
    before:
      - mysql -e 'CREATE DATABASE IF NOT EXISTS euromillions_test'
      #- mysql -e 'GRANT ALL ON *.* TO 'root'
      - dev-scripts/schema_migration.sh scrutinizer

  tests:
    override:
      - command: cd src;php -d zend.enable_gc=0 vendor/bin/codecept run --config=codeception_scrutinizer.yml --skip acceptance --coverage --coverage-xml
        coverage:
          file: src/tests/_output/coverage.xml
          format: php-clover

#      - command: src/vendor/bin/phpunit --coverage-clover=coverage.clover --configuration src/tests/phpunit.xml --testsuite=unit+integration
#        coverage:
#          file: coverage.clover
#          format: php-clover
#  deployment:
#    - branch: master
#      commands:
#        - curl --data "environment=staging&version=master" http://62.57.159.66:3000/deploy/