checks:
    php:
        fix_php_opening_tag: false
        remove_php_closing_tag: false
        one_class_per_file: false
        side_effects_or_types: false
        no_mixed_inline_html: false
        require_braces_around_control_structures: false
        php5_style_constructor: false
        no_global_keyword: false
        avoid_usage_of_logical_operators: false
        psr2_class_declaration: false
        no_underscore_prefix_in_properties: false
        no_underscore_prefix_in_methods: false
        blank_line_after_namespace_declaration: false
        single_namespace_per_use: false
        psr2_switch_declaration: false
        psr2_control_structure_declaration: false
        avoid_superglobals: false
        security_vulnerabilities: false
        no_exit: false
filter:
  paths:
    - src/*
  excluded_paths:
    - src/tests/*
    - src/vendor/*
build:
  container: antonienko/phalcon2-ci:v1.2.3
  dependencies:
    override:
      - '/etc/init.d/mysql start & > /dev/null'
      - 'redis-server &'
      - 'composer install --prefer-source --no-interaction --working-dir=src'
      - 'cd src/react'
      - 'npm install'
      - 'cd ../..'
  project_setup:
    override:
      - 'mysql -e "create database if not exists euromillions_test"'
      - 'dev-scripts/schema_migration.sh scrutinizer'

  tests:
    override:
      -
        command: src/vendor/bin/phpunit --log-junit shippable/testresults/junit.xml --coverage-clover=coverage.clover --configuration src/tests/phpunit.xml --testsuite=unit+integration
        coverage:
          file: coverage.clover
          format: php-clover



