#checks:
#    php:
#        fix_php_opening_tag: false
#        remove_php_closing_tag: false
#        one_class_per_file: false
#        side_effects_or_types: false
#        no_mixed_inline_html: false
#        require_braces_around_control_structures: false
#        php5_style_constructor: false
#        no_global_keyword: false
#        avoid_usage_of_logical_operators: false
#        psr2_class_declaration: false
#        no_underscore_prefix_in_properties: false
#        no_underscore_prefix_in_methods: false
#        blank_line_after_namespace_declaration: false
#        single_namespace_per_use: false
#        psr2_switch_declaration: false
#        psr2_control_structure_declaration: false
#        avoid_superglobals: false
#        security_vulnerabilities: false
#        no_exit: false
#filter:
#  paths:
#    - src/*
#  excluded_paths:
#    - src/tests/*
#    - src/vendor/*
#build:
#  environment:
#    php:
#      version: "5.6.16"
#      ini:
#        'date.timezone': 'UTC'
#    postgresql: false
#    mongodb: false
#    elasticsearch: false
#    solr: false
#    couchdb: false
#    beanstalkd: false
#    neo4j: false
#    rabbitmq: false
#
#  dependencies:
#    before:
#      - git clone -q --depth=1 https://github.com/phalcon/cphalcon.git -b master
#      - cd cphalcon/ext; export CFLAGS="-g3 -O1 -fno-delete-null-pointer-checks -Wall"; phpize && ./configure --enable-phalcon && make -j4 && sudo make install && sed -i '$ a \\n[Phalcon]\nextension=phalcon.so\n'  /home/scrutinizer/.phpenv/versions/5.6.16/etc/php.ini
#      - pwd
##      - cd src/react
##      - npm install
##      - cd ../..
#  #project_setup:
#  #  override:
#  #    - 'mysql -e "create database if not exists euromillions_test"'
#  #    - 'dev-scripts/schema_migration.sh scrutinizer'
#
##  tests:
##    override:
##      -
##        command: src/vendor/bin/phpunit --log-junit shippable/testresults/junit.xml --coverage-clover=coverage.clover --configuration src/tests/phpunit.xml --testsuite=unit+integration
##        coverage:
##          file: coverage.clover
##          format: php-clover
#
#
#
