version: '3.4'

services:
  database:
    image: rmrbest/percona
    volumes:
      - "database_volume:/var/lib/mysql"
    networks:
      - backend
    environment:
      REPLICATION: 'true'
      REPLICATION_NODE: 1
      REPLICATION_SLAVE_USER: slave_db1
      REPLITACION_SLAVE_PASSWORD: euromillions
      MYSQL_ROOT_PASSWORD: tpl9
      MYSQL_USER: euromillions
      MYSQL_PASSWORD: tpl9
      MYSQL_DATABASE: euromillions

  web:
    build:
      target: staging
    image: staging-web:latest

  php:
    build:
      target: staging
    image: staging-php:latest
    depends_on:
      - redis
      - database
    volumes:
      - "./src:/var/www"
    links:
      - redis:redis
      - database:mysql

  phpcron:
    image: staging-phpcron:latest
    links:
      - redis:redis
      - database:mysql

volumes:
  database_volume: