version: '2'
services:

  redis:
    image: redis:latest

  web:
    image: panamedialottery/euromillions-web:prod
    volumes_from:
    - php
    depends_on:
    - php
    links:
    - php:php
    environment:
      EM_ENV: ${EM_ENV}

  php:
    image: panamedialottery/euromillions-php:prod
    depends_on:
    - redis
    - database
    links:
    - redis:redis
    - database:mysql
    environment:
      EM_ENV: ${EM_ENV}
      AWS_ACCESS_KEY_ID: AKIAJ4KKQDQVDECKXUNQ
      AWS_SECRET_ACCESS_KEY: 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

  phpcron:
    image: panamedialottery/euromillions-php:cron
    volumes_from:
    - php
    depends_on:
    - redis
    - database
    links:
    - redis:redis
    - database:mysql
    environment:
      EM_ENV: ${EM_ENV}
      AWS_ACCESS_KEY_ID: AKIAJ4KKQDQVDECKXUNQ
      AWS_SECRET_ACCESS_KEY: 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