version: '3.4'

services:
  redis:
    image: redis:latest
    networks:
      - backend

  web:
    image: panamedialottery/euromillions-web:prod
    depends_on:
      - php
    links:
      - php:php
    networks:
      - backend
    environment:
      EM_ENV: ${EM_ENV}

  php:
    image: panamedialottery/euromillions-php:prod
    depends_on:
      - redis
    links:
      - redis:redis
    networks:
      - backend
    environment:
      EM_ENV: ${EM_ENV}
      AWS_ACCESS_KEY_ID: AKIAJ4KKQDQVDECKXUNQ
      AWS_SECRET_ACCESS_KEY: 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

  phpcron:
    image: panamedialottery/euromillions-php:cron
    depends_on:
      - redis
    volumes:
      - "./src:/var/www"
    links:
      - redis:redis
    networks:
      - backend
    environment:
      EM_ENV: ${EM_ENV}
      AWS_ACCESS_KEY_ID: AKIAJ4KKQDQVDECKXUNQ
      AWS_SECRET_ACCESS_KEY: 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

networks:
  backend: {}
  frontend: {}