version: '2'
services:

  web:
    image: panamedialottery/euromillions-web:staging
    labels:
      io.rancher.scheduler.affinity:host_label: em_hostname=china

  php:
    image: panamedialottery/euromillions-php:staging
    links:
      - redis
      - database
    depends_on:
      - redis

  phpcron:
    links:
      - redis
    depends_on:
    - redis