# This docker-compose.yml is for devel environment only. (On staging / prod we use the version 2)
version: '3.4'

services:
  database:
    image: mysql:5.6
    volumes:
      - "database_volume:/var/lib/mysql"
    networks:
      backend:
        ipv4_address: ${EM_DOCKER_DATABASE_IP}
    environment:
      MYSQL_ROOT_PASSWORD: tpl9
      MYSQL_USER: euromillions
      MYSQL_PASSWORD: tpl9
      MYSQL_DATABASE: euromillions

  redis:
    image: redis:latest
    networks:
      - backend

  web:
    build:
      context: devOps/docker/web
      target: devel
    image: panamedialottery/euromillions-web:devel
    volumes:
      - "./src:/var/www"
    depends_on:
      - php
    links:
      - php:php
    networks:
      - backend
    environment:
      EM_ENV: ${EM_ENV}

  php:
    build:
      context: devOps/docker/php
      dockerfile: Dockerfile-devel
      target: devel
    image: panamedialottery/euromillions-php:devel
    volumes:
      - "./src:/var/www"
    depends_on:
      - redis
      - database
    links:
      - redis:redis
      - database:mysql
    networks:
      - backend
    environment:
      EM_ENV: ${EM_ENV}
      AWS_ACCESS_KEY_ID: AKIAJ4KKQDQVDECKXUNQ
      AWS_SECRET_ACCESS_KEY: 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
      XDEBUG_CONFIG: remote_host=172.10.0.1 remote_enable=1 remote_autostart=1 remote_log=/tmp/xdebug.log

  phpcron:
    build:
      context: devOps/docker/php
      dockerfile: Dockerfile-devel
      target: cron
    image: panamedialottery/euromillions-php:cron
    volumes:
      - "./src:/var/www"
    depends_on:
      - redis
      - database
    links:
      - redis:redis
      - database:mysql
    networks:
      - backend
    environment:
      EM_ENV: ${EM_ENV}
      AWS_ACCESS_KEY_ID: AKIAJ4KKQDQVDECKXUNQ
      AWS_SECRET_ACCESS_KEY: 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

  varnish:
    build: devOps/docker/varnish
    image: panamedialottery/euromillions-varnish:devel
    depends_on:
      - web
    links:
      - web:backend
    networks:
      backend: {}
      frontend:
        ipv4_address: ${EM_DOCKER_VARNISH_IP}
    environment:
      EM_ENV: ${EM_ENV}


  util-nodejs:
    build: devOps/docker/util-nodejs
    image: euromillions-util-nodejs:devel
    command: sleep infinity
    working_dir: "/var/www"
    volumes:
      - "./src:/var/www"

  util-php:
    build:
      context: devOps/docker/php
      dockerfile: Dockerfile-devel
      target: tools
    image: euromillions-util-php:devel
    depends_on:
      - redis
      - database
    links:
      - redis:redis
      - database:mysql
    command: sleep infinity
    volumes:
      - "./src:/var/www"
    networks:
      - backend
    environment:
      EM_ENV: ${EM_ENV}
      AWS_ACCESS_KEY_ID: AKIAJ4KKQDQVDECKXUNQ
      AWS_SECRET_ACCESS_KEY: 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

volumes:
  database_volume:

networks:
  backend:
    ipam:
      config:
      - subnet: ${EM_DOCKER_BACKEND_SUBNET}
  frontend:
    ipam:
      config:
      - subnet: ${EM_DOCKER_FRONTEND_SUBNET}