# This docker-compose.yml is for test environment only.
version: '3.4'
services:

  redis:
    image: redis:latest

  database:
    image: mysql:5.6
    environment:
      MYSQL_ROOT_PASSWORD: tpl9
      MYSQL_USER: euromillions
      MYSQL_PASSWORD: tpl9
      MYSQL_DATABASE: euromillions

  php:
    build:
      context: .
      dockerfile: devOps/docker/php/Dockerfile
      target: tools
    volumes:
      - "./src:/var/www"
    depends_on:
      - redis
      - database
    links:
      - redis
      - database
    environment:
      EM_ENV: test
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}