version: '2'
services:

  loadbalancer:
    scale: 1
    start_on_create: true
    lb_config:
      certs: []
      config: timeout server 5m
      default_cert: "*.euromillions.com"
      port_rules:
      - priority: 1
        protocol: https
        service: web
        source_port: 443
        target_port: 80
      - priority: 2
        protocol: http
        service: web
        source_port: 80
        target_port: 80
    health_check:
      healthy_threshold: 2
      response_timeout: 2000
      port: 42
      unhealthy_threshold: 3
      initializing_timeout: 60000
      interval: 2000
      strategy: recreate
      reinitializing_timeout: 60000

  redis:
    scale: 1
    upgrade_strategy:
      start_first: true
    health_check:
      healthy_threshold: 2
      response_timeout: 5000
      port: 6379
      unhealthy_threshold: 3
      initializing_timeout: 10000
      interval: 2000
      strategy: none
      reinitializing_timeout: 1000

  web:
    scale: 1
    upgrade_strategy:
      start_first: true
    health_check:
      response_timeout: 2000
      healthy_threshold: 2
      port: 80
      unhealthy_threshold: 3
      initializing_timeout: 60000
      interval: 30000
      strategy: recreate
      request_line: GET "/readme.txt" "HTTP/1.0"
      reinitializing_timeout: 60000

  php:
    scale: 1
    upgrade_strategy:
      start_first: true
    health_check:
      healthy_threshold: 2
      response_timeout: 2000
      port: 9000
      unhealthy_threshold: 3
      initializing_timeout: 10000
      interval: 2000
      strategy: recreate
      reinitializing_timeout: 1000

  phpcron:
    scale: 1
    upgrade_strategy:
      start_first: true