<div class="page-header">
	<h1><?=$this->translate('transactions')?></h1>
</div>

<div class="panel panel-default">
	<div class="panel-body">
		<form action="<?=$this->url(Array('module' => 'default','controller' => 'admin_log_transactions', 'action' => 'details'),false,true )?>" role="form" method="post" class="col-md-12 form-inline">
			<div class="form-group">
				<label>Select Priority</label>
				<?=$this->Selectmenu('transaction_type',$this->transtypes,$this->searchParams['transaction_type'],'form-control') ?>
			</div>
			<div class="form-group">
				<button class="btn btn-primary" type="submit"><i class="glyphicon glyphicon-repeat"></i></button>
			</div>
		</form>
	</div>
</div>
<table class="table table-striped table-bordered">
	<thead>
		<tr>
			<th>#</th>
			<th>date</th>
			<th>user_id</th>
			<th>type</th>
			<th>state</th>
			<th>amount</th>
			<th><?=$this->translate('details')?></th>
		</tr>
	</thead>
	<? foreach($this->items as $item) { ?>

		<tr>
			<td><?=$item['transaction_id']?></td>
			<td><?=$item['transaction_date']?></td>
			<td><?=$item['user_id']?></td>
			<td><?=$item['transaction_type']?></td>
			<td><?=$item['state']?></td>
			<td><?=$item['amount']?></td>
			<td><a class="popup" href="<?=$this->url(Array('module' => 'default','controller' => 'admin_log_transactions', 'action' => 'details','id' => $item['transaction_id']),false,true )?>"><?=$this->translate('details')?></a></td>
		</tr>
	<? } ?>
	</table>
<?=$this->paginator?>