---
env: 'staging'
display_errors: '1'
display_startup_errors: '1'

domain_url: 'beta.euromillions.com/'

database_host: 'stagingdatabases.cywoihxulkwc.eu-west-1.rds.amazonaws.com'
database_user: 'euromillions'
database_pass: 'je96bmdhaVdH6oCt'
is_development_mode: 'true'

lottorisq_endpoint: 'https://cd2zqkxcnk.execute-api.us-west-2.amazonaws.com/beta/powerball'
lottorisq_apikey: 'OwhqLS0ue13Gr3tm1BsoKaiYJ8gpnb5t7xNJTTk3'


restricted_access_activated: '1'
restricted_access_ips: '62.57.159.66,10.0.2.2'