#!/bin/bash
cp githooks/* .git/hooks
#
while read -r line; do
    if [[ $line == "vagrant_config/"* ]] || [[ $line == "Vagrantfile" ]]
    then
        ./restart-dev-environment.sh
    fi
    if [[ $line == "docker/"* ]]
    then
        ./restart-dev-environment.sh
    fi
done <<< $(eval "git diff --name-only HEAD@{1} HEAD")

touch "environment_$EM_ENV"