#!/bin/bash
cp githooks/* .git/hooks
#
while read -r line; do
    if [[ $line == "vagrant_config/"* ]] || [[ $line == "Vagrantfile" ]]
    then
        vagrant reload --provision
    fi
    if [[ $line == "docker/"* ]]
    then
        vagrant reload --provision
    fi
    if [[ $line == "src/apps/web/migrations/"* ]]
    then
        vagrant reload
    fi
    if [[ $line == "src/apps/web/migrations_data/"* ]]
    then
        vagrant reload
    fi

    if [[ $line == "composer.json" ]]
    then
        composer install
    fi
done <<< $(eval "git diff --name-only HEAD@{1} HEAD")

vagrant ssh -c "/vagrant/dev-scripts/schema_and_data_migration.sh dev"