<div class="row">
	<div class="col-lg-12">
		<h1 id="overview"><?=$this->translate('payout_management')?></h1>
	</div>
</div>
	<? $type = ($this->type)? $this->type :'new'; ?>
	<?=$this->partial('billing/admin/payout/navigation.phtml', array('active' => $type)); ?>
<div class="row">
	<div class="col-md-12 col-lg-12 col-sm-12">
		<div class="table-responsive">
			<table class="table table-striped table-bordered">
				<thead>
					<tr>
						<th>ID</th>
						<th><?=$this->translate('amount')?></th>
						<th><?=$this->translate('date')?></th>
						<th><?=$this->translate('type')?></th>
						<th><?=$this->translate('options')?></th>
					</tr>
				</thead>
				<? foreach($this->items as $item){ ?>
				<tr>
					<td><?=$item['transaction_id']?></td>
					<td><?=$this->Currency()->get($item['amount'])?></td>
					<td><?=$this->Date($item['add_date'])?></td>
					<td><?=$item['payout_account_type']?></td>
					<td>
						<? if($this->type == 'new'){ ?>
							<a href="<?=$this->url(Array('action' => 'details','payout_id' => $item['payout_id']))?>" >
								<i class=" glyphicon glyphicon-log-in tip" title="<?=$this->translate('edit')?>"></i>
							</a>
						<? } else { ?>
							<a href="<?=$this->url(Array('action' => 'details','payout_id' => $item['payout_id']))?>">
								<i class="glyphicon glyphicon-search tip" title="<?=$this->translate('edit')?>"></i>
							</a>
						<? } ?>
					</td>
				</tr>
				<? } ?>
			</table>
			<?=$this->paginator ?>
		</div>
	</div>
</div>