<div class="row">
	<div class="container">
		<ul class="nav nav-tabs" role="tablist">
			<li <? if($this->active == 'new'){ ?>class="active"<? } ?>><a href="<?=$this->url(Array('action' => 'index','type' => 'new','page' => 1))?>">New</a></li>
			<li <? if($this->active == 'payout'){ ?>class="active"<? } ?>><a href="<?=$this->url(Array('action' => 'index','type' => 'payout','page' => 1))?>">Payout history</a></li>
			<li <? if($this->active == 'error'){ ?>class="active"<? } ?>><a href="<?=$this->url(Array('action' => 'index','type' => 'error','page' => 1))?>">Error</a></li>
		</ul>
	</div>
</div>
<br />