<div class="quickhelp">
	<p><?=$this->translate('play_index_index_quickhelp_description',array('<strong>','</strong>'))?></p>
	<br />
	<h4 style="text-align:left;"><?=$this->translate('play_index_index_quickhelp_headline')?></h4>
	<ul class="color">
		<li><span><?=$this->translate('play_index_index_howtoplay_step_1')?></span></li>
		<li><span><?=$this->translate('play_index_index_howtoplay_step_2')?></span></li>
		<li><span><?=$this->translate('play_index_index_howtoplay_step_3')?></span></li>
		<li><span><?=$this->translate('play_index_index_howtoplay_step_4')?></span></li>
		<li><span><?=$this->translate('play_index_index_howtoplay_step_5')?></span> <i class="icon-chkstyle icon-crossover"></i></li>
		<li><span><?=$this->translate('play_index_index_howtoplay_step_6')?></span> <i class="icon-chkstyle icon-multiple"></i></li>
	</ul>

	<p><?=$this->translate('play_index_index_quickhelp_question',array('<a class="color" href="' . $this->url(Array(),"Faq_Index",true) . '">', '</a>'))?></p>
	<div class="modal-controls">
		<a class="btn btn-primary"><?=$this->translate('okay')?></a>
	</div>
</div>