Vagrant.configure(2) do |config|
  config.vm.box = "ubuntu/trusty64"
  config.vm.provision :shell, path: "bootstrap.sh", privileged: false
  config.vm.network "forwarded_port", guest: 8080, host: 8080
  config.vm.synced_folder "../docker/", "/docker"
  config.vm.synced_folder "../oldsrc/", "/oldsrc"
  config.vm.synced_folder "../src/", "/src"
end
