Vagrant.configure(2) do |config|
    config.vm.provider "virtualbox" do |v|
        v.customize ["modifyvm", :id, "--cpuexecutioncap", "50"]
        v.memory = 2048
    end
    config.vm.box = "ubuntu/trusty64"
    config.vm.provision :shell, path: "bootstrap.sh", privileged: false
    config.vm.network "forwarded_port", guest: 8080, host: 8080
    config.vm.synced_folder "../docker/", "/docker"
    config.vm.synced_folder "../src/", "/src"
end
