develdbmaster:
  build: ./devel-dbmaster
  ports:
    - "3306:3306"
  volumes:
    - /home/vagrant/mysqldata:/var/lib/mysql/
  environment:
    MYSQL_ROOT_PASSWORD: tpl9
    MYSQL_DATABASE: euromillions

develredis:
  image: redis
  ports:
    - "6379:6379"

develweb:
  build: ./devel-web
  ports:
    - "80:80"
    - "443:443"
  volumes:
    - /var/www:/var/www
    - /vagrant/src/docker/devel-web/nginxconfig:/etc/nginx/sites-enabled
    - /vagrant/src/docker/devel-web/certs:/etc/nginx/ssl
  links:
    - develdbmaster:mysql
    - develredis:redis
  environment:
    EM_ENV: development

compass:
  image: antonienko/compass-watch
  command: watch --poll /src/compass
  volumes:
    - /var/www:/src

