<!DOCTYPE html>
<html lang="en">
  <head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<meta name="description" content="">
	<meta name="author" content="">
	<link rel="shortcut icon" href="<?=$this->baseUrl() ?>/favicon.png">
	<link rel="shortcut icon" href="<?=$this->baseUrl() ?>/templates/default/images/favicon.ico" type="image/x-icon" />
	<title>Euromillions Admin</title>
	<!-- Bootstrap core CSS -->
	<link href="<?=$this->baseUrl() ?>/templates/admin/assets/bootstrap/css/bootstrap.css" rel="stylesheet">
	<!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
	<!--[if lt IE 9]>
	  <script src="<?=$this->baseUrl() ?>/templates/admin/assets/bootstrap/js/html5shiv.js"></script>
	  <script src="<?=$this->baseUrl() ?>/templates/admin/assets/bootstrap/js/respond.min.js"></script>
	<![endif]-->

	<link href="<?=$this->baseUrl() ?>/templates/admin/css/style.css" rel="stylesheet">
	<link href="<?=$this->baseUrl() ?>/templates/admin/css/flags.css" rel="stylesheet">

	<!-- Placed at the end of the document so the pages load faster -->
	<script src="<?=$this->baseUrl() ?>/templates/admin/assets/bootstrap/js/jquery.js"></script>
	<script src="<?=$this->baseUrl() ?>/templates/admin/assets/bootstrap/js/bootstrap.min.js"></script>

	<link href="<?=$this->baseUrl() ?>/templates/admin/assets/datepicker/css/datepicker.css" rel="stylesheet" />
	<script src="<?=$this->baseUrl() ?>/templates/admin/assets/datepicker/js/bootstrap-datepicker.js"></script>

	<link href="<?=$this->baseUrl() ?>/templates/admin/assets/daterangepicker/daterangepicker-bs3.css" rel="stylesheet">
	<script src="<?=$this->baseUrl() ?>/templates/admin/assets/daterangepicker/moment.min.js"></script>
	<script src="<?=$this->baseUrl() ?>/templates/admin/assets/daterangepicker/daterangepicker.js"></script>

	<script src="<?=$this->baseUrl() ?>/templates/admin/assets/bootstrap.file-input.js"></script>
	<link href="<?=$this->baseUrl() ?>/templates/admin/assets/jquery-editable/css/jquery-editable.css" rel="stylesheet" />
	<script src="<?=$this->baseUrl() ?>/templates/admin/assets/jquery-editable/js/jquery-editable-poshytip.js"></script>
	<script src="<?=$this->baseUrl() ?>/templates/global/js/mo.updatechecker.js"></script>
	<script src="<?=$this->baseUrl() ?>/templates/admin/js/common.js"></script>
	</head>

  <body>
	<div class="navbar navbar-inverse navbar-fixed-top">
			<div class="navbar-heder">
				<button type="button" class="navbar-toggle sidebar-toggle pull-left" style="float:left;" data-toggle="collapse" data-target=".sidebar-ex1-collaps">
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
				</button>
				<!--button type="button" class="navbar-toggle" data-toggle="collapse" style="float:left;" data-target=".navbar-collapse">
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
				</button-->
				<a class="navbar-brand" href="<?=$this->url(Array('module' => 'default','controller' => 'admin', 'action' => 'index'),null,true )?>">EuroMillions</a>
			</div>
			<form act="" id="logout" method="post" style="display:none;"><input type="hidden" name="act" value="logout"></form>
			<div class="navbar-right">
				<ul class="nav navbar-nav">
					<li><a href="<?=$this->url(Array('module' => 'default','controller' => 'admin', 'action' => 'help'),null,true )?>" data-toggle="modal" data-target="#Modalbox"><i class="glyphicon glyphicon-info-sign"></i> <span class="hidden-xs"><?=$this->translate('help')?></span></a></li>
					<li><a href="/"><i class="glyphicon glyphicon-credit-card"></i></a></li>
					<li><a href="#" onclick="$('#logout').submit();"><i class="glyphicon glyphicon-off"></i></a></li>
				</ul>
			</div><!--/.nav-collapse -->

	</div>

	<div class="container-fluid">
		<div id="sidebar" class="col-sm-3 col-md-2 col-lg-2 sidebar hidden-xs">

			<? $explode = explode('_',$this->translation_prefix);
			   $themodule = $explode[0];?>
			<ul class="nav nav-sidebar" id="mainmenu">
				<li><?=$this->translation_prefix?></li>
				<li class="<?=($this->translation_prefix == 'default_admin_index')? 'active' : ''?>">
					<a href="<?=$this->url(Array('module' => 'default','controller' => 'admin', 'action' => 'index'),null,true )?>"><i class="glyphicon glyphicon-home"></i> Dashboard</a>
				</li>
				<? if (hasAccess("acp_article") || hasAccess("acp_faq") || hasAccess("acp_news")){ ?>
				<li class="<?=($themodule == 'article' || $themodule == 'news' || $themodule == 'faq')? 'active' : ''?>">
					<a href="#contentmenu" data-toggle="collapse" data-parent="#mainmenu"><i class="glyphicon glyphicon-file"></i> <?=$this->translate('contents')?>  <b class="caret"></b></a>
					<ul class="nav <?=($themodule == 'article' || $themodule == 'news' || $themodule == 'faq')? 'collapse in' : 'collapse'?>" id="contentmenu">
					<? if (hasAccess("acp_article")){ ?>
						<li>
							<a href="#menuarticle"  data-toggle="collapse" data-parent="#contentmenu"><?=$this->translate('article')?><b class="caret"></b></a>
							<ul class="nav <?=($themodule == 'article')? 'collapse in' : 'collapse'?>" id="menuarticle">
								<li><a href="<?=$this->url(Array('module' => 'article','controller' => 'admin', 'action' => 'index'),null,true )?>"><i class="glyphicon glyphicon-align-justify"></i> Manage / Edit</a></li>
								<li><a href="<?=$this->url(Array('module' => 'article','controller' => 'admin', 'action' => 'add'),null,true)?>"><i class="glyphicon glyphicon-plus"></i> <?=$this->translate('add')?></a></li>
							</ul>
						</li>
					<? } ?>
					<? if (hasAccess("acp_news")){ ?>
						<li>
							<a href="#menunews"  data-toggle="collapse" data-parent="#contentmenu"><?=$this->translate('news')?><b class="caret"></b></a>
							<ul class="nav <?=($themodule == 'news')? 'collapse in' : 'collapse'?>" id="menunews">
								<li><a href="<?=$this->url(Array('module' => 'news','controller' => 'admin', 'action' => 'index'),null,true )?>"><i class="glyphicon glyphicon-align-justify"></i> Manage / Edit</a></li>
								<li><a href="<?=$this->url(Array('module' => 'news','controller' => 'admin', 'action' => 'add'),null,true)?>"><i class="glyphicon glyphicon-plus"></i> <?=$this->translate('add')?></a></li>
							</ul>
						</li>
					<? } ?>
					<? if (hasAccess("acp_faq")){ ?>
						<li>
							<a href="#menufaq"  data-toggle="collapse" data-parent="#contentmenu"><?=$this->translate('faq')?><b class="caret"></b></a>
							<ul class="nav <?=($themodule == 'faq')? 'collapse in' : 'collapse'?>" id="menufaq">
								<li><a href="<?=$this->url(Array('module' => 'faq','controller' => 'admin', 'action' => 'index'),null,true )?>"><i class="glyphicon glyphicon-align-justify"></i> Manage / Edit</a></li>
								<li><a href="<?=$this->url(Array('module' => 'faq','controller' => 'admin', 'action' => 'add'),null,true)?>"><i class="glyphicon glyphicon-plus"></i> <?=$this->translate('add')?></a></li>
							</ul>
						</li>
					<? } ?>
					</ul>
				</li>
				<? } ?>
				<? if (hasAccess("acp_translation")){ ?>
				<li>
					<a href="#menutranslation" data-toggle="collapse" data-parent="#mainmenu"><i class="glyphicon glyphicon-text-width"></i> <?=$this->translate('translations')?> <b class="caret"></b></a>
					<ul class="nav <?=($themodule == 'translation')? 'collapse in' : 'collapse'?>" id="menutranslation">
						<li>
							<a href="<?=$this->url(Array('module' => 'translation','controller' => 'admin', 'action' => 'index'),null,true)?>"><i class="glyphicon glyphicon-align-justify"></i> Manage / Edit</a>
						</li>
						<li>
							<a href="<?=$this->url(Array('module' => 'translation','controller' => 'admin', 'action' => 'add'),null,true)?>"><i class="glyphicon glyphicon-plus"></i> <?=$this->translate('add')?></a>
						</li>
					</ul>
				</li>
				<? } ?>

				<? if (hasAccess("acp_stats")){ ?>
				<li class="<?=($this->translation_prefix == 'stats_admin_index')? 'active' : ''?>">
					<a href="<?=$this->url(Array('module' => 'default','controller' => 'adminstats', 'action' => 'index'),null,true )?>"><i class="glyphicon glyphicon-signal"></i> <?=$this->translate('statistics')?> </a>
				</li>
				<? } ?>

				<? if (hasAccess("acp_lottery")){ ?>
				<li class="<?=($this->translation_prefix == 'lottery_admin_index')? 'active' : ''?>">
					<a href="#menulotteryem" data-toggle="collapse" data-parent="#mainmenu"><i class="glyphicon glyphicon-asterisk"></i> <?=$this->translate('lottery')?> <b class="caret"></b></a>
					<ul class="nav <?=($themodule == 'lottery')? 'collapse in' : 'collapse'?>" id="menulotteryem">
						<li>
							<a href="<?=$this->url(Array('module' => 'lottery','controller' => 'admin_euromillions_results', 'action' => 'index'),null,true)?>"><i class="glyphicon glyphicon-asterisk"></i> <?=$this->translate('draws')?></a>
						</li>
						<li>
							<a href="<?=$this->url(Array('module' => 'lottery','controller' => 'admin_euromillions_log_lc', 'action' => 'index'),null,true)?>"><i class="glyphicon glyphicon-list-alt"></i> LC <?=$this->translate('log')?></a>
						</li>
					</ul>
				</li>
				<? } ?>

				<? if (hasAccess("acp_user")){ ?>
				<li class="<?=($this->translation_prefix == 'user_admin_index')? 'active' : ''?>">
					<a href="<?=$this->url(Array('module' => 'user','controller' => 'admin', 'action' => 'index'),null,true )?>"><i class="glyphicon glyphicon-user"></i> <?=$this->translate('user')?></a>
				</li>
				<? } ?>
				<? if (hasAccess("acp_billing_payout")){ ?>
				<li class="<?=($this->translation_prefix == 'billing_admin_payout_index')? 'active' : ''?>">
					<a href="<?=$this->url(Array('module' => 'billing','controller' => 'admin_payout', 'action' => 'index'),null,true )?>"><i class="glyphicon glyphicon-euro"></i> <?=$this->translate('payouts')?></a>
				</li>
				<? } ?>
				<? if (hasAccess("acp_default_country") || hasAccess("acp_default_acl") || hasAccess("acp_log")){ ?>
				<li class="<?=($themodule == 'default' && ($explode[2] == 'log' || $explode[2] == 'country' || $explode[2] == 'acl' ))? 'active' : ''?>">
					<a href="#systemtmenu" data-toggle="collapse" data-parent="#mainmenu"><i class="glyphicon glyphicon-cog"></i> <?=$this->translate('system_settings')?>  <b class="caret"></b></a>
					<ul class="nav <?=($themodule == 'default' && ($explode[2] == 'log' || $explode[2] == 'country' || $explode[2] == 'acl' ) )? 'collapse in' : 'collapse'?>" id="systemtmenu">
						<? if (hasAccess("acp_default_country")){ ?>
						<li>
							<a href="<?=$this->url(Array('module' => 'default','controller' => 'admin_country', 'action' => 'index'),null,true )?>"><?=$this->translate('country_settings')?></a>
						</li>
						<? } ?>
						<? if (hasAccess("acp_default_currency")){ ?>
						<li>
							<a href="<?=$this->url(Array('module' => 'default','controller' => 'admin_currency', 'action' => 'index'),null,true )?>"><?=$this->translate('currency_settings')?></a>
						</li>
						<? } ?>
						<? if (hasAccess("acp_default_acl")){ ?>
						<li>
							<a href="<?=$this->url(Array('module' => 'default','controller' => 'admin_acl', 'action' => 'index'),null,true )?>"><?=$this->translate('acl_settings')?></a>
						</li>
						<? } ?>
						<? if (hasAccess("acp_log")){ ?>
						<li class="<?=($themodule == 'default' && ($explode[2] == 'log'))? 'active' : ''?>">
							<a href="#logmenu" data-toggle="collapse" data-parent="#systemtmenu"><i class="glyphicon glyphicon-list-alt"></i> <?=$this->translate('logs')?>  <b class="caret"></b></a>
							<ul class="nav <?=($themodule == 'default' && ($explode[2] == 'log') )? 'collapse in' : 'collapse'?>" id="logmenu">
								<li>
									<a href="<?=$this->url(Array('module' => 'default','controller' => 'admin_log_system', 'action' => 'index'),null,true )?>"><?=$this->translate('system')?></a>
								</li>
								<li>
									<a href="<?=$this->url(Array('module' => 'default','controller' => 'admin_log_transactions', 'action' => 'index'),null,true )?>"><?=$this->translate('transactions')?></a>
								</li>
							</ul>
						<? } ?>
					</ul>
				</li>
				<? } ?>
			 </ul>
		</div>
		<div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
			<div id="infobox">
				<div class="user box col-xs-12 col-sm-6 col-md-6 col-lg-6">
					<div class="total">
						<i class="glyphicon glyphicon-user"></i> <span>12</span>
					</div>
					<div class="details"></div>
				</div>
				<div class="emaillist box col-xs-12 col-sm-6 col-md-6 col-lg-6">
					<div class="total">
						<i class="glyphicon glyphicon-envelope"></i> <span>as</span>
					</div>
					<div class="details"></div>
				</div>
				<span class="clear"></span>
			</div>
			<?=$this->navigation()->menu();?>
			<?=$this->layout()->content; ?>
		</div>
	</div>

		<!-- Modal -->
		<div class="modal fade" tabindex="-1"  id="acpmodal" role="dialog" aria-hidden="true">
			<div class="modal-dialog">
				<div class="modal-content"></div>
			</div>
		</div>
		<script>
			$(document).ready(function(){
				$('body').moUpdatechecker({
					data_url: '<?=$this->url(Array('module' => 'default','controller' => 'adminstats', 'action' => 'livestatsajr'),null,true )?>',
					name:'updaterequest', type:'data',onReturn: function(){	getRequestReturn(this);	} });
			});
		</script>

  </body>
</html>