<div class="pagename" id="statsoverview">
	<div class="page-header">
		<h1><?=$this->translate('transactions')?></h1>
	</div>
	<?=$this->partial('default/adminstats/navigation.phtml', array('active' => 'billings')); ?>

		<table class="table table-striped table-bordered">
			<tr>
				<th>ID</th>
				<th><?=$this->translate('date')?></th>
				<th><?=$this->translate('type')?></th>
				<th><?=$this->translate('status')?></th>
				<th><?=$this->translate('lines')?></th>
				<th><?=$this->translate('income')?></th>
				<th><?=$this->translate('commission')?></th>
				<th><?=$this->translate('option')?></th>
			</tr>
			<tr>
				<td></td>
				<td></td>
				<td></td>
				<td></td>
				<td></td>
				<td></td>
				<td></td>
				<td><a class="popup" href="#" data-href="<?=$this->url(Array('action' => 'drawdetails','draw_id' => 734, 'lottery' => 'euromillions', 'customer_id' => '0'))?>"><?=$this->translate('details')?></a></td>
			</tr>

		</table>

</div>
