<div class="pagename" id="statsoverview">
	<div class="page-header">
		<h1><?=$this->translate('draws_for_lottery',array($this->lottery))?></h1>
	</div>
	<?=$this->partial('default/adminstats/navigation.phtml', array('active' => 'draws')); ?>

		<table class="table table-striped table-bordered">
			<tr>
				<th>ID</th>
				<th><?=$this->translate('date')?></td>
				<th><?=$this->translate('status')?></td>
				<th><?=$this->translate('lines')?></td>
				<th><?=$this->translate('gross_revenue')?></td>
				<th class="danger"><?=$this->translate('gross_profit')?></td>
				<th><?=$this->translate('options')?></td>
			</tr>
			<? foreach($this->items as $draw){?>
			<tr class="<?=($draw['status'] == 'open')? 'warning':'success'; ?>">
				<td><?=$draw['draw_id']?></td>
				<td><?=$this->Date($draw['date']);?></td>
				<td><?=$draw['status']?></td>
				<td><?=$draw['bought']?></td>
				<td style="text-align:right;"><?=$this->Currency()->get($draw['bought_total_amount']);?></td>
				<td style="text-align:right;"><?=$this->Currency()->get($draw['profit_total_amount']);?></td>
				<td><a class="popup" href="#" data-href="<?=$this->url(Array('action' => 'drawdetails','draw_id' => $draw['draw_id'], 'lottery' => 'euromillions', 'customer_id' => '0'))?>"><?=$this->translate('details')?></a></td>
			<? } ?>
			</tr>
		</table>
		<?=$this->paginator ?>
</div>
