<div class="modal-header">
	<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
	<h4 class="modal-title"><?=$this->translate('details_for_draw_id',array($this->draw_id))?> - <?=$this->Date($this->details['date']);?></h4>
</div>
<style>
	.modal-body td {text-align:right;}
</style>
<div class="modal-body">
	<table class="table table-striped">
		<tr>
			<th><?=$this->translate('lottery')?></th>
			<td><?=$this->lottery ?></td>
			<th><?=$this->translate('customer')?></th>
			<td><?=$this->customer_id ?></td>
		</tr>
		<tr>
			<th><?=$this->translate('status')?></th>
			<td><?=$this->details['status'] ?></td>
			<th><?=$this->translate('lines')?></th>
			<td><?=$this->details['bought'] ?></td>
		</tr>
		<tr>
			<th><?=$this->translate('gross_revenue')?></th>
			<td><?=$this->Currency()->get($this->details['bought_total_amount']); ?></td>
			<th class="danger"><?=$this->translate('gross_profit')?></th>
			<td class="danger"><?=$this->Currency()->get($this->details['profit_total_amount']); ?></td>
		</tr>
		<tr>
			<th><?=$this->translate('winners')?></th>
			<td><?=$this->details['won'] ?></td>
			<th><?=$this->translate('amount_won')?></th>
			<td><?=$this->Currency()->get($this->details['won_total_amount']); ?></td>
			<td></td>
		</tr>
		<tr>
			<th><?=$this->translate('add_to_cart')?></th>
			<td><?=$this->details['add_to_cart'] ?></td>
			<th><?=$this->translate('remove_from_cart')?></th>
			<td><?=$this->details['remove_from_cart'] ?></td>
		</tr>
		<tr>
			<th><?=$this->translate('validation_ok')?></th>
			<td><?=$this->details['validation_ok'] ?></td>
			<th><?=$this->translate('validation_error')?></th>
			<td><?=$this->details['validation_error'] ?></td>
		</tr>
	</table>
	<table class="table table-striped table-bordered">
		<tr>
			<th><?=$this->translate('product')?></th>
			<th><?=$this->translate('lines')?></th>
			<th><?=$this->translate('amount')?></th>
			<th><?=$this->translate('winners')?></th>
			<th><?=$this->translate('amount_won')?></th>
		</tr>
		<? foreach($this->products as $product){ ?>
		<tr>
			<td><?=$product['product_id']?></td>
			<td><?=$product['bought']?></td>
			<td><?=$this->Currency()->get($product['bought_total_amount']);?></td>
			<td><?=$product['won']?></td>
			<td><?=$this->Currency()->get($product['won_total_amount']);?></td>
		</tr>
		<? } ?>
	</table>
</div>
<div class="modal-footer">
	<a type="button" class="btn btn-default" data-dismiss="modal"><?=$this->translate('close')?></a>
</div>