<div class="row">
	<div class="container">
		<ul class="nav nav-tabs" role="tablist">
			<li <? if($this->active == 'overview'){ ?>class="active"<? } ?>><a href="<?=$this->url(Array('module' => 'default','controller' => 'adminstats','action' => 'index'),false,true)?>">Overview</a></li>
			<li <? if($this->active == 'draws'){ ?>class="active"<? } ?>><a href="<?=$this->url(Array('module' => 'default','controller' => 'adminstats','action' => 'draws'),false,true)?>">Draw History</a></li>
			<li <? if($this->active == 'billings'){ ?>class="active"<? } ?>><a href="<?=$this->url(Array('module' => 'default','controller' => 'adminstats','action' => 'billings'),false,true)?>">Billings</a></li>
			<li <? if($this->active == 'transactioncosts'){ ?>class="active"<? } ?>><a href="<?=$this->url(Array('module' => 'default','controller' => 'adminstats','action' => 'transactioncosts'),false,true)?>">Transaction Costs</a></li>
			<li <? if($this->active == 'useronline'){ ?>class="active"<? } ?>><a href="<?=$this->url(Array('module' => 'default','controller' => 'adminstats', 'action' => 'useronline'),false,true)?>">User online</a></li>
		</ul>
	</div>
</div>
<br />