<? $this->Statistic()->setData($this->statsdata);?>
<div class="pagename" id="statsoverview">
	<div class="page-header">
		<h1><?=$this->translate('statistics')?></h1>
	</div>
	<?=$this->partial('default/adminstats/navigation.phtml', array('active' => 'useronline')); ?>
	<form class="form-inline" role="form" action="<?=$this->url(Array('module' => 'default','controller' => 'adminstats','action' => 'useronline'),false,true)?>" method="post">
		<input type="hidden" name="customer_id" value="<?=$this->filter['customer_id'] ?>" />
		<div class="form-group pull-right">
			<button class="btn btn-primary btn-sm" type="submit"><i class="glyphicon glyphicon-repeat"></i></button>
		</div>
		<div class="form-group pull-right">
			<?=$this->Selectmenu('country',$this->arrCountries,$this->filter['country'],'form-control input-sm',$this->translate('all_countrys'));?>
		</div>
		<div id="reportrange" class="pull-right">
			<input type="hidden" name="start" id="start" value="<?=$this->filter['start'] ?>"/>
			<input type="hidden" name="end" id="end"  value="<?=$this->filter['end'] ?>"/>
			<i class="glyphicon glyphicon-calendar"></i>
			<span><?=$this->Date($this->filter['start'])?> - <?=$this->Date($this->filter['end'])?></span> <b class="caret"></b>
		</div>
		<span class="clear"></span>
	</form>
	<div class="row">
		<? if(count($this->data)>0){ ?>
		<table class="table table-striped">
			<tr>
				<th>Date</th>
				<?if($this->display_type != 'daily'){ ?><th>Country</th><? } ?>
				<th>Male</th>
				<th>Female</th>
				<th>Neutrum</th>
				<th>max </th>
			</tr>
			<? foreach($this->data as $item){ ?>
				<tr>
					<td><?=$item['year'] . '-' .$item['month'] . ' '. $item['day']?>  </td>
					<?if($this->display_type != 'daily'){ ?><td><?=$item['country']?></td><? } ?>
					<td><?=$item['gender_m']?></td>
					<td><?=$item['gender_f']?></td>
					<td><?=$item['gender_n']?></td>
					<td><?=$item['gender_m']+$item['gender_f']+$item['gender_n']?></td>
				</tr>
			<? } ?>
		</table>
		<? } else { ?>
			<strong>No Data for the selected Timerange: <?=$this->Date($this->filter['start'])?> - <?=$this->Date($this->filter['end'])?>
		<? } ?>
		</div>
	</div>
</div>
