<? foreach($this->list as $item){ ?>
	<div class="articleContainer">
		<h2><?=$item['page_title']?></h2>
		<div class="meta">
			<i class="glyphicon glyphicon-calendar"></i> <?=$this->Date($item['published_on'])?>
			<? if($item['published_by_name']){ ?>&nbsp;&nbsp;&nbsp;&nbsp;<i class="glyphicon glyphicon-user"></i> <?=$item['published_by_name']?><? } ?>
		</div>
		<p><?=$item['meta_description']?> ... <a href="<?=$item['detail_link']?>"  class="readmore"><?=$this->translate('read_more')?></a></p>
	</div>
<? } ?>