<div class="page-header">
	<h1><?=$this->translate('system_log')?></h1>
</div>
<div class="panel panel-default">
			<div class="panel-body">
				<form action="<?=$this->url(Array('module' => 'default','controller' => 'admin_log_system', 'action' => 'index'),null,true )?>" role="form" method="post" class="col-md-12 form-inline">
					<div class="form-group">
						<label>Select Priority</label>
						<?=$this->Selectmenu('priority',$this->priority,$this->searchParams['priority'],'form-control') ?>
					</div>
					<div class="form-group">
						<button class="btn btn-primary" type="submit"><i class="glyphicon glyphicon-repeat"></i></button>
					</div>
				</form>
			</div>
		</div>
<table class="table table-striped">
	<thead>
		<tr>
			<th>level</th>
			<th>user_id</th>
			<th>message</th>
			<th>created</th>
			<th>uri</th>
			<th>details</th>
		</tr>
	</thead>
	<? foreach($this->items as $item) { ?>
	<tbody>
		<tr>
			<td><?=$item['level']?></td>
			<td><?=$item['user_id']?></td>
			<td><?=$item['message']?></td>
			<td><?=$item['created']?></td>
			<td><?=$item['uri']?></td>
			<td><a class="popup" href="<?=$this->url(Array('module' => 'default','controller' => 'admin_log_system', 'action' => 'details','id' => $item['id']),false,true )?>"><?=$this->translate('details')?></a></td>
		</tr>
	</tbody>
	<? } ?>
	</table>
<?=$this->paginator?>