---
- name: include variables for environment
  include_vars: vars/{{ item }}.yml
  with_items:
    - default_vars
    - development_vars

- name: create template for environment
  template: src=config_tpl.j2 dest={{ playbook_dir }}/../src/apps/shared/config/development_config.ini
  ignore_errors: yes