---
- name: include variables for environment
  include_vars: vars/{{ item }}.yml
  with_items:
    - default_vars
    - test_vars
- name: create template for environment
  template: src=config_tpl.j2 dest={{ playbook_dir }}/../src/apps/shared/config/test_config.ini
  ignore_errors: yes

- name: include variables for environment
  include_vars: vars/{{ item }}.yml
  with_items:
    - default_vars
    - development_vars
- name: create template for environment
  template: src=config_tpl.j2 dest={{ playbook_dir }}/../src/apps/shared/config/development_config.ini
  ignore_errors: yes

- name: include variables for environment
  include_vars: vars/{{ item }}.yml
  with_items:
    - default_vars
    - shippable_vars
- name: create template for environment
  template: src=config_tpl.j2 dest={{ playbook_dir }}/../src/apps/shared/config/shippable_config.ini
  ignore_errors: yes

- name: include variables for environment
  include_vars: vars/{{ item }}.yml
  with_items:
    - default_vars
    - scrutinizer_vars

- name: create template for environment
  template: src=config_tpl.j2 dest={{ playbook_dir }}/../src/apps/shared/config/scrutinizer_config.ini
  ignore_errors: yes

- name: include variables for environment
  include_vars: vars/{{ item }}.yml
  with_items:
    - default_vars
    - staging_vars

- name: create template for environment
  template: src=config_tpl.j2 dest={{ playbook_dir }}/../src/apps/shared/config/staging_config.ini
  ignore_errors: yes