<?php

use Phinx\Seed\AbstractSeed;

class DrawResultsSeeder extends AbstractSeed
{
    /**
     * Run Method.
     *
     * Write your database seeder using this method.
     *
     * More information on writing seeders is available here:
     * http://docs.phinx.org/en/latest/seeding.html
     */
    public function run()
    {
        $data = [
            [
                'lottery_id' => 1,
                'draw_date' => '2016-05-10',
                'result_regular_number_one' => '1',
                'result_regular_number_two' => '2',
                'result_regular_number_three' => '3',
                'result_regular_number_four' => '4',
                'result_regular_number_five' => '5',
                'result_lucky_number_one' => '1',
                'result_lucky_number_two' => '2',
                'jackpot_amount' => '1500000000',
                'jackpot_currency_name' => 'EUR',
                'break_down_category_one_name' => '5 + 2',
                'break_down_category_one_winners' => '0',
                'break_down_category_one_lottery_prize_amount' => '0',
                'break_down_category_one_lottery_prize_currency_name' => 'EUR',
                'break_down_category_two_name' => '5 + 1',
                'break_down_category_two_winners' => '6',
                'break_down_category_two_lottery_prize_amount' => '2585218100',
                'break_down_category_two_lottery_prize_currency_name' => 'EUR',
                'break_down_category_three_name' => '5 + 0',
                'break_down_category_three_winners' => '20',
                'break_down_category_three_lottery_prize_amount' => '258521800',
                'break_down_category_three_lottery_prize_currency_name' => 'EUR',
                'break_down_category_four_name' => '4 + 2',
                'break_down_category_four_winners' => '64',
                'break_down_category_four_lottery_prize_amount' => '40394000',
                'break_down_category_four_lottery_prize_currency_name' => 'EUR',
                'break_down_category_five_name' => '4 + 1',
                'break_down_category_five_winners' => '1.156',
                'break_down_category_five_lottery_prize_amount' => '1956800',
                'break_down_category_five_lottery_prize_currency_name' => 'EUR',
                'break_down_category_six_name' => '4 + 0',
                'break_down_category_six_winners' => '3.419',
                'break_down_category_six_lottery_prize_amount' => '661600',
                'break_down_category_six_lottery_prize_currency_name' => 'EUR',
                'break_down_category_seven_name' => '3 + 2',
                'break_down_category_seven_winners' => '2.042',
                'break_down_category_seven_lottery_prize_amount' => '791300',
                'break_down_category_seven_lottery_prize_currency_name' => 'EUR',
                'break_down_category_eight_name' => '2 + 2',
                'break_down_category_eight_winners' => '29.431',
                'break_down_category_eight_lottery_prize_amount' => '252500',
                'break_down_category_eight_lottery_prize_currency_name' => 'EUR',
                'break_down_category_nine_name' => '3 + 1',
                'break_down_category_nine_winners' => '43.727',
                'break_down_category_nine_lottery_prize_amount' => '162600',
                'break_down_category_nine_lottery_prize_currency_name' => 'EUR',
                'break_down_category_ten_name' => '3 + 1',
                'break_down_category_ten_winners' => '128.707',
                'break_down_category_ten_lottery_prize_amount' => '92900',
                'break_down_category_ten_lottery_prize_currency_name' => 'EUR',
                'break_down_category_eleven_name' => '1 + 2',
                'break_down_category_eleven_winners' => '157.728',
                'break_down_category_eleven_lottery_prize_amount' => '133200',
                'break_down_category_eleven_lottery_prize_currency_name' => 'EUR',
                'break_down_category_twelve_name' => '2 + 1',
                'break_down_category_twelve_winners' => '592.167',
                'break_down_category_twelve_lottery_prize_amount' => '96000',
                'break_down_category_twelve_lottery_prize_currency_name' => 'EUR',
                'break_down_category_thirteen_name' => '2 + 0',
                'break_down_category_thirteen_winners' => '1.682.415',
                'break_down_category_thirteen_lottery_prize_amount' => '34600',
                'break_down_category_thirteen_lottery_prize_currency_name' => 'EUR',
            ],
            [
                'lottery_id' => 1,
                'draw_date' => '2016-05-06',
                'result_regular_number_one' => '3',
                'result_regular_number_two' => '5',
                'result_regular_number_three' => '7',
                'result_regular_number_four' => '9',
                'result_regular_number_five' => '11',
                'result_lucky_number_one' => '1',
                'result_lucky_number_two' => '2',
                'jackpot_amount' => '1500000000',
                'jackpot_currency_name' => 'EUR',
                'break_down_category_one_name' => '5 + 2',
                'break_down_category_one_winners' => '0',
                'break_down_category_one_lottery_prize_amount' => '0',
                'break_down_category_one_lottery_prize_currency_name' => 'EUR',
                'break_down_category_two_name' => '5 + 1',
                'break_down_category_two_winners' => '6',
                'break_down_category_two_lottery_prize_amount' => '2585218100',
                'break_down_category_two_lottery_prize_currency_name' => 'EUR',
                'break_down_category_three_name' => '5 + 0',
                'break_down_category_three_winners' => '20',
                'break_down_category_three_lottery_prize_amount' => '258521800',
                'break_down_category_three_lottery_prize_currency_name' => 'EUR',
                'break_down_category_four_name' => '4 + 2',
                'break_down_category_four_winners' => '64',
                'break_down_category_four_lottery_prize_amount' => '40394000',
                'break_down_category_four_lottery_prize_currency_name' => 'EUR',
                'break_down_category_five_name' => '4 + 1',
                'break_down_category_five_winners' => '1.156',
                'break_down_category_five_lottery_prize_amount' => '1956800',
                'break_down_category_five_lottery_prize_currency_name' => 'EUR',
                'break_down_category_six_name' => '4 + 0',
                'break_down_category_six_winners' => '3.419',
                'break_down_category_six_lottery_prize_amount' => '661600',
                'break_down_category_six_lottery_prize_currency_name' => 'EUR',
                'break_down_category_seven_name' => '3 + 2',
                'break_down_category_seven_winners' => '2.042',
                'break_down_category_seven_lottery_prize_amount' => '791300',
                'break_down_category_seven_lottery_prize_currency_name' => 'EUR',
                'break_down_category_eight_name' => '2 + 2',
                'break_down_category_eight_winners' => '29.431',
                'break_down_category_eight_lottery_prize_amount' => '252500',
                'break_down_category_eight_lottery_prize_currency_name' => 'EUR',
                'break_down_category_nine_name' => '3 + 1',
                'break_down_category_nine_winners' => '43.727',
                'break_down_category_nine_lottery_prize_amount' => '162600',
                'break_down_category_nine_lottery_prize_currency_name' => 'EUR',
                'break_down_category_ten_name' => '3 + 1',
                'break_down_category_ten_winners' => '128.707',
                'break_down_category_ten_lottery_prize_amount' => '92900',
                'break_down_category_ten_lottery_prize_currency_name' => 'EUR',
                'break_down_category_eleven_name' => '1 + 2',
                'break_down_category_eleven_winners' => '157.728',
                'break_down_category_eleven_lottery_prize_amount' => '133200',
                'break_down_category_eleven_lottery_prize_currency_name' => 'EUR',
                'break_down_category_twelve_name' => '2 + 1',
                'break_down_category_twelve_winners' => '592.167',
                'break_down_category_twelve_lottery_prize_amount' => '96000',
                'break_down_category_twelve_lottery_prize_currency_name' => 'EUR',
                'break_down_category_thirteen_name' => '2 + 0',
                'break_down_category_thirteen_winners' => '1.682.415',
                'break_down_category_thirteen_lottery_prize_amount' => '34600',
                'break_down_category_thirteen_lottery_prize_currency_name' => 'EUR',
            ],
            [
                'lottery_id' => 1,
                'draw_date' => '2016-05-03',
                'result_regular_number_one' => '13',
                'result_regular_number_two' => '15',
                'result_regular_number_three' => '17',
                'result_regular_number_four' => '19',
                'result_regular_number_five' => '21',
                'result_lucky_number_one' => '1',
                'result_lucky_number_two' => '2',
                'jackpot_amount' => '1500000000',
                'jackpot_currency_name' => 'EUR',
                'break_down_category_one_name' => '5 + 2',
                'break_down_category_one_winners' => '0',
                'break_down_category_one_lottery_prize_amount' => '0',
                'break_down_category_one_lottery_prize_currency_name' => 'EUR',
                'break_down_category_two_name' => '5 + 1',
                'break_down_category_two_winners' => '6',
                'break_down_category_two_lottery_prize_amount' => '2585218100',
                'break_down_category_two_lottery_prize_currency_name' => 'EUR',
                'break_down_category_three_name' => '5 + 0',
                'break_down_category_three_winners' => '20',
                'break_down_category_three_lottery_prize_amount' => '258521800',
                'break_down_category_three_lottery_prize_currency_name' => 'EUR',
                'break_down_category_four_name' => '4 + 2',
                'break_down_category_four_winners' => '64',
                'break_down_category_four_lottery_prize_amount' => '40394000',
                'break_down_category_four_lottery_prize_currency_name' => 'EUR',
                'break_down_category_five_name' => '4 + 1',
                'break_down_category_five_winners' => '1.156',
                'break_down_category_five_lottery_prize_amount' => '1956800',
                'break_down_category_five_lottery_prize_currency_name' => 'EUR',
                'break_down_category_six_name' => '4 + 0',
                'break_down_category_six_winners' => '3.419',
                'break_down_category_six_lottery_prize_amount' => '661600',
                'break_down_category_six_lottery_prize_currency_name' => 'EUR',
                'break_down_category_seven_name' => '3 + 2',
                'break_down_category_seven_winners' => '2.042',
                'break_down_category_seven_lottery_prize_amount' => '791300',
                'break_down_category_seven_lottery_prize_currency_name' => 'EUR',
                'break_down_category_eight_name' => '2 + 2',
                'break_down_category_eight_winners' => '29.431',
                'break_down_category_eight_lottery_prize_amount' => '252500',
                'break_down_category_eight_lottery_prize_currency_name' => 'EUR',
                'break_down_category_nine_name' => '3 + 1',
                'break_down_category_nine_winners' => '43.727',
                'break_down_category_nine_lottery_prize_amount' => '162600',
                'break_down_category_nine_lottery_prize_currency_name' => 'EUR',
                'break_down_category_ten_name' => '3 + 1',
                'break_down_category_ten_winners' => '128.707',
                'break_down_category_ten_lottery_prize_amount' => '92900',
                'break_down_category_ten_lottery_prize_currency_name' => 'EUR',
                'break_down_category_eleven_name' => '1 + 2',
                'break_down_category_eleven_winners' => '157.728',
                'break_down_category_eleven_lottery_prize_amount' => '133200',
                'break_down_category_eleven_lottery_prize_currency_name' => 'EUR',
                'break_down_category_twelve_name' => '2 + 1',
                'break_down_category_twelve_winners' => '592.167',
                'break_down_category_twelve_lottery_prize_amount' => '96000',
                'break_down_category_twelve_lottery_prize_currency_name' => 'EUR',
                'break_down_category_thirteen_name' => '2 + 0',
                'break_down_category_thirteen_winners' => '1.682.415',
                'break_down_category_thirteen_lottery_prize_amount' => '34600',
                'break_down_category_thirteen_lottery_prize_currency_name' => 'EUR',
            ],
            [
                'lottery_id' => 1,
                'draw_date' => '2016-04-29',
                'result_regular_number_one' => '21',
                'result_regular_number_two' => '23',
                'result_regular_number_three' => '25',
                'result_regular_number_four' => '27',
                'result_regular_number_five' => '29',
                'result_lucky_number_one' => '1',
                'result_lucky_number_two' => '2',
                'jackpot_amount' => '1500000000',
                'jackpot_currency_name' => 'EUR',
                'break_down_category_one_name' => '5 + 2',
                'break_down_category_one_winners' => '0',
                'break_down_category_one_lottery_prize_amount' => '0',
                'break_down_category_one_lottery_prize_currency_name' => 'EUR',
                'break_down_category_two_name' => '5 + 1',
                'break_down_category_two_winners' => '6',
                'break_down_category_two_lottery_prize_amount' => '2585218100',
                'break_down_category_two_lottery_prize_currency_name' => 'EUR',
                'break_down_category_three_name' => '5 + 0',
                'break_down_category_three_winners' => '20',
                'break_down_category_three_lottery_prize_amount' => '258521800',
                'break_down_category_three_lottery_prize_currency_name' => 'EUR',
                'break_down_category_four_name' => '4 + 2',
                'break_down_category_four_winners' => '64',
                'break_down_category_four_lottery_prize_amount' => '40394000',
                'break_down_category_four_lottery_prize_currency_name' => 'EUR',
                'break_down_category_five_name' => '4 + 1',
                'break_down_category_five_winners' => '1.156',
                'break_down_category_five_lottery_prize_amount' => '1956800',
                'break_down_category_five_lottery_prize_currency_name' => 'EUR',
                'break_down_category_six_name' => '4 + 0',
                'break_down_category_six_winners' => '3.419',
                'break_down_category_six_lottery_prize_amount' => '661600',
                'break_down_category_six_lottery_prize_currency_name' => 'EUR',
                'break_down_category_seven_name' => '3 + 2',
                'break_down_category_seven_winners' => '2.042',
                'break_down_category_seven_lottery_prize_amount' => '791300',
                'break_down_category_seven_lottery_prize_currency_name' => 'EUR',
                'break_down_category_eight_name' => '2 + 2',
                'break_down_category_eight_winners' => '29.431',
                'break_down_category_eight_lottery_prize_amount' => '252500',
                'break_down_category_eight_lottery_prize_currency_name' => 'EUR',
                'break_down_category_nine_name' => '3 + 1',
                'break_down_category_nine_winners' => '43.727',
                'break_down_category_nine_lottery_prize_amount' => '162600',
                'break_down_category_nine_lottery_prize_currency_name' => 'EUR',
                'break_down_category_ten_name' => '3 + 1',
                'break_down_category_ten_winners' => '128.707',
                'break_down_category_ten_lottery_prize_amount' => '92900',
                'break_down_category_ten_lottery_prize_currency_name' => 'EUR',
                'break_down_category_eleven_name' => '1 + 2',
                'break_down_category_eleven_winners' => '157.728',
                'break_down_category_eleven_lottery_prize_amount' => '133200',
                'break_down_category_eleven_lottery_prize_currency_name' => 'EUR',
                'break_down_category_twelve_name' => '2 + 1',
                'break_down_category_twelve_winners' => '592.167',
                'break_down_category_twelve_lottery_prize_amount' => '96000',
                'break_down_category_twelve_lottery_prize_currency_name' => 'EUR',
                'break_down_category_thirteen_name' => '2 + 0',
                'break_down_category_thirteen_winners' => '1.682.415',
                'break_down_category_thirteen_lottery_prize_amount' => '34600',
                'break_down_category_thirteen_lottery_prize_currency_name' => 'EUR',
            ],
            [
                'lottery_id' => 1,
                'draw_date' => '2016-04-26',
                'result_regular_number_one' => '31',
                'result_regular_number_two' => '33',
                'result_regular_number_three' => '35',
                'result_regular_number_four' => '37',
                'result_regular_number_five' => '39',
                'result_lucky_number_one' => '1',
                'result_lucky_number_two' => '2',
                'jackpot_amount' => '1500000000',
                'jackpot_currency_name' => 'EUR',
                'break_down_category_one_name' => '5 + 2',
                'break_down_category_one_winners' => '0',
                'break_down_category_one_lottery_prize_amount' => '0',
                'break_down_category_one_lottery_prize_currency_name' => 'EUR',
                'break_down_category_two_name' => '5 + 1',
                'break_down_category_two_winners' => '6',
                'break_down_category_two_lottery_prize_amount' => '2585218100',
                'break_down_category_two_lottery_prize_currency_name' => 'EUR',
                'break_down_category_three_name' => '5 + 0',
                'break_down_category_three_winners' => '20',
                'break_down_category_three_lottery_prize_amount' => '258521800',
                'break_down_category_three_lottery_prize_currency_name' => 'EUR',
                'break_down_category_four_name' => '4 + 2',
                'break_down_category_four_winners' => '64',
                'break_down_category_four_lottery_prize_amount' => '40394000',
                'break_down_category_four_lottery_prize_currency_name' => 'EUR',
                'break_down_category_five_name' => '4 + 1',
                'break_down_category_five_winners' => '1.156',
                'break_down_category_five_lottery_prize_amount' => '1956800',
                'break_down_category_five_lottery_prize_currency_name' => 'EUR',
                'break_down_category_six_name' => '4 + 0',
                'break_down_category_six_winners' => '3.419',
                'break_down_category_six_lottery_prize_amount' => '661600',
                'break_down_category_six_lottery_prize_currency_name' => 'EUR',
                'break_down_category_seven_name' => '3 + 2',
                'break_down_category_seven_winners' => '2.042',
                'break_down_category_seven_lottery_prize_amount' => '791300',
                'break_down_category_seven_lottery_prize_currency_name' => 'EUR',
                'break_down_category_eight_name' => '2 + 2',
                'break_down_category_eight_winners' => '29.431',
                'break_down_category_eight_lottery_prize_amount' => '252500',
                'break_down_category_eight_lottery_prize_currency_name' => 'EUR',
                'break_down_category_nine_name' => '3 + 1',
                'break_down_category_nine_winners' => '43.727',
                'break_down_category_nine_lottery_prize_amount' => '162600',
                'break_down_category_nine_lottery_prize_currency_name' => 'EUR',
                'break_down_category_ten_name' => '3 + 1',
                'break_down_category_ten_winners' => '128.707',
                'break_down_category_ten_lottery_prize_amount' => '92900',
                'break_down_category_ten_lottery_prize_currency_name' => 'EUR',
                'break_down_category_eleven_name' => '1 + 2',
                'break_down_category_eleven_winners' => '157.728',
                'break_down_category_eleven_lottery_prize_amount' => '133200',
                'break_down_category_eleven_lottery_prize_currency_name' => 'EUR',
                'break_down_category_twelve_name' => '2 + 1',
                'break_down_category_twelve_winners' => '592.167',
                'break_down_category_twelve_lottery_prize_amount' => '96000',
                'break_down_category_twelve_lottery_prize_currency_name' => 'EUR',
                'break_down_category_thirteen_name' => '2 + 0',
                'break_down_category_thirteen_winners' => '1.682.415',
                'break_down_category_thirteen_lottery_prize_amount' => '34600',
                'break_down_category_thirteen_lottery_prize_currency_name' => 'EUR',
            ]




        ];
        $euroMillionsDraws = $this->table('euromillions_draws');
        $euroMillionsDraws->insert($data)
            ->save();

    }
}
