---
- name: Install Php libs
  apt: name=php5.6-cli,php5.6-dev,php5.6-xdebug,php5.6-mysql,php-apc,php5.6-zip,php5.6-redis,php5.6-intl,php5.6-curl,php5.6-xml,php5.6-mcrypt,php5.6-mbstring state=present
- name: Install libfontconfig
  apt: name=libfontconfig state=present
- name: Copy xdebug configuration
  copy: src={{ config_files_path }}{{ xdebug_config_file }} dest=/etc/php/5.6/mods-available
- name: Enable xdebug php module
  file: src=/etc/php/5.6/mods-available/{{ xdebug_config_file }} dest=/etc/php/5.6/cli/conf.d/{{ xdebug_config_file }} state=link
- name: Enable mcrypt php module
  shell: php5enmod mcrypt
- name: Clone Phalcon 2.0.10
  git: repo=https://github.com/phalcon/cphalcon.git accept_hostkey=yes dest=/tmp/phalcon version=phalcon-v2.0.10
- name: Build Phalcon
  shell: cd /tmp/phalcon/build/; ./install
- name: Phalcon module php
  shell: echo "extension=phalcon.so" > /etc/php/5.6/mods-available/30-phalcon.ini
- name: Enable phalcon module
  shell: phpenmod 30-phalcon