---
- name: Install Php libs
  apt: name=php5-cli,php5-dev,php5-xdebug,php5-mysql,php-apc,php5-redis,php5-intl,php5-curl,php5-mcrypt state=present
- name: Install libfontconfig
  apt: name=libfontconfig state=present
- name: Copy xdebug configuration
  copy: src={{ config_files_path }}{{ xdebug_config_file }} dest=/etc/php5/mods-available
- name: Enable xdebug php module
  file: src=/etc/php5/mods-available/{{ xdebug_config_file }} dest=/etc/php5/cli/conf.d/{{ xdebug_config_file }} state=link
- name: Enable mcrypt php module
  shell: php5enmod mcrypt
- name: Clone Phalcon 2.0.10
  git: repo=https://github.com/phalcon/cphalcon.git accept_hostkey=yes dest=/tmp/phalcon version=phalcon-v2.0.10
- name: Build Phalcon
  shell: cd /tmp/phalcon/build/; ./install
- name: Enable phalcon module
  shell: php5enmod phalcon
