<div class="pagename" id="translationlist">
    <div class="row">
	<div class="col-lg-12">
	    <div class="page-header">
		<h1 id="overview"><?= $this->translate('manage_translation') ?></h1>
	    </div>
	    <div class="row">
		<form class="form-inline col-md-12" role="form">
		    <div class="form-group">
			<label for="inputEmail1" class="control-label"><?= $this->translate('display_language') ?>:&nbsp;&nbsp;&nbsp;</label>
		    </div>
		    <div class="form-group">
			<select class="form-control input-sm" id="lang1" name="language1">
			    <option value="0"><?= $this->translate('display_language') ?></option>
			    <? foreach ($this->arrLang as $language) { ?>
    			    <option value="<?= $language ?>" <?= ($language == $this->language1) ? 'selected="selected"' : '' ?>><?= $this->translate('language_' . $language) ?></option>
			    <? } ?>
			</select>
		    </div>
		    <div class="form-group">
			<select  class="form-control input-sm" id="lang2" name="language2">
			    <option value="0"><?= $this->translate('display_language') ?></option>
			    <? foreach ($this->arrLang as $language) { ?>
    			    <option value="<?= $language ?>" <?= ($language == $this->language2) ? 'selected="selected"' : '' ?> ><?= $this->translate('language_' . $language) ?></option>
			    <? } ?>
			</select>
		    </div>
		    <div class="form-group">
			<select  class="form-control input-sm" id="type" name="type">
			    <option value="all" <?= ($this->type == 'all') ? 'selected="selected"' : '' ?>><?= $this->translate('all') ?></option>
			    <option value="missing" <?= ($this->type == 'missing') ? 'selected="selected"' : '' ?>><?= $this->translate('show_missing_keys') ?></option>
			</select>
		    </div>
		    <div class="form-group">
			<select  class="form-control input-sm" id="type" name="status">
			    <option value="1" <?= ($this->status == '1') ? 'selected="selected"' : '' ?>><?= $this->translate('active') ?></option>
			    <option value="0" <?= ($this->status == '0') ? 'selected="selected"' : '' ?>><?= $this->translate('inactive') ?></option>
			</select>
		    </div>
		    <div class="form-group">
			<button type="submit" class="btn btn-primary btn-sm"><i class="glyphicon glyphicon-repeat"></i></button>
		    </div>
		    <div class=" pull-right">
			<div class="form-group">
			    <input type="text" class="form-control input-sm" name="search" value="<?= $this->search ?>" placeholder="<?= $this->translate('enter_search_param') ?>" >
			</div>
			<div class="form-group">
			    <button type="submit" class="btn btn-primary btn-sm"><?= $this->translate('search') ?></button>
			</div>
		    </div>
		</form>
	    </div>
	    <br class="clearfix" />

	    <div class="table-responsive">
		<table class="table table-striped table-bordered">
		    <thead>
			<tr>
			    <th>KEY</th>
			    <? if ($this->language1 != '0') { ?>
    			    <th class="<?= $this->language1 ?> lang"><?= $this->translate('language_' . $this->language1) ?></th>
			    <? } ?>
			    <? if ($this->language2 != '0' && $this->language2 != $this->language1) { ?>
    			    <th class="<?= $this->language2 ?> lang"><?= $this->translate('language_' . $this->language2) ?></th>
			    <? } ?>
			    <th><?=$this->translate('options')?></th>
			</tr>
		    </thead>
		    <? foreach ($this->list as $item) { ?>

    		    <tr id="key<?= $item['translation_id'] ?>">
    			<td><?= $item['key'] ?></td>
			    <? if ($this->language1 != '0') { ?>
				<td class="<?= $this->language1 ?> lang">
				    <a href="#" class="editable" data-name="value_<?= $this->language1 ?>" data-pk="<?= $item['translation_id'] ?>" data-type="text"  data-url="<?= $this->url(Array('action' => 'edit', 'translation_id' => $item['translation_id'])) ?>"><?= $item[$this->language1] ?></a>
				</td>
			    <? } ?>
			    <? if ($this->language2 != '0' && $this->language2 != $this->language1) { ?>
				<td class="<?= $this->language2 ?> lang">
				    <a href="#" class="editable" data-name="value_<?= $this->language2 ?>" data-pk="<?= $item['translation_id'] ?>" data-type="text"  data-url="<?= $this->url(Array('action' => 'edit', 'translation_id' => $item['translation_id'])) ?>"><?=$item[$this->language2]; ?></a>
				</td>
			    <? } ?>
    			<td>
    			    <a href="<?= $this->url(Array('action' => 'edit', 'translation_id' => $item['translation_id'])) ?>"><i class="glyphicon glyphicon-pencil tip" title="<?= $this->translate('edit') ?>"></i></a>
					<? if(hasAccess("acp_translation_delete")){ ?>
						<a href="#" data-href="<?= $this->url(Array('action' => 'del', 'translation_id' => $item['translation_id'])) ?>" class="popup"><i class="glyphicon glyphicon-trash tip" title="<?= $this->translate('delete') ?>"></i></a>
					<? } ?>
    			</td>
    		    </tr>
		    <? } ?>
		</table>
	    </div>
	</div>
    </div>
</div>