<div class="pagename" id="forgotpassword">
	<h1><?=$this->translate('seo_headline_user_auth_forgotpassword')?></h1>
	<p><?=$this->translate('user_auth_forgotpassword_description')?></p>
	<?=$this->form;?>
</div>
<script>
	$(document).ready(function(){
		$('#forgotform').submit(function(){
			data = formCollect($(this));
			$.extend(data, {'act':'forgotpw'});
			Popup(data);
			return false;
		});
	});
</script>