<? if(!$this->popup) { ?>
	<? $this->headTitle($this->translate('seo_login_title'))?>
	<? $this->headMeta()->prependName('keywords', $this->translate('seo_login_keywords')); ?>
	<? $this->headMeta()->prependName('description', $this->translate('seo_login_description')); ?>

	<div class="pagename" id="loginact">
		<div class="container">
			<div class="box">
<? } ?>
			<h1><?=$this->translate('seo_headline_user_auth_login')?></h1>
			<? if($this->errorMessage) { ?>
				<?=$this->errorMessage?>
			<? } ?>
			<?=$this->form;?>
			<div id="forgot-password">
				<a href="#" data-href="<?=$this->url(array(),'User_ForgotPassword')?>" class="popup"><i><?=$this->translate('forgot_password')?></i></a>
			</div>
			<script>
				$(document).ready(function(){
					$('#login #loginact').val($('.pagename').attr('id'));
				});
			</script>
<? if(!$this->popup) { ?>
			</div>
	</div>
</div>
<? } ?>