<div id="loginregister">	
	<h1><?=$this->translate('seo_headline_user_auth_login_register_switch')?></h1>
	<div class="box pull-left" style="width:49%; text-align: center;">
		<strong><?=$this->translate('user_auth_login_register_switch_login_text')?></strong>
		<a class="btn eur-primary popup" data-act="login" data-href="<?=$this->url(Array(),'User_Login',true)?>"><?=$this->translate('seo_menu_user_auth_login')?></a>	
	</div>
	<div class="box pull-right" style="width:49%; text-align: center;">
		<strong><?=$this->translate('user_auth_login_register_switch_register_text')?></strong>
		<a class="btn eur-primary popup" data-act="registration" data-href="<?=$this->url(Array(),'User_Registration',true)?>"><?=$this->translate('seo_menu_user_auth_registration')?></a>	
	</div>
	<span class="clear"></span>

</div>