<? if(!$this->popup) { ?>
	<? $this->headTitle($this->translate('seo_registration_title'))?>
	<? $this->headMeta()->prependName('keywords', $this->translate('seo_registration_keywords')); ?>
	<? $this->headMeta()->prependName('description', $this->translate('seo_registration_description')); ?>
	<script type="text/javascript">
		$(document).ready(function(){
			$('#registration select').moSelect({autowidth: false,style:'standalone'});
		});
	</script>
<div class="container">
	<div class="box">
<? } ?>
		<h1><?=$this->translate('seo_headline_meta_user_auth_registration')?></h1>
		<?=$this->form;?>

<? if(!$this->popup) { ?>
	</div>
</div>
<? } else { ?>
	<script>
		$(document).ready(function(){
			$('#registration_popup').submit(function(){
				data = formCollect($(this));
				$.extend(data, {act:'registration', href: $(this).attr('action')});
				Popup(data);
				return false;
			});
			$('#registration_popup select').moSelect({autowidth: false,style:'standalone'});
		});
	</script>
<? } ?>