<? if(!$this->popup) { ?> 
<div class="pagename" id="newpassword">
	<div class="container">
		<div class="box">
<? } ?>
			<h1><?=$this->translate('seo_headline_user_auth_newpw')?></h1>
			<p><?=$this->translate('user_auth_newpw_description_2')?></p>
			<?=$this->form;?>			
<? if(!$this->popup) { ?> 
		</div>
	</div>
</div>
<? } else { ?>
	<script>
		$(document).ready(function(){
			$('#changepassword').submit(function(){
				data = formCollect($(this));
				$.extend(data, {act:'changepassword', href: $(this).attr('action')});
				Popup(data);
				return false;
			});
		});
	</script>

<? } ?>
