<? $this->headTitle($this->translate('seo_account_title')) ?>
<? if ($this->payout_success) { ?>
	<? $this->headScript()->captureStart() ?>
		settings.initOV = <?=json_encode(Array('html' => $this->Notification('notice_payout_added_successfull',true))) ?>;
	<? $this->headScript()->captureEnd() ?>
<? } ?>
<div class="pagename" id="account">
    <div class="container" id="boxbox">
		<!-- NEWS -->
		<div class="box box50 closed" id="news">
			<h4><?= $this->translate('news') ?></h4>
			<div class="inner">
				<?= $this->Teaser()->News('account', 1) ?>
			</div>
			<a class="expand toggle" data-target="news"></a>
		</div>

		<!-- LASTDRAW -->
		<div class="box box50 closed drawbox" id="lastdraw">
			<? if (!isset($draw['winner'])) { ?>
				<div class="rollover"></div>
			<? } ?>
			<? $lastResult = $this->Lottery_Euromillions()->getLastResults() ?>
			<h4><?= $this->date($lastResult['draw_date'], 'long'); ?></h4>
			<div class="inner">
			<div class="jackpot">
				<? if ($lastResult['jackpot']) { ?>
					<?=$lastResult['jackpot'];?>
				<? } ?>
			</div>
			<div class="draw">
				<i class="drawnumber icon-drawnumber-<?= $lastResult['standard_1'] ?>"></i>
				<i class="drawnumber icon-drawnumber-<?= $lastResult['standard_2'] ?>"></i>
				<i class="drawnumber icon-drawnumber-<?= $lastResult['standard_3'] ?>"></i>
				<i class="drawnumber icon-drawnumber-<?= $lastResult['standard_4'] ?>"></i>
				<i class="drawnumber icon-drawnumber-<?= $lastResult['standard_5'] ?>"></i>
				<i class="drawstar selected icon-playstar-<?= $lastResult['luckystar_1'] ?>"></i>
				<i class="drawstar selected icon-playstar-<?= $lastResult['luckystar_2'] ?>"></i>
			</div>
			<table class="table table-hover table-striped">
				<thead>
					<tr>
						<th><?= $this->translate('match') ?></th>
						<th><?= $this->translate('prize') ?></th>
						<th><?= $this->translate('winners') ?></th>
					</tr>
				</thead>
				<tbody>
					<? $results = $this->Lottery_Euromillions()->getWinner($lastResult['draw_id']); ?>
					<?
					if (!empty($results)) {
						foreach ($results as $key => $winner) {
						?>
						<tr>
							<td align="left"><?= $winner['numbers'] ?>+<?= $winner['luckystars'] ?></td>
							<td><?= $winner['prize'] ?></td>
							<td><?= $winner['winners'] ?></td>
						</tr>
						<?
						}
					} else {
						?>
						<tr>
							<td colspan="3"><?= $this->translate('no_results_aviable'); ?></td>
						</tr>
					<? } ?>
				</tbody>
			</table>
			</div>
			<a class="expand toggle" data-target="lastdraw" title="<?= $this->translate('view_prize_breakdown') ?>"></a>
		</div>

		<!-- Profile -->
		<div class="box box25 closed dyn-content" id="profile" data-href="<?= $this->url(Array(), 'User_Account_Profilesettings', true) ?>" data-popup="true">
			<a class="close toggle" data-target="profile"><i class="glyphicon glyphicon-remove"></i></a>
			<h4><?= $this->translate('personal_data') ?></h4>
			<div class="inner preview">
				<img src="<?= $this->baseUrl() ?>/templates/lotto/img/icons/profile.png">
			</div>
			<div class="inner content">
				<!-- dyn loaded content -->
			</div>
		</div>
		<!-- Active Tickets -->
		<div class="box closed  dyn-content" id="tickets" data-href="<?= $this->url(Array(), 'User_Account_Ticket_Index', true) ?>" data-popup="true">
			<a class="close toggle" data-target="tickets"><i class="glyphicon glyphicon-remove"></i></a>
			<h4><?= $this->translate('user_account_ticket_index_headline') ?></h4>
			<div class="inner preview">
				<div class="pull-left">
					<img src="<?= $this->baseUrl() ?>/templates/lotto/img/icons/mytickets.png" />
				</div>
				<div class="pull-right">
					<dl class="amount">
						<dt><?= $this->translate('active_tickets') ?></dt>
						<dd>5</dd>
						<dt><?= $this->translate('my_previous_tickets') ?></dt>
						<dd>53</dd>
					</dl>
					<span class="clear"></span>
					<span style="display:block;"><i class="icon-zoom-in"></i> <?= $this->translate('view_transactions') ?></span>
				</div>
			</div>
			<div class="inner content">
				<!-- dyn loaded content -->
			</div>
		</div>


		<!-- SYNDICATES -->
		<!--div class="box box25 closed" id="syndicates">
			<h4><?= $this->translate('syndicates') ?></h4>
			<div class="inner">
				<img src="<?= $this->baseUrl() ?>/templates/lotto/img/icons/syndicates.png">
			</div>
		</div-->


		<!--Transactions -->
		<div class="box box25 closed dyn-content" id="transactions" data-href="<?= $this->url(Array(), 'User_Account_Banking', true) ?>" data-popup="true">
			<a class="close toggle" data-target="transactions"><i class="glyphicon glyphicon-remove"></i></a>
			<h4><?= $this->translate('my_banking_headline') ?></h4>

			<div class="inner preview">
				<? if ($this->User_Userdata()->getBalance() == 0.00) { ?>
					<span class="nocredits">0</span>
					<a href="/de/billing/pay/payin<? //$this->url(Array(),'User_Login',true)    ?>" class="btn btn-primary btn-block btn-xs"><?= $this->translate('user_account_index_payin') ?></a>
				<? } else { ?>
					<span class="credits">
					<?= $this->Currency()->get($this->User_Userdata()->getBalance()); ?>
					</span>
					<span style="display:block;"><i class="icon-zoom-in"></i> <?= $this->translate('view_transactions') ?></span>
				<? } ?>
			</div>
			<div class="inner content">
				<!-- dyn loaded content -->
			</div>

		</div>

		<!--SETTINGS -->
		<div class="box closed dyn-content" id="settings" data-href="<?= $this->url(Array(), 'User_Account_Settings', true) ?>" data-popup="true">
			<a class="close toggle" data-target="settings"><i class="glyphicon glyphicon-remove"></i></a>
			<h4><?= $this->translate('settings') ?></h4>
			<div class="inner preview">
				<img src="<?= $this->baseUrl() ?>/templates/lotto/img/icons/settings.png">
			</div>
			<div class="inner content">
				<!-- dyn loaded content -->
			</div>
		</div>

		<!-- WHATS UP -->
		<div class="box box50 closed" id="whatsup">
			<h4><?= $this->translate('whatsup_headline') ?></h4>
			<div class="inner">
			<h2>“Just played on euromillions.com it’s easy, fast and secure!”</h2>
			<p>Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet.</p>
			</div>
			<a class="expand toggle" data-target="whatsup"></a>
		</div>

		<div class="box box25 closed stat-content" id="socialmedia">
			<a class="close toggle" data-target="socialmedia"><i class="glyphicon glyphicon-remove"></i></a>
			<h4 class="headline"><?= $this->translate('socialmedia') ?></h4>
			<div class="inner preview">
				<img src="<?= $this->baseUrl() ?>/templates/lotto/img/images/socials.png" style="margin: 12px 0;">
			</div>
			<div class="inner content">
				<h4 class="description"><?= $this->translate('user_account_index_socialmedia_description') ?></h4>
				<div class="socialbox">
					<div class="link">
						<a href="https://www.facebook.com/pages/Euromillionscom/204411286236724" target="_blank">
							<i class="social-big icon-facebook"></i>
						</a>
					</div>
					<div class="link">
						<a href="https://twitter.com/_lotteries" target="_blank">
							<i class="social-big icon-twitter"></i>
						</a>
					</div>
					<div class="link">
						<a href="https://plus.google.com/+Euromillionscom/posts" target="_blank">
							<i class="social-big icon-gplus"></i>
						</a>
					</div>
					<div class="link">
						<a href="http://www.reddit.com/domain/euromillions.com" target="_blank">
							<i class="social-big icon-reddit"></i>
						</a>
					</div>
					<div class="link">
						<a href="http://www.stumbleupon.com/stumbler/EuromillionsNews" target="_blank">
							<i class="social-big icon-stumbleupon"></i>
						</a>
					</div>
					<span class="clear"></span>
				</div>
			</div>
		</div>
	</div>
</div>
<script src="<?= $this->baseUrl() ?>/templates/lotto/js/masonry.pkgd.min.js"></script>