<div class="pagename" id="billingerror">
	<div class="container">
		<div class="box">
			<h1 class="error"><i class="icon-warning-sign"></i> <?=$this->translate('meta_headline_billing_error')?></h1>

			<p><?=$this->translate('billing_error_description')?></p>

			<ul>
				<li>Lorem ipsum sit dolorem lorem ipsum sit dolorem lorem lorem ipsum</li>
				<li>Lorem ipsum sit dolorem lorem ipsum sit dolorem lorem lorem ipsum</li>
				<li>Lorem ipsum sit dolorem lorem ipsum sit dolorem lorem lorem ipsum</li>
				<li>Lorem ipsum sit dolorem lorem ipsum sit dolorem lorem lorem ipsum</li>
			</ul>
			<div class="submit">
				<strong><?=$this->translate('billing_error_question')?></strong><br />
				<br />
				<a href="<?=$this->url(Array(), 'User_Account_Index',true);?>" class="btn btn-default pull-left" value="abort"><?=$this->translate('no')?></a>
				<a href="<?=$this->url(Array(),"Billing_Pay") ?>" class="btn eur-primary pull-right" value="abort"><?=$this->translate('yes')?></a>
				<span class="clear"></span>
			</div>
		</div>
	</div>
</div>