<div class="modal-header">
	<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
	<h4 class="modal-title"><?=$this->translate('please_confirm')?></h4>
</div>
<div class="modal-body">
<p><?=$this->translate('notice_delete_article_question')?></p>
<p><i class="flag flag-<?=$this->lang?>" title="<?=$this->translate('language_' . $this->lang )?>"/></i> - <?=$this->title?></p>
</div>
<div class="modal-footer">
	<a type="button" class="btn btn-default" data-dismiss="modal"><?=$this->translate('abort')?></a>
	<a type="button" href="<?=$this->url(Array("a"=>"y")) ?>" class="btn btn-primary"><?=$this->translate('yes')?></a>
</div>