<script type="text/javascript" src="<?=$this->baseUrl() ?>/templates/admin/assets/markitup/jquery.markitup.js"></script>
<script type="text/javascript" src="<?=$this->baseUrl() ?>/templates/admin/assets/markitup/sets/html/set.js"></script>

<link rel="stylesheet" type="text/css" href="<?=$this->baseUrl() ?>/templates/admin/assets/markitup/skins/markitup/style.css" />
<link rel="stylesheet" type="text/css" href="<?=$this->baseUrl() ?>/templates/admin/assets/markitup/sets/html/style.css" />
<script language="javascript">
$(document).ready(function()	{
   $('textarea.markitup').markItUp(mySettings);
});
</script>
<div class="row">
	<div class="col-lg-12">
		<div class="page-header">
			<h1 id="overview"><?=$this->translate('edit_news')?>
				<a href="<?=$this->url(Array("lang" => $this->form->lang->getValue(),"alias"=>$this->form->alias->getValue()),"News_Show") ?>" onclick="window.open(this.href); return false;"  class="pull-right btn btn-info"><i class="glyphicon glyphicon-search"></i> <?=$this->translate('frontend_preview')?></a>
			</h1>
		</div>
		<?=$this->form;?>
	</div>
</div>