<script type="text/javascript" src="<?=$this->baseUrl() ?>/templates/admin/assets/markitup/jquery.markitup.js"></script>
<script type="text/javascript" src="<?=$this->baseUrl() ?>/templates/admin/assets/markitup/sets/html/set.js"></script>

<link rel="stylesheet" type="text/css" href="<?=$this->baseUrl() ?>/templates/admin/assets/markitup/skins/markitup/style.css" />
<link rel="stylesheet" type="text/css" href="<?=$this->baseUrl() ?>/templates/admin/assets/markitup/sets/html/style.css" />
<script language="javascript">
$(document).ready(function()	{
   $('textarea.markitup').markItUp(mySettings);
   $('.languagebox legend').click(function(){
		$(this).parent().parent().toggleClass('closed');
	});
   $('.languagebox').each(function(){
	   if ($(this).find('input').val() == '' || $(this).find('textarea').val() == ''){
		   $(this).addClass('notext');
	   } else {
		   $(this).addClass('ok');
	   }
   });
});
</script>

<div class="pagename" id="faq">
	<div class="row">
		<div class="col-lg-12">
			<div class="page-header">
				<h1 id="overview"><?=$this->translate('edit_faq')?></h1>
			</div>
			<?=$this->form;?>
		</div>
	</div>
</div>