FROM panamedialottery/euromillions-base-php as base

# override default WORKDIR
WORKDIR /var/www

################################################################################

FROM base as devel

RUN pecl install xdebug-2.5.5 \
    && docker-php-ext-enable xdebug

# set php.ini
COPY php-devel/php.ini $PHP_INI_DIR/php.ini

# set fpm pool config
COPY php-devel/php-fpm.d/www.conf $PHP_INI_DIR/../php-fpm.d/www.conf