# Usage:
#
# PHALCON_BRANCH -> set the git branch for clone from phalcon repo
# PHP_VERSION -> set the php to use
#
# Example for build a image:
#
# $ docker build --build-arg PHP_VERSION=5.6.38 --build-arg PHALCON_BRANCH=phalcon-v2.0.9 -t base-php -f Dockerfile-base .
#
# This image is pushed to panamedialottery/euromillions-base-php on Docker Hub

ARG PHP_VERSION

FROM php:${PHP_VERSION}-fpm-stretch

ARG PHALCON_BRANCH

RUN buildDeps=" \
    gcc g++ libxslt1-dev libxml2-dev libmcrypt-dev libtidy-dev libfreetype6-dev \
    libjpeg62-turbo-dev libpng-dev libbz2-dev zlib1g-dev libicu-dev \
    libpcre3-dev git \
    " \
    && enableExtensions=" \
    spl_types redis apcu phalcon\
    " \
    && installExtensions=" \
    pdo_mysql mysql mysqli dba bcmath bz2 calendar \
    exif gettext gd intl mcrypt tidy \
    xsl xmlrpc pcntl shmop soap sockets \
    sysvmsg sysvsem sysvshm wddx zip opcache \
    " \
    && apt-get update && apt-get upgrade -y \
    && apt-get install -y $buildDeps --no-install-recommends \
    && docker-php-ext-install -j$(nproc) $installExtensions \
    && pecl install redis-4.1.1 \
    && pecl install apcu-4.0.11 \
    && pecl install SPL_Types \
    && git clone https://github.com/phalcon/cphalcon.git /tmp/phalcon --branch=${PHALCON_BRANCH} \
    && cd /tmp/phalcon/build/; ./install \
    && docker-php-ext-enable $enableExtensions \
    && apt-get install -y pwgen \
    && rm -rf /var/lib/apt/lists/* \
    && apt-get purge -y --auto-remove git \
    && rm -rf /tmp/*