FROM panamedialottery/euromillions-base-php as base

# override default WORKDIR
WORKDIR /var/www

################################################################################

FROM base as cron

# set php.ini
COPY cron/php.ini $PHP_INI_DIR/php.ini

COPY cron/run-cron.sh /run-cron.sh
COPY cron/euromillions.crons /etc/cron.d/euromillions.crons

RUN apt-get update && apt-get install -y cron \
    && chmod -v +x /run-cron.sh \
    && crontab /etc/cron.d/euromillions.crons \
    && rm -rf /var/lib/apt/lists/* \
    && rm -rf /tmp/*

CMD ["/run-cron.sh"]

################################################################################

FROM base as tools

# set php.ini
COPY tools/php.ini $PHP_INI_DIR/php.ini

# composer
RUN apt-get update \
    && apt-get install -y git zip unzip \
    && php -r "readfile('http://getcomposer.org/installer');" | php -- --install-dir=/usr/bin/ --filename=composer \
    && apt-get -y autoremove \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

ENV user deploybot

RUN useradd -m -d /home/${user} ${user} \
 && chown -R ${user} /home/${user}

USER ${user}

################################################################################

FROM base as devel

RUN pecl install xdebug-2.5.5 \
    && docker-php-ext-enable xdebug

# set php.ini
COPY php-devel/php.ini $PHP_INI_DIR/php.ini

# set fpm pool config
COPY php-devel/php-fpm.d/www.conf $PHP_INI_DIR/../php-fpm.d/www.conf