<div class="modal-header">
	<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
	<h4 class="modal-title"><?=$this->translate('help')?></h4>
</div>
<div class="modal-body">
	<h4><?=$this->translate('list_of_inserttags')?></h4>
	<div class="well">
			<strong><?=$this->translate('article')?></strong><br />
			{{article_url::KEY-OF-ARTICLE}} <br />
			<i style="color:#666"><?=$this->translate('example')?>: {{article_url::euromillions_rollover_system}} </i><br /> <br />

			<strong><?=$this->translate('latest_news_overview')?></strong><br />
			{{news_url::latest}} <br />
			<i style="color:#666"><?=$this->translate('result')?>: http://euromillions.com/en/newsarchive/page </i><br /> <br />

			<strong><?=$this->translate('news')?></strong><br />
			{{news_url::NEWS-ID}} <br />
			<i style="color:#666"><?=$this->translate('example')?>: {{news_url::13}} </i><br /> <br />

			<strong><?=$this->translate('latest_lottery_overview')?></strong><br />
			{{lottery_url::latest}} <br />
			<i style="color:#666"><?=$this->translate('result')?>: http://euromillions.com/en/euromillion-results </i><br /> <br />

			<strong><?=$this->translate('lottey_draw_link')?></strong><br />
			{{lottery_url::DRAW-ID}} <br />
			<i style="color:#666"><?=$this->translate('example')?>: {{lottery_url::627}}</i><br /> <br />

			<strong><?=$this->translate('images_base')?></strong><br />
			{{image_base_url}} <br />
			<i style="color:#666"><?=$this->translate('example')?>: {{image_base_url}}/euromillions_news.png </i><br /><br />

			<strong><?=$this->translate('base_url')?></strong><br />
			{{base_url}} <br />
			<i style="color:#666"><?=$this->translate('result')?>: http://www.euromillions.com </i><br /><br />

	</div>
</div>
<div class="modal-footer">
	<a type="button" class="btn btn-default" data-dismiss="modal"><?=$this->translate('close')?></a>
</div>