<div class="page-header">
	<h1><?=$this->translate('dashboard')?></h1>
</div>

<div class="row">
	<? if (hasAccess("acp_article")){ ?>
	<div class="col-lg-4 col-md-4 col-sm-6">
		<h2><i class="glyphicon glyphicon-file"></i> <?=$this->translate('article')?></h2>
		<p><?=$this->translate('article_description')?></p>
		<p>
			<a href="<?=$this->url(Array('module' => 'article','controller' => 'admin', 'action' => 'index') )?>" class="btn btn-primary"><i class="glyphicon glyphicon-align-justify"></i> <?=$this->translate('manage')?></a>
			<a href="<?=$this->url(Array('module' => 'article','controller' => 'admin', 'action' => 'add') )?>" class="btn btn-primary pull-right"><i class="glyphicon glyphicon-plus"></i> <?=$this->translate('add')?></a>
		</p>
	</div>
	<? } ?>
	<? if (hasAccess("acp_news")){ ?>
	<div class="col-lg-4 col-md-4 col-sm-6">
		<h2><i class="glyphicon glyphicon-calendar"></i> <?=$this->translate('news')?></h2>
		<p><?=$this->translate('news_description')?></p>
		<p>
			<a href="<?=$this->url(Array('module' => 'news','controller' => 'admin', 'action' => 'index') )?>" class="btn btn-primary"><i class="glyphicon glyphicon-align-justify"></i> <?=$this->translate('manage')?></a>
			<a href="<?=$this->url(Array('module' => 'news','controller' => 'admin', 'action' => 'add') )?>" class="btn btn-primary pull-right"><i class="glyphicon glyphicon-plus"></i> <?=$this->translate('add')?></a>
		</p>
	</div>
	<? } ?>
	<? if (hasAccess("acp_translation")){ ?>
	<div class="col-lg-4 col-md-4 col-sm-6">
		<h2><i class="glyphicon glyphicon-text-width"></i> <?=$this->translate('translations')?></h2>
		<p><?=$this->translate('translations_description')?></p>
		<p>
			<a href="<?=$this->url(Array('module' => 'translation','controller' => 'admin', 'action' => 'index') )?>" class="btn btn-primary"><i class="glyphicon glyphicon-align-justify"></i> <?=$this->translate('manage')?></a>
			<a href="<?=$this->url(Array('module' => 'translation','controller' => 'admin', 'action' => 'add') )?>" class="btn btn-primary pull-right"><i class="glyphicon glyphicon-plus"></i> <?=$this->translate('add')?></a>
		</p>
	</div>
	<? } ?>
	<? if (hasAccess("acp_stats")){ ?>
	<div class="col-lg-4 col-md-4 col-sm-6">
		<h2><i class="glyphicon glyphicon-signal"></i> <?=$this->translate('statistics')?></h2>
		<p><?=$this->translate('statistic_description')?></p>
		<p>
			<a href="<?=$this->url(Array('module' => 'default','controller' => 'adminstats', 'action' => 'index') )?>" class="btn btn-primary"><i class="glyphicon glyphicon-align-justify"></i> <?=$this->translate('view')?></a>
		</p>
	</div>
	<? } ?>
	<? if (hasAccess("acp_lottery")){ ?>
	<div class="col-lg-4">
		<h2><i class="glyphicon glyphicon-star-empty"></i> <?=$this->translate('lottery')?></h2>
		<p><?=$this->translate('lottery_description')?></p>
		<p><a href="<?=$this->url(Array('module' => 'lottery','controller' => 'admin', 'action' => 'index'))?>" class="btn btn-primary"><i class="glyphicon glyphicon-align-justify"></i> <?=$this->translate('manage')?></a></p>
	</div>
	<? } ?>
	<? if (hasAccess("acp_user")){ ?>
	<div class="col-lg-4">
		<h2><i class="glyphicon glyphicon-user"></i> <?=$this->translate('user')?></h2>
		<p><?=$this->translate('user_description')?></p>
		<p><a href="<?=$this->url(Array('module' => 'user','controller' => 'admin', 'action' => 'index') )?>" class="btn btn-primary"><i class="glyphicon glyphicon-align-justify"></i> <?=$this->translate('manage')?></a></p>
	</div>
	<? } ?>
</div>
<div class="page-header">
	<h1><?=$this->translate('quick_overview')?></h1>
</div>