<script type="text/javascript" src="<?=$this->baseUrl() ?>/templates/admin/assets/markitup/jquery.markitup.js"></script>
<script type="text/javascript" src="<?=$this->baseUrl() ?>/templates/admin/assets/markitup/sets/html/set.js"></script>

<link rel="stylesheet" type="text/css" href="<?=$this->baseUrl() ?>/templates/admin/assets/markitup/skins/markitup/style.css" />
<link rel="stylesheet" type="text/css" href="<?=$this->baseUrl() ?>/templates/admin/assets/markitup/sets/html/style.css" />

<script language="javascript">
$(document).ready(function()	{
   $('textarea.markitup').markItUp(mySettings);

});
</script>
<div class="row">
	<div class="col-lg-12">
		<div class="page-header">
			<h1 id="overview"><?=$this->translate('add_new_article')?></h1>
		</div>
		<?=$this->form;?>

	</div>
</div>