<div class="pagename" id="articleindex">
	<div class="row">
		<div class="col-lg-12">
			<div class="page-header">
				<h1 id="overview"><?=$this->translate('article_management')?></h1>
			</div>
			<div class="panel panel-default">
				<div class="panel-body">
					<form class="form-inline pull-left" action="" role="form">
						<div class="form-group">
							<input type="text" class="form-control" name="search" id="search" placeholder="<?=$this->translate('enter_search_param')?>">
						</div>
						<button type="submit" class="btn btn-primary"><?=$this->translate('search')?></button>
					</form>
				</div>
			</div>

			<div class="btn-group pull-right">
				<button type="button" class="btn btn-default btn-xs" onclick="$('#articlelist .panel').removeClass('closed').addClass('open');"><?=$this->translate('expand_all')?></button>
				<button type="button" class="btn btn-default btn-xs" onclick="$('#articlelist .panel').removeClass('open').addClass('closed');"><?=$this->translate('minimize_all')?></button>
			</div>
			<br class="clearfix" />

				<div id="articlelist">
				<? foreach($this->list as $key => $item) {?>

					<div id="article<?=$key?>" class="panel <?=($item['published'] == 1) ? 'open panel-success' : 'closed panel-warning';?>">
						<div class="panel-heading">
							<a class="toggle tip" onclick="$('#article<?=$key?>').toggleClass('closed').toggleClass('open');" style="cursor:pointer;" title="<?=$this->translate('open_close')?>">
								<i class="glyphicon glyphicon-minus"></i>
								<i class="glyphicon glyphicon-plus"></i>
							</a>
							<strong><?=$item['key']?></strong> <small>(<?=$this->translate('created')?>: <?=$this->Date($item['creation_date'])?> )</small>
							<? if(hasAccess('acp_article_publish')){ ?>
							<a class="popup pull-right" href="#" data-href="<?=$this->url(Array('action' => 'publish','article_id' => $item['article_id'], 'language' => '0'))?>" title="<?=$this->translate('publish_unpublish')?>"><i class="glyphicon glyphicon-eye-close"></i></a>
							<? } ?>
							<span class="languages pull-right" style="margin: 0 15px 0 0;">
								<? foreach($item['details'] as $lang => $details) { ?>
									<i class="flag flag-<?=$lang?> tip" title="<?=$this->translate('language_' . $lang )?>"/></i>
								<? } ?>
							</span>
						</div>
						<div class="panel-body" style="padding: 5px 10px 5px;">
							<table class="table">
								<?
								$newlang = Array();
								foreach($item['details'] as $lang => $details) {?>
									<tr id="article<?=$key?>_<?=$lang?>" class="<?=($details['published'] == 1) ? 'active' : 'warning';?>">
										<td><i class="flag flag-<?=$lang?>"/></i> <?=$this->translate('language_' . $lang )?></td>
										<td><?=$details['title']?> </td>
										<td>
											<a href="<?=$this->url(Array('action' => 'edit','article_id' => $item['article_id'], 'language' => $lang))?>" class="tip" title="<?=$this->translate('language_' . $lang )?> - <?=$this->translate('edit')?>"><i class="glyphicon glyphicon-pencil"></i></a>
											<a href="<?=$this->url(Array("module"=>"article","controller"=>"index","action"=>"show","lang" => $lang,"alias"=>$item['details'][$lang]['alias']),"Article_Show"); ?>" title="<?=$this->translate('frontend_preview')?>" onclick="window.open(this.href); return false;"><i class="glyphicon glyphicon-search"></i></a>
											<? if (hasAccess("acp_article_delete")){ ?>
											<a class="popup" href="#" data-href="<?=$this->url(Array('action' => 'del','article_id' => $item['article_id'], 'language' => $lang))?>"><i class="glyphicon glyphicon-trash tip" title="<?=$this->translate('language_' . $lang )?> - <?=$this->translate('delete')?>"></i></a>
											<? } ?>
											<? if (hasAccess("acp_article_publish")){ ?>
											<a class="popup pull-right" href="#" data-href="<?=$this->url(Array('action' => 'publish','article_id' => $item['article_id'], 'language' => $lang))?>"><i class="glyphicon glyphicon-eye-close tip" title="<?=$this->translate('publish_unpublish')?>"></i></a>
											<? } ?>
										</td>
									</tr>
								<? } ?>
							</table>

							<? if(count($item['missing_languages']) > 0) { ?>
								<form class="form-inline pull-right" action="<?=$this->url(Array('module' => 'article','controller' => 'admin', 'action' => 'add'))?>" role="form" method="get" id="addlang">
								<input type="hidden" name="article_id" value="<?=$item['article_id']?>" />
									<div class="form-group">
									<select name="language" class="form-control input-xs">
										<option value="0"><?=$this->translate('add_language')?></option>
										<? foreach($item['missing_languages'] as $language) { ?>
										<option value="<?=$language?>"><?=$this->translate('language_' . $language)?></option>
										<? } ?>
									</select>
									</div>
									<div class="form-group">
									<button type="submit" class="btn btn-primary btn-xs"><?=$this->translate('add')?></button>
									</div>
								</form>
							<? } ?>

						</div>
					</div>

				<? } ?>
				</div>

			</div>
		</div>
	</div>
</div>