<div class="modal-header">
	<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
	<h4 class="modal-title"><?=$this->translate('notice')?></h4>
</div>
<div class="modal-body">
<? if($this->error == true) { ?>
	<div class="alert alert-danger">
		<strong><?=$this->translate('error')?></strong> <?=$this->translate('notice_error_happens_during_operation')?>
	</div>
<? } else { ?>
<p><?=($this->published == 1) ? $this->translate('notice_published') : $this->translate('notice_not_published'); ?></p>
<script>
	<? if ($this->lang != '0'){ ?>
		$('#article<?=$this->article_id; ?>_<?=$this->lang; ?>').toggleClass('warning').toggleClass('success');
	<? } else { ?>
		$('#article<?=$this->article_id; ?>').toggleClass('panel-warning').toggleClass('panel-success');
	<? } ?>
</script>
<? } ?>
</div>
<div class="modal-footer">
	<a type="button" class="btn btn-primary" data-dismiss="modal"><?=$this->translate('ok')?></a>
</div>
