---
- name: execute crons for updating jackpots and results
  shell: >
    docker exec {{webserver_container_name}} php /var/www/apps/cli.php jackpot updatePrevious;
    docker exec {{webserver_container_name}} php /var/www/apps/cli.php result update;
    docker exec {{webserver_container_name}} php /var/www/apps/cli.php jackpot update;
    docker exec {{webserver_container_name}} crontab /var/www/global_config/crontab.txt;
    docker exec {{webserver_container_name}} php /var/www/apps/cli.php result importAllHistoricalDataFromPowerball;
    docker exec {{webserver_container_name}} php /var/www/apps/cli.php result updatePowerballResult;
    docker exec {{webserver_container_name}} php /var/www/apps/megamillions/megamillions-cli.php jackpot updateNextDrawJackpotMegaMillions;

  ignore_errors: yes

- name: Insert translation to BBDD
  shell: mysql -h 127.0.0.1 -u root -ptpl9 --port=3306 --default-character-set=utf8 euromillions < ../src/data/sql/translation_dump.sql
  ignore_errors: yes
