<?
if(!$this->popup) { ?>
	<? $this->headTitle($this->translate('seo_payout_title'))?>
<div class="pagename" id="payoutaccount">
	<div class="container">
		<div class="box">
<? } ?>
			<div id="payoutaccountconfirmform" class="inner">
				<h2><i class="icon-back-arrow"></i> <?=$this->translate('billing_payout_account_headline')?></h2><br />
				<p><strong><?=$this->translate('billing_payout_account_confirm_subheadline')?></strong></p>
				<?=$this->form ?>
			</div>
<? if(!$this->popup) { ?>
		</div>
	</div>
</div>
<? } else { ?>
	<style>
		.modal form strong {display:block; text-align:center;text-transform:uppercase;}
		.modal form label {font-weight:300;}
		.modal ul {display:none;}
	</style>
	<script>
		$(document).ready(function(){
			$('#back').click(function(){
				$('#step').val('1');
			});
			$('#back').removeClass('btn-primary').addClass('btn-default');
			$('#save').addClass('pull-right');
			$('#accountform_popup').submit(function(){
				data = formCollect($(this));
				$.extend(data, {act:'accountform', href: '<?=$this->url(Array(),'Billing_Payout_Account',true)?>'});
				Popup(data);
				return false;
			});
		});
	</script>
<? } ?>