<?
if(!$this->popup) { ?>
	<? $this->headTitle($this->translate('seo_payout_title'))?>
<div class="pagename" id="payoutaccount">
	<div class="container">
		<div class="box">
<? } ?>
			<div id="payoutaccountform" class="inner">
				<h2><i class="icon-back-arrow"></i> <?=$this->translate('billing_payout_account_headline')?></h2>
				<br />
				<p><strong><?=$this->translate('billing_payout_account_subheadline')?></strong></p>
				<p><?=$this->translate('billing_payout_account_info')?></p>
				<hr />
				<p><strong><?=$this->translate('billing_payout_account_info_2')?></strong></p>
				<?=$this->form ?>
			</div>
			<div id="ibancountry" class="inner hidden">
				<?=$this->render('/billing/payout/ibancountry.phtml')?>
			</div>
<? if(!$this->popup) { ?>
		</div>
	</div>
</div>
<? } else { ?>
	<style>
		.modal form strong {display:block; text-align:center;text-transform:uppercase;}
		.modal form label {font-weight:300;}
		#back {display:none;}
	</style>
	<script>
		$(document).ready(function(){
			$('.toggleAccount').click(function(){
				$('#payoutaccountform,#ibancountry').toggleClass('hidden');
			});
			$('#country').change(function(){
				initIBAN();
			});

			$('#iban').change(function(){
				$('#accountnumber').attr('disabled','disabled').val('');
			});
			$('#accountnumber').change(function(){
				$('#iban').attr('disabled','disabled').val('');
			});
			$('#accountform_popup').submit(function(){
				data = formCollect($(this));
				$.extend(data, {act:'accountform', href: '<?=$this->url(Array(),'Billing_Payout_Account',true)?>'});
				Popup(data);
				return false;
			});
			ibanonly = <?=$this->ibanonly?>;
			initIBAN();
		});
	</script>
<? } ?>