<?
	$minimum_amount = $this->minimum;
if(!$this->popup) { ?>
	<? $this->headTitle($this->translate('seo_payout_title'))?>

<div class="pagename" id="payout">
	<div class="container">
		<div class="box">
<? } ?>
			<div class="inner">
				<h2><i class="icon-back-arrow"></i><?=$this->translate('seo_headline_billing_payout_index')?></h2>
				<dl>
					<dt><?=$this->translate('balance')?>:</dt>
					<dd><?=$this->Currency()->get($this->userData['budget']);?></dd>
					<dt><?=$this->translate('your_winnings')?>:</dt>
					<dd><?=$this->Currency()->get($this->userData['win']);?></dd>
					<span class="clear"></span>
				</dl>
				<hr />
				<? if($this->status != 'waiting'){ ?>

					<? if($this->winnings < $this->minimum){ ?>

						<strong><?=$this->translate('billing_payout_index_no_winnings_subheadline')?>:</strong>
						<ul>
							<li><?=$this->translate('billing_payout_index_no_winnings_info_1',array($this->Currency()->get($minimum_amount)))?></li>
							<li><?=$this->translate('billing_payout_index_no_winnings_info_2')?></li>
						</ul>
						<p><?=$this->translate('billing_payout_index_no_winnings_info_3')?></p>
						<p class="buttonrow">
							<a href="<?=$this->url(Array(), 'User_Account_Index',true);?>" class="btn eur-primary"><?=$this->translate('billing_payout_index_no_winnings_button')?></a>
						</p>
					<? } else { ?>
						<form class="form-inline" action="" method="post">
							<strong>1. <?=$this->translate('billing_payout_index_amount_label') ?>:</strong>
							<br /><br />
							<div class="amount">
								<span><?=$this->Currency()->getSymbol()?></span>&nbsp;&nbsp;&nbsp;<input data-minimum="<?=$this->Currency()->get($minimum_amount,'2',false);?>" value="<?=$this->Currency()->get($minimum_amount,'2',false);?>" class="form-control" id="payoutamount" name="amount_payout"> ( <?=$this->translate('minimum_amount',array($this->Currency()->get($minimum_amount,2,false)))?>)
							</div>
							<p><?=$this->translate('billing_payout_index_amount_info')?></p>
							<span class="clear"></span>
							<br/>
							<strong>2. <?=$this->translate('billing_payout_index_account_label') ?>:</strong>
							<br/><br/>
							<? if(!empty($this->bankAccounts)){ ?>
								<? foreach($this->bankAccounts as $account){
									$accountnumber = ($account['iban'] != '' ) ? $account['iban'] : $account['account_number'];
									$censored = $accountnumber;
									if (strlen($accountnumber)>10){
										$censored =  substr($accountnumber,0,4) . str_repeat("*", (strlen($accountnumber) - 6)) . substr($accountnumber, -2);
									}

								?>
									<div class="formfield">
										<label class="radio" for="account_<?=$account['id']?>">
											<input type="radio" id="account_<?=$account['id']?>" name="account_id"  value="<?=$account['id']?>" /> <?=$account['bank_name']?> - <?=$censored;?>
											<a class="popup" data-href="/en/billing/payout/deletebankaccount/account_id/<?=$account['id']?>"><i class=" glyphicon glyphicon-trash"></i></a>
										</label>
									</div>
								<? } ?>
								<div class="formfield addaccount">
									<a class="popup" data-href="<?=$this->url(Array(),'Billing_Payout_Account',true)?>">
										<i class="icon-chkstyle icon-plus pull-left"></i> <span><?=$this->translate('billing_payout_index_add_bank_account')?></span>
									</a>
								</div>
								<br/>
								<p style="text-align:center;">
									<button type="submit" class="btn btn-primary"><?=$this->translate('billing_payout_index_submit_button')?></button>
								</p>
							<? } else { ?>
								<a class="popup btn btn-default btn-primary" data-href="<?=$this->url(Array(),'Billing_Payout_Account',true)?>"><?=$this->translate('bank_transfer')?></a>
							<? } ?>

						</form>

					<? } ?>
				<? } else { ?>
					<?=$this->Notification('notice_payout_waiting_for_approval') ?>
					<table class="table table-bordered table-striped">
						<thead>
						<tr>
							<th>ID</th>
							<th><?=$this->translate('amount')?></th>
							<th><?=$this->translate('date')?></th>
							<th><?=$this->translate('status')?></th>
						</tr>
						</thead>
						<tr>
							<td><?=$this->payout['payout_id']?></td>
							<td><?=$this->Currency()->get($this->payout['amount'])?></td>
							<td><?=$this->Date($item['add_date'])?></td>
							<td><?=($this->payout['state'] == 'new')? $this->translate('waiting') : ''?></td>
						</tr>
					</table>
				<? } ?>

			</div>
<? if(!$this->popup) { ?>
		</div>
	</div>
</div>
<? } ?>

<? $this->headStyle()->captureStart("APPEND", array("media" => "screen, projection")) ?>
	body {display:none;}
<? $this->headStyle()->captureEnd() ?>
<? $this->headStyle()->appendStyle('body {color:#ff0000;}'); ?>