<? $this->headTitle($this->translate('seo-home-title'))?>
<? $this->headMeta()->prependName('keywords', $this->translate('seo-home-keywords')); ?>
<? $this->headMeta()->prependName('description', $this->translate('seo-home-description')); ?>

<section class="slider">
	<div id="slidedeck_frame" class="skin-slidedeck">
		<dl class="slidedeck">
			<a href="http://play.euromillions.com/<?= Zend_Registry::get('lang')?>/">
				<img src="<?=$this->baseUrl() ?>/templates/default/images/teaser/mainbanner_<?= Zend_Registry::get('lang')?>.jpg" title="<?=$this->translate('buy-your-tickets')?>" alt="<?=$this->translate('play-euromillions-online')?>">
			</a>
			<h1><a href="http://play.euromillions.com/<?= Zend_Registry::get('lang')?>/"><?=$this->translate('homepage_button_text')?></a></h1>
		</dl>
	</div>
</section>

<div class="container nextJackpot">
    <img src="<?=$this->baseUrl() ?>/templates/default/images/euromillions_lottery.png">
    <h2><?=$this->translate('next-jackpot-estimated')?></h2>
	<p class="jackpotValueRed"><?=$this->Lottery_Euromillions()->getJackpot() ?></p>
    <div class="counter">
        <p class="small">
            <?=$this->translate('time-remaining')?>:
            <em id="days" class='days'>1</em>
            <?=$this->translate('days')?>
        </p>
        <div class="group">
        <div id="hourH" class="counterCell hoursH">0</div>
        <div id="hourL" class="counterCell hoursL">0</div>

        </div>
        <div class="timeseperator">
            :
        </div>
        <div class="group">
            <div id="minH" class="counterCell minutesH">0</div>
            <div id="minL" class="counterCell minutesL">0</div>
        </div>
        <div class="timeseperator">
            :
        </div>
        <div class="group">
            <div id="secH" class="counterCell secondsH">0</div>
            <div id="secL" class="counterCell secondsL">0</div>
        </div>
    </div>
    <span class="label"><?=$this->translate('hours')?></span> <span class="label"><?=$this->translate('minutes')?></span>
    <span class="label"><?=$this->translate('seconds')?></span>
    <a href="http://play.euromillions.com/<?= Zend_Registry::get('lang')?>/" class=" button orange" rel="nofollow"><?=$this->translate('buy-your-tickets')?></a>
</div>

<script type="text/javascript">
    setInterval("UpdateTimer()", 1000);

    // year, month, day, hours, minutes, seconds, milliseconds
    var startJackpots = [new Date(0, 0, 2, 19, 0, 0, 0), new Date(0, 0, 5, 19, 0, 0, 0)];
    var endJackpots = [new Date(0, 0, 2, 21, 0, 0, 0), new Date(0, 0, 5, 21, 0, 0, 0)];

    function UpdateTimer() {
        var tmpUtc = new Date();
        var check = new Date(0, 0, tmpUtc.getUTCDay(), tmpUtc.getUTCHours() + 1, tmpUtc.getUTCMinutes(), tmpUtc.getUTCSeconds(), 0);

        var timestamp = CheckTimeStamps(check);
        if (timestamp != false) {
            timestamp -= check.getTime();
            var display = TimeStampToDate(Math.floor(timestamp));

            $('#jackpot').html("€ 124.000.000");

            $('#days').html(display[0]);

            $('#hourH').html(padLeft(display[1], 2, "0").substr(0, 1));
            $('#hourL').html(padLeft(display[1], 2, "0").substr(1, 1));

            $('#minH').html(padLeft(display[2], 2, "0").substr(0, 1));
            $('#minL').html(padLeft(display[2], 2, "0").substr(1, 1));

            $('#secH').html(padLeft(display[3], 2, "0").substr(0, 1));
            $('#secL').html(padLeft(display[3], 2, "0").substr(1, 1));


        }
        else {

            $('#jackpot').html('In progress');

            $('#days').html("N/A");

            $('#hourH').html("-");
            $('#hourL').html("-");

            $('#minH').html("-");
            $('#minL').html("-");

            $('#secH').html("-");
            $('#secL').html("-");
        }
    }

    function padLeft(num, totalChars, padWith) {
        num = num + "";
        padWith = (padWith) ? padWith : "0";
        if (num.length < totalChars) {
            while (num.length < totalChars) {
                num = padWith + num;
            }
        } else { }

        if (num.length > totalChars) { //if padWith was a multiple character string and num was overpadded
            num = num.substring((num.length - totalChars), totalChars);
        } else { }

        return num;
    }


    //between 17 - 21 inprogress
    function CheckTimeStamps(current) {
        for (var i in startJackpots) {
            if (current < startJackpots[i])
                return startJackpots[i];

            if (current > startJackpots[i] && current < endJackpots[i])
                return false;
        }

        var date = new Date(0, 0, 1, 14, 0, 0, 0);
        date.setTime(startJackpots[0].getTime() + 1000 * 60 * 60 * 24 * 7);

        return date;
    }

    //
    function TimeStampToDate(timestamp) {
        return new Array(parseInt((timestamp / (24 * 60 * 60 * 1000))),
                        parseInt((timestamp / (60 * 60 * 1000)) % 24),
                        parseInt((timestamp / (60 * 1000)) % 60),
                        parseInt((timestamp / (1000)) % 60));
    }

    //
    $(document).ready(function () {
        UpdateTimer();
    });

</script>

<? $lastResult=$this->Lottery_Euromillions()->getLastResults() ?>

<? if($lastResult) { ?>

<div class="container">
	<h2><?=$this->translate('last-result-for')?> <?=$lastResult['draw_date'] ?></h2>
	<span class="greenball"> <?=$lastResult['standard_1'] ?></span>
	<span class="greenball"><?=$lastResult['standard_2'] ?></span>
	<span class="greenball"><?=$lastResult['standard_3'] ?></span>
	<span class="greenball"><?=$lastResult['standard_4'] ?></span>
	<span class="greenball"><?=$lastResult['standard_5'] ?>	</span>
	<span class="redball"><?=$lastResult['luckystar_1'] ?></span>
	<span class="redball"><?=$lastResult['luckystar_2'] ?></span>
	<p class="jackpotValueGrey"> <?=$lastResult["jackpot"] ?></p>
	<p><span class="smallFont"><a href="{{lottery_url::latest}}"><?=$this->translate('view-prize-breakdown')?></a></span></p>
	<p><strong><?=$this->translate('euromillions-results-get')?></strong> &nbsp; &nbsp; <a href="http://play.euromillions.com/<?= Zend_Registry::get('lang')?>/register/" class="button green" rel="nofollow"><?=$this->translate('register')?></a></p>
</div>
<? } ?>
<script type="text/javascript">
    $(document).ready(function () {
        $(".submitMobile").click(function () {
            $.getJSON("/BackOffice/RegisterCustomerMobile", { countryCode: $("#Countries").val(), mobile: $("#mobile").val() }, function (data) {
                if (data.status == "success") {
                    $("#mobile").val('');
                    jQuery.facebox(data.message);
                }
            });
        });
    });
</script>

	<div class="smallBanner2">
		<a href="https://twitter.com/_lotteries" target="_blank"><img src="<?=$this->baseUrl() ?>/templates/default/images/teaser/follow-us_<?= Zend_Registry::get('lang')?>.jpg" border="0" alt="Follow Euromillions on Twitter"></a>
	</div>

	<div class="smallBanner buyTickets">
		<div><a href="{{article_url::how_to_play_euromillions_online}}" onClick="_gaq.push(['_trackEvent', 'Banners', 'en', 'playeurojackpot-460x200']);" rel="nofollow"><img src="<?=$this->baseUrl() ?>/templates/default/images/teaser/banner-play-online_<?= Zend_Registry::get('lang')?>.jpg" alt="how to play Euromillions online" /></a></div>
	</div>


<?=$this->Teaser()->News('content',3) ?>

	<div class="smallArticleContainer">
		<p><a href="{{article_url::discover_your_odds_of_winning_the_euromillions}}" title="<?=$this->translate('main-page-story-1-title')?>"><?=$this->translate('main-page-story-1-title')?></a></p>
		<p><?=$this->translate('main-page-story-1-content')?></p>
	</div>
	<div class="smallArticleContainer">
		<p><a href="{{article_url::euromillions_rules}}" title="<?=$this->translate('main-page-story-2-title')?>"><?=$this->translate('main-page-story-2-title')?></a></p>
		<p><?=$this->translate('main-page-story-2-content')?></p>
	</div>
	<div class="smallArticleContainer">
		<p><a href="{{article_url::euromillions_history}}" title="<?=$this->translate('main-page-story-3-title')?>"><?=$this->translate('main-page-story-3-title')?></a></p>
		<p><?=$this->translate('main-page-story-3-content')?></p>
	</div>
	<div class="smallArticleContainer">
	   <p><a href="{{article_url::euromillions_prize_structure}}" title="<?=$this->translate('main-page-story-4-title')?>"><?=$this->translate('main-page-story-4-title')?></a></p>
		<p><?=$this->translate('main-page-story-4-content')?></p>
	</div>
