<? $this->headTitle($this->translate('seo_results_title'))?>
<? $this->headMeta()->prependName('keywords', $this->translate('seo_results_keywords')); ?>
<? $this->headMeta()->prependName('description', $this->translate('seo_results_description')); ?>

<div class="pagename" id="showresults">

	<div class="container">
		<h1><?=$this->translate('euromillions_draw')?> <?=$this->draw_id?></h1>


	<div class="box">
		<? $result=$this->Lottery_Euromillions()->getResult($this->draw_id) ?>
		<h4><?=$this->translate('results_for_date')?> <?=$this->Date($result['draw_date'])?></h4>
		<div class="pull-left">
			<strong><?=$this->translate('jackpot_size')?></strong>
			<? if($result['jackpot']){ echo $result['jackpot']; } ?>
		</div>
		<div class="pull-right">
			<strong><?=$this->translate('winning_euromillions_numbers')?></strong>
			<div class="draw">
				<i class="drawnumber icon-drawnumber-<?=$result['standard_1']?>"></i>
				<i class="drawnumber icon-drawnumber-<?=$result['standard_2']?>"></i>
				<i class="drawnumber icon-drawnumber-<?=$result['standard_3']?>"></i>
				<i class="drawnumber icon-drawnumber-<?=$result['standard_4']?>"></i>
				<i class="drawnumber icon-drawnumber-<?=$result['standard_5']?>"></i>
				<i class="drawstar selected icon-playstar-<?=$result['luckystar_1']?>"></i>
				<i class="drawstar selected icon-playstar-<?=$result['luckystar_2']?>"></i>
			</div>
		</div>
		<span class="clear"></span>
	</div>
		<br  />

		<div id="breakDown"  style="width:100%;">
			<div id="priceandwinners">
				<table class="table table-striped table-bordered">
					<thead>
						<tr class="tableHead">
							<th><?=$this->translate('match')?></th>
							<th><?=$this->translate('prize')?></th>
							<th><?=$this->translate('winners')?></th>
						</tr>
					</thead>
					<tbody>
						<? $winners = $this->Lottery_Euromillions()->getWinner($this->draw_id); ?>
						<? if (!empty($winners)){ ?>
							<? foreach($winners as $key =>  $winner){  ?>
									<tr>
										<td align="left"><?=$winner['numbers'] ?>+<?=$winner['luckystars'] ?></td>
										<td><?=$winner['prize']?></td>
										<td><?=$winner['winners']?></td>
									</tr>
							 <? } ?>
						<? } else { ?>
						<tr>
							<td colspan="4"><?=$this->translate('no_results_aviable');?></td>
						</tr><? } ?>
					</tbody>
				</table>
			</div>
		</div>
	</div>

</div>