FROM antonienko/nginx-php-fpm:v0.5
MAINTAINER Antonio Hernández "antonio.hernandez@panamedia.net"

RUN echo "INSTALLING LOCALES"

RUN locale-gen es_ES.UTF-8
RUN locale-gen en_US.UTF-8
RUN locale-gen en_GB.UTF-8

