<?php
namespace tests\integration\shared;

use EuroMillions\shared\services\SiteConfigService;
use EuroMillions\web\entities\SiteConfig;
use Money\Currency;
use Money\Money;
use tests\base\DatabaseIntegrationTestBase;

class SiteConfigServiceSpy extends SiteConfigService
{
    public function getConfigEntity()
    {
        return $this->configEntity;
    }
}

class SiteConfigServiceIntegrationTest extends DatabaseIntegrationTestBase
{

    protected $currencyConversionService_dobule;

    /**
     * Child classes must implement this method. Return empty array if no fixtures are needed
     * @return array
     */
    protected function getFixtures()
    {
        return ['site_config'];
    }

    public function setUp()
    {
        $this->currencyConversionService_dobule = $this->getServiceDouble('CurrencyConversionService');
        parent::setUp(); // TODO: Change the autogenerated stub
    }

    /**
     * method __construct
     * when called
     * should createProperEntity
     */
    public function test___construct_called_createProperEntity()
    {
        $expected = new SiteConfig();
        $expected->initialize([
            'id' => 1,
            'fee' => new Money(35 ,new Currency('EUR')),
            'fee_to_limit' => new Money(12000, new Currency('EUR')),
            'default_currency' => new Currency('EUR')
        ]);

        $sut = $this->getSut();
        $this->assertEquals($expected, $sut->getConfigEntity());
    }

    /**
     * method getFee
     * when called
     * should returnProperValue
     */
    public function test_getFee_called_returnProperValue()
    {
        $sut = $this->getSut();
        $actual = $sut->getFee();
        $expected = new Money(35, new Currency('EUR'));
        $this->assertEquals($expected, $actual);
    }

    /**
     * method getFormatFeeMoney
     * when called
     * should returnProperValueWithFormatCurrency
     */
    public function test_getFormatFeeMoney_called_returnProperValueWithFormatCurrency()
    {
        $expected = '$0.15';
        $amount = new Money(35, new Currency('EUR'));
        $converted_value = new Money(15, new Currency('EUR'));
        list($user_currency, $locale) = $this->exerciseFormatMoney($amount,$converted_value);
        $sut = $this->getSut();
        $actual = $sut->getFeeFormatMoney($user_currency,$locale);
        $this->assertEquals($expected,$actual);
    }

    /**
     * method getFeeLimitFormatMoney
     * when called
     * should returnProperValueWithFormatCurrency
     */
    public function test_getFeeLimitFormatMoney_called_returnProperValueWithFormatCurrency()
    {
        $expected = '$80';
        $amount = new Money(12000, new Currency('EUR'));
        $converted_value = new Money(8000, new Currency('EUR'));
        list($user_currency, $locale) = $this->exerciseFormatMoney($amount,$converted_value);
        $sut = $this->getSut();
        $actual = $sut->getFeeLimitFormatMoney($user_currency,$locale);
        $this->assertEquals($expected,$actual);
    }

    /**
     * @return array
     */
    private function exerciseFormatMoney(Money $amount, Money $value_converted)
    {
        $user_currency = new \Money\Currency('USD');
        $locale = 'en_US';
        $this->currencyConversionService_dobule->convert($amount, $user_currency)->willReturn($value_converted);
        $this->currencyConversionService_dobule->toString($value_converted, $locale)->willReturn('$'.$value_converted->getAmount()/100);
        return array($user_currency, $locale);
    }

    /**
     * @return SiteConfigService
     */
    private function getSut()
    {
        $sut = new SiteConfigServiceSpy($this->entityManager, $this->currencyConversionService_dobule->reveal());
        return $sut;
    }

}