<? $this->headTitle($this->article['page_title'])?>
<? $this->headMeta()->prependName('keywords', $this->article['meta_keywords']); ?>
<? $this->headMeta()->prependName('description', $this->article['meta_description']); ?>
<div class="pagename" id="article">
	<div class="container">
		<h1><?=$this->article['title']?></h1>
		<div class="meta">
			<i class="glyphicon glyphicon-calendar"></i> <?=$this->translate('Published')?>: <time pubdate="<?=$this->Date($this->article['published_on'])?>"><?=$this->Date($this->article['published_on'])?></time>
			1<?=$this->article['published_by']?>2
			<? if($this->article['published_by_name'] != ''){ ?> &nbsp;&nbsp;&nbsp;&nbsp;<i class="glyphicon glyphicon-user"></i> <?=$this->article['published_by_name']?><? } ?>
		</div>

		<!-- AddThis Button BEGIN -->
		<?=$this->SocialWidgets()->addThis(); ?>

		<? if($this->article['image'] != '' || $this->article['header'] != '') { ?>
		<div id="preamble">
			<? if($this->article['image'] != '') { ?>
				<img src="<?=$this->article['image']?>" alt="<?=$this->article['page_title']?>" style="float:left;margin: 0 10px 10px 0;max-width: 25%;"/>
			<? } else { ?>
					<img src="<?=$this->baseUrl() ?>/templates/default/images/euromillions_news.png" alt="<?=$this->article['page_title']?>" align="left" height="196" width="196" />
			<? } ?>
			<? if($this->article['header'] != '') { ?>
				<h2><?=$this->article['header']?></h2>
			<? } ?>
		</div>
		<? } ?>

		<div id="mainContent" class="ColF">
			<?=$this->article['content']?>
		</div>

	</div>
</div>