<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="utf-8">
		<title>Euromillions.com</title>
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		<meta name="description" content="">
		<meta name="author" content="">

		<!-- Le styles -->
		<link href="<?=$this->baseUrl() ?>/assets/bootstrap/css/bootstrap.css" rel="stylesheet">
		<link href="<?=$this->baseUrl() ?>/fonts/ostrich-sans/ostrich-sans.css" rel="stylesheet">
		<link href="<?=$this->baseUrl() ?>/css/style.css" rel="stylesheet">

  </head>

  <body>
  
	<!-- Fixed navbar -->
	<div role="navigation" class="navbar navbar-default navbar-fixed-top">
		<div class="container">
			<div class="navbar-header">
				<button data-target=".navbar-collapse" data-toggle="collapse" class="navbar-toggle" type="button">
				<span class="sr-only">Toggle navigation</span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				</button>
				<a href="home.html" class="navbar-brand">Euromillions.com</a>
			</div>
			<div class="navbar-collapse collapse  navbar-right">
				<p class="navbar-text">
					Hello, Username! <a href="account.html" class="btn eur-secondary btn-xs">Account</a>
					EN €
				</p>
			</div>
			<div class="navbar-collapse collapse">
				<ul class="nav nav-justified">
					<li class="active"><a href="play.html">Play</a></li>
					<li><a href="results.html">Results</a></li>
					<li><a href="#information">Information</a></li>
					<li><a href="#about">About</a></li>
				</ul>
			</div><!--/.nav-collapse -->

		</div>
		<div id="slideOut">
			<div class="container">
				<div class="pull-left">
					<p>Days &nbsp;&nbsp;&nbsp;&nbsp;Hours &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Minutes </p>
					<img src="img/timerdummy.png">
				</div>
				<div class="pull-right">
					<p>Don´t miss your chance to win</p>
					<a href="play.html" class="btn eur-primary">
						Play now!
					</a>
				</div>
				<div class="jackpot">
					<p>Next Euromillions Jackpot</p>
					<strong>157.500.000 €</strong>
				</div>
			</div>
		</div>
	</div>



	<div class="pagename" id="play">
		<div class="container">
			<form action="" method="post">
				<div class="box">
					<div class="inner">
							<div class="formfield" style="min-width:38px;">
								<img src="img/icons/date.png" /> Days
							</div>
							<div class="formfield">
								<label tabindex="3" class="checkbox" for="tuesday">
									<input type="checkbox" id="tuesday" value="1" name="tuesday"> Tuesday
								</label>
							</div>
							<div class="formfield">
								<label tabindex="3" class="checkbox" for="friday">
									<input type="checkbox" id="friday" value="1" name="friday"> Friday
								</label>
							</div>
							<div class="formfield">
								<select name="draws" class="form-control input-xs" >
									<option value="1">1 Draw</option>
									<option value="2">2 Draws</option>
									<option value="3">5 Draws</option>
									<option value="4">10 Draws</option>
									<option value="5">20 Draws</option>
								</select>
							</div>
							<div class="formfield pull-right">
								<label tabindex="3" class="checkbox" for="recurring">
									<input type="checkbox" id="recurring" value="1" name="recurring"> Recurring Ticket
								</label>
							</div>
							<hr class="clear" />
							<div class="formfield">
								<a onclick="addLines();">
									<i class="icon-chkstyle add"></i> Add additional Lines
								</a> 
							</div>
							<div class="formfield">
								<label tabindex="3" class="checkbox" for="multible">
									<input type="checkbox" id="multible" value="1" name="multible"> Play multiple ticket(s)
								</label>
							</div>
							<div class="formfield">
								<a id="clearAll">
									<i class="icon-chkstyle remove"></i> clear all
								</a>
							</div>
							<div class="formfield">
								<a id="randomizeAll">
									<i class="icon-chkstyle random"></i> randomize all
								</a>
							</div>
					</div>
				</div>
				<div class="addcartbox">
					<div class="price">Total Price: <span class="amount color">0,00 €</span></div>
					<!--
					<a href="" class="btn eur-primary" id="addcard" onclick="document.form.submit('asd');">Buy Now</a>
					-->
					<input type="submit" value="Kaufen" class="btn eur-primary" id="addcard" />
				</div>
				<div class="box linebox">
					<div class="inner">
					   <div class="line">
							<input type="hidden" class="num" name="numbers[1]" value="" />
							<input type="hidden" class="sta"  name="stars[1]" value="" />
							<div class="headline pull-left color">Line 1</div>
							<div class="pull-right">
								<a onclick="resetLine($(this));">
									<i class="icon-chkstyle remove"></i>
								</a>
								<a onclick="randomLine($(this));">
									<i class="icon-chkstyle random"></i>
								</a>
							</div>
							<div class="numbers">
								<div class="playnumber">1</div>
								<div class="playnumber">2</div>
								<div class="playnumber">3</div>
								<div class="playnumber">4</div>
								<div class="playnumber">5</div>
								<div class="playnumber">6</div>
								<div class="playnumber">7</div>
								<div class="playnumber">8</div>
								<div class="playnumber">9</div>
								<div class="playnumber">10</div>

								<div class="playnumber">11</div>
								<div class="playnumber">12</div>
								<div class="playnumber">13</div>
								<div class="playnumber">14</div>
								<div class="playnumber">15</div>
								<div class="playnumber">16</div>
								<div class="playnumber">17</div>
								<div class="playnumber">18</div>
								<div class="playnumber">19</div>
								<div class="playnumber">20</div>

								<div class="playnumber">21</div>
								<div class="playnumber">22</div>
								<div class="playnumber">23</div>
								<div class="playnumber">24</div>
								<div class="playnumber">25</div>
								<div class="playnumber">26</div>
								<div class="playnumber">27</div>
								<div class="playnumber">28</div>
								<div class="playnumber">29</div>
								<div class="playnumber">30</div>

								<div class="playnumber">31</div>
								<div class="playnumber">32</div>
								<div class="playnumber">33</div>
								<div class="playnumber">34</div>
								<br class="clear">
								<div class="playnumber">35</div>
								<div class="playnumber">36</div>
								<div class="playnumber">37</div>
								<div class="playnumber">38</div>
								<br class="clear">
								<div class="playnumber">39</div>
								<div class="playnumber">40</div>
								<div class="playnumber">41</div>
								<div class="playnumber">42</div>
								<br class="clear">
								<div class="playnumber">43</div>
								<div class="playnumber">44</div>
								<div class="playnumber">45</div>
								<div class="playnumber">46</div>
								<br class="clear">
								<div class="playnumber">47</div>
								<div class="playnumber">48</div>
								<div class="playnumber">49</div>
								<div class="playnumber">50</div>
							</div>
							<div class="stars">
								<div class="playstar">1</div>
								<div class="playstar">2</div>
								<div class="playstar">3</div>
								<div class="playstar">4</div>
								<div class="playstar">5</div>
								<div class="playstar">6</div>
								<div class="playstar">7</div>
								<div class="playstar">8</div>
								<div class="playstar">9</div>
								<div class="playstar">10</div>
								<div class="playstar">11</div>
							</div>
						</div>
						<div class="line">
							<input type="hidden" class="num" name="numbers[2]" value="" />
							<input type="hidden" class="sta"  name="stars[2]" value="" />
							<div class="headline pull-left color">Line 2</div>
							<div class="pull-right">
								<a onclick="resetLine($(this));">
									<i class="icon-chkstyle remove"></i>
								</a>
								<a onclick="randomLine($(this));">
									<i class="icon-chkstyle random"></i>
								</a>
							</div>
							<div class="numbers">
								<div class="playnumber">1</div>
								<div class="playnumber">2</div>
								<div class="playnumber">3</div>
								<div class="playnumber">4</div>
								<div class="playnumber">5</div>
								<div class="playnumber">6</div>
								<div class="playnumber">7</div>
								<div class="playnumber">8</div>
								<div class="playnumber">9</div>
								<div class="playnumber">10</div>

								<div class="playnumber">11</div>
								<div class="playnumber">12</div>
								<div class="playnumber">13</div>
								<div class="playnumber">14</div>
								<div class="playnumber">15</div>
								<div class="playnumber">16</div>
								<div class="playnumber">17</div>
								<div class="playnumber">18</div>
								<div class="playnumber">19</div>
								<div class="playnumber">20</div>

								<div class="playnumber">21</div>
								<div class="playnumber">22</div>
								<div class="playnumber">23</div>
								<div class="playnumber">24</div>
								<div class="playnumber">25</div>
								<div class="playnumber">26</div>
								<div class="playnumber">27</div>
								<div class="playnumber">28</div>
								<div class="playnumber">29</div>
								<div class="playnumber">30</div>

								<div class="playnumber">31</div>
								<div class="playnumber">32</div>
								<div class="playnumber">33</div>
								<div class="playnumber">34</div>
								<br class="clear">
								<div class="playnumber">35</div>
								<div class="playnumber">36</div>
								<div class="playnumber">37</div>
								<div class="playnumber">38</div>
								<br class="clear">
								<div class="playnumber">39</div>
								<div class="playnumber">40</div>
								<div class="playnumber">41</div>
								<div class="playnumber">42</div>
								<br class="clear">
								<div class="playnumber">43</div>
								<div class="playnumber">44</div>
								<div class="playnumber">45</div>
								<div class="playnumber">46</div>
								<br class="clear">
								<div class="playnumber">47</div>
								<div class="playnumber">48</div>
								<div class="playnumber">49</div>
								<div class="playnumber">50</div>
							</div>
							<div class="stars">
								<div class="playstar">1</div>
								<div class="playstar">2</div>
								<div class="playstar">3</div>
								<div class="playstar">4</div>
								<div class="playstar">5</div>
								<div class="playstar">6</div>
								<div class="playstar">7</div>
								<div class="playstar">8</div>
								<div class="playstar">9</div>
								<div class="playstar">10</div>
								<div class="playstar">11</div>
							</div>
						</div>
						<div class="line">
							<input type="hidden" class="num" name="numbers[2]" value="" />
							<input type="hidden" class="sta"  name="stars[2]" value="" />
							<div class="headline pull-left color">Line 3</div>
							<div class="pull-right">
								<a onclick="resetLine($(this));">
									<i class="icon-chkstyle remove"></i>
								</a>
								<a onclick="randomLine($(this));">
									<i class="icon-chkstyle random"></i>
								</a>
							</div>
							<div class="numbers">
								<div class="playnumber">1</div>
								<div class="playnumber">2</div>
								<div class="playnumber">3</div>
								<div class="playnumber">4</div>
								<div class="playnumber">5</div>
								<div class="playnumber">6</div>
								<div class="playnumber">7</div>
								<div class="playnumber">8</div>
								<div class="playnumber">9</div>
								<div class="playnumber">10</div>

								<div class="playnumber">11</div>
								<div class="playnumber">12</div>
								<div class="playnumber">13</div>
								<div class="playnumber">14</div>
								<div class="playnumber">15</div>
								<div class="playnumber">16</div>
								<div class="playnumber">17</div>
								<div class="playnumber">18</div>
								<div class="playnumber">19</div>
								<div class="playnumber">20</div>

								<div class="playnumber">21</div>
								<div class="playnumber">22</div>
								<div class="playnumber">23</div>
								<div class="playnumber">24</div>
								<div class="playnumber">25</div>
								<div class="playnumber">26</div>
								<div class="playnumber">27</div>
								<div class="playnumber">28</div>
								<div class="playnumber">29</div>
								<div class="playnumber">30</div>

								<div class="playnumber">31</div>
								<div class="playnumber">32</div>
								<div class="playnumber">33</div>
								<div class="playnumber">34</div>
								<br class="clear">
								<div class="playnumber">35</div>
								<div class="playnumber">36</div>
								<div class="playnumber">37</div>
								<div class="playnumber">38</div>
								<br class="clear">
								<div class="playnumber">39</div>
								<div class="playnumber">40</div>
								<div class="playnumber">41</div>
								<div class="playnumber">42</div>
								<br class="clear">
								<div class="playnumber">43</div>
								<div class="playnumber">44</div>
								<div class="playnumber">45</div>
								<div class="playnumber">46</div>
								<br class="clear">
								<div class="playnumber">47</div>
								<div class="playnumber">48</div>
								<div class="playnumber">49</div>
								<div class="playnumber">50</div>

							</div>
							<div class="stars">
								<div class="playstar">1</div>
								<div class="playstar">2</div>
								<div class="playstar">3</div>
								<div class="playstar">4</div>
								<div class="playstar">5</div>
								<div class="playstar">6</div>
								<div class="playstar">7</div>
								<div class="playstar">8</div>
								<div class="playstar">9</div>
								<div class="playstar">10</div>
								<div class="playstar">11</div>
							</div>
						</div>
					</div>
				</div>
			</form>
			
		</div>		

 	</div>
	

	<script src="<?=$this->baseUrl() ?>/assets/bootstrap/js/jquery.js"></script>
	<script src="<?=$this->baseUrl() ?>/assets/bootstrap/js/bootstrap.js"></script>
	<script src="<?=$this->baseUrl() ?>/js/common.js"></script>
<br /><br />
	<a href="<?=$this->url(Array(),"Billing_Cart") ?>">Bezahlen</a>	
</body>
</html>
