<div class="row">
	<div class="col-lg-12">
			<h1 id="overview"><?=$this->translate('details_for_user')?>: <span class="color"><?=$this->userData['username']?></span></h1>
	</div>
</div>
<?=$this->partial('user/admin/navigation.phtml', array('active' => 'details', 'user_id' => $this->userData['user_id'])); ?>
<div class="row">
	<div class="col-md-8 col-lg-8 col-sm-12">
		<div class="panel panel-default">
			<div class="panel-heading">Details</div>
			<div class="panel-body">
				<div class="row">
					<div class="col-md-5 col-lg-6 col-sm-6">
						<table class="table table-striped">
							<tbody>
								<tr>
									<th><?=$this->translate('firstname')?></th>
									<td><?=$this->userData['first_name']?></td>
								</tr>
								<tr>
									<th><?=$this->translate('lastname')?></th>
									<td><?=$this->userData['last_name']?></td>
								</tr>
								<tr>
									<th><?=$this->translate('city')?> / <?=$this->translate('zip')?></th>
									<td><?=$this->userData['city']?> / <?=$this->userData['zip']?></td>
								</tr>
								<tr>
									<th><?=$this->translate('street')?></th>
									<td><?=$this->userData['street']?></td>
								</tr>
								<tr>
									<th><?=$this->translate('birthdate')?></th>
									<td><?=$this->Date($this->userData['birth_date'] . ' 00:00:00','medium')?></td>
								</tr>
								<tr>
									<th><?=$this->translate('currency')?></th>
									<td><?=$this->userData['currency']?></td>
								</tr>
							</tbody>
						</table>
					</div>
					<div class="col-md-6 col-lg-6 col-sm-6">
						<table class="table table-striped">
							<tbody>
								<tr>
									<th>User ID</th>
									<td><?=$this->userData['user_id']?></td>
								</tr>
								<tr>
									<th>Role</th>
									<td><?=$this->userData['role']?></td>
								</tr>
								<tr>
									<th>Customer</th>
									<td><?=$this->userData['customer_id']?></td>
								</tr>
								<tr>
									<th><?=$this->translate('country')?></th>
									<td><?=$this->countries[$this->userData['country']] ?></td>
								</tr>
								<tr>
									<th><?=$this->translate('language')?></th>
									<td><?=$this->translate('language_' .$this->userData['lang'])?></td>
								</tr>
								<tr>
									<th>Usercode</th>
									<td><input type="text" class="form-control input-sm" value="<?=$this->userData['user_code']?>" ></td>
								</tr>
							</tbody>
						</table>
					</div>
				</div>
			</div>
		</div>
	</div>
	<div class="col-md-4 col-lg-4 col-sm-6">
		<div class="panel panel-default">
			<div class="panel-heading">Account</div>
			<table class="table table-striped">
				<tbody>
					<tr>
						<th>Budget</th>
						<td><?=$this->Currency()->get($this->userData['budget']);?></td>
					</tr>
					<tr class="danger">
						<th>Deposits</th>
						<td><?=$this->Currency()->get('0');?></td>
					</tr>
					<tr class="danger">
						<th>Payouts</th>
						<td><?=$this->Currency()->get('0');?></td>
					</tr>

					<tr class="danger">
						<th>Amount Spent</th>
						<td><?=$this->Currency()->get('0');?></td>
					</tr>
					<tr class="danger">
						<th>Amount Won</th>
						<td><?=$this->Currency()->get('0');?></td>
					</tr>

				</tbody>
			</table>
		</div>
	</div>
	<div class="col-md-4 col-lg-4 col-sm-6">
		<div class="panel panel-default">
			<div class="panel-heading">Activity</div>
			<table class="table table-striped">
				<tbody>
					<tr>
						<th>Userstatus</th>
						<td><?=$this->userData['active']?></td>
					</tr>
					<tr class="danger">
						<th>Player Rank</th>
						<td> xxx / 0000</td>
					</tr>
					<tr>
						<th>Registration Date</th>
						<td><?=$this->Date($this->userData['last_login'],'time')?></td>
					</tr>
					<tr>
						<th>Last Login</th>
						<td><?=$this->Date($this->userData['last_login'],'time')?></td>
					</tr>
					<tr>
						<th>Last Action</th>
						<td><?=$this->Date($this->userData['last_action'],'time')?></td>
					</tr>
					<tr>
						<th>Last IP</th>
						<td><?=$this->userData['last_ip']?></td>
					</tr>
				</tbody>
			</table>
		</div>
	</div>
</div>
<pre>
<? print_r($this->userData);?>
</pre>