<div class="row">
	<div class="col-lg-12">
		<h1 id="overview"><?=$this->translate('details_for_user')?>: <span class="color"><?=$this->userData['username']?></span></h1>
	</div>
</div>
<?=$this->partial('user/admin/navigation.phtml', array('active' => 'edit', 'user_id' => $this->userData['user_id'])); ?>
<div class="row">
	<div class="col-lg-12">
		<?=$this->form;?>
	</div>
</div>
<pre>
	<? print_r($this->userData);?>
</pre>