<div class="row">
	<div class="col-lg-12">
		<div class="page-header">
			<h1 id="overview"><?=$this->translate('user_management')?></h1>
		</div>
		<div class="panel panel-default">
			<div class="panel-heading"><?=$this->translate('search')?></div>
			<div class="panel-body">
				<form class="col-md-12" method="post" role="form" action="<?=$this->url(Array('module' => 'user','controller' => 'admin', 'action' => 'index'),null,true )?>">
					<fieldset>
						<div class="form-group">
							<input class=" form-control" type="text" name="quick_user" value="<?=($this->searchParams['quick_user'])?>" placeholder="<?=$this->translate('email')?> / <?=$this->translate('firstname')?> / <?=$this->translate('lastname')?>" />
						</div>
						<div class="form-group">
							<input class=" form-control" type="text" name="quick_id" value="<?=$this->searchParams['quick_id']?>" placeholder="<?=$this->translate('ticket_id')?> / <?=$this->translate('ticket_id')?>" />
						</div>
					</fieldset>
					<fieldset class="hidden">
						<div class="form-group">
							<label><?=$this->translate('email')?></label>
							<input class="form-control input-sm" value="<?=$this->searchParams['username'] ?>" type="text" name="username">
						</div>
						<div class="form-group">
							<label><?=$this->translate('ticket_id')?></label>
							<input class="form-control input-sm" value="<?=$this->searchParams['ticket_id'] ?>" type="text" name="ticket_id">
						</div>
						<div class="form-group">
							<label><?=$this->translate('transaction_id')?></label>
							<input class="form-control input-sm" value="<?=$this->searchParams['transaction_id'] ?>"  type="text" name="transaction_id">
						</div>
						<div class="form-group">
							<label><?=$this->translate('firstname')?></label>
							<input class="form-control input-sm" value="<?=$this->searchParams['firstname'] ?>"  type="text" name="firstname">
						</div>
						<div class="form-group">
							<label><?=$this->translate('lastname')?></label>
							<input class="form-control input-sm" value="<?=$this->searchParams['lastname'] ?>" type="text" name="lastname">
						</div>
						<div class="form-group">
							<label><?=$this->translate('country')?></label>
							<?=$this->Selectmenu('country',$this->arrCountries,$this->searchParams['country'],'form-control',$this->translate('please_select'));?>
						</div>
						<div class="form-group">
							<label><?=$this->translate('language')?></label>
							<?=$this->Selectmenu('language',$this->arrLanguages,$this->searchParams['language'],'form-control',$this->translate('please_select'));?>
						</div>
						<div class="form-group">
							<label><?=$this->translate('role')?></label>
							<select class="form-control input-sm" id="type" name="role">
								<option value="-1"> ------</option>
								<option value="user" <?= ($this->searchParams['role'] == 'user') ? 'selected="selected"' : '' ?>>user</option>
								<option value="admin" <?= ($this->searchParams['role'] == 'admin') ? 'selected="selected"' : '' ?>>admin</option>
								<option value="superadmin" <?= ($this->searchParams['role'] == 'superadmin') ? 'selected="selected"' : '' ?>>superadmin</option>
							</select>
						</div>
					</fieldset>
					<a href="#" onclick="$(this).parent().find('fieldset').toggleClass('hidden');"><?=$this->translate('detail_search')?></a>
					<input type="submit" class="btn btn-primary pull-right"/>
				</form>
			</div>
		</div>

		<div class="clearfix"></div>
		<br />
		<div class="table-responsive">
			<table class="table table-striped table-bordered">
				<thead>
					<tr>
						<th>ID</th>
						<th><?=$this->translate('user')?></th>
						<th><?=$this->translate('role')?></th>
						<th><?=$this->translate('options')?></th>
					</tr>
				</thead>
				<? foreach($this->users as $user){ ?>
				<tr>
					<td><?=$user['user_id']?></td>
					<td><i class="glyphicon glyphicon-user <?=($user['gender'] == 'm')? 'male' : 'female'; ?>"></i> <strong> <?=$user['first_name']?> <?=$user['last_name']?></strong> (<?=$user['username']?>)</td>
					<td>
						<span class="label label-<?=($user['role'] == 'superadmin') ? 'danger': ''?><?=($user['role'] == 'admin') ? 'success': ''?><?=($user['role'] == 'user') ? 'default': ''?>"><?=$user['role']?></span>
					</td>
					<td>
						<a href="<?=$this->url(Array('action' => 'details','user_id' => $user['user_id']),false)?>"><i class="glyphicon glyphicon-pencil tip" title="<?=$this->translate('edit')?>"></i></a>
					</td>
				</tr>
				<? } ?>
			</table>
			<?=$this->paginator ?>
		</div>
	</div>
</div>