<div class="row">
	<div class="col-lg-12">
			<h1 id="overview"><?=$this->translate('details_for_user')?>: <span class="color"><?=$this->userData['username']?></span></h1>
	</div>
</div>
<?=$this->partial('user/admin/navigation.phtml', array('active' => 'tickets', 'user_id' => $this->userData['user_id'])); ?>
<table class="table table-striped table-bordered">
	<thead>
		<tr>
			<th><?=$this->translate('ticket_id')?></th>
			<th><?=$this->translate('date')?></th>
			<th><?=$this->translate('type')?></th>
			<th><?=$this->translate('price')?></th>
			<th><?=$this->translate('winning')?></th>
		</tr>
	</thead>
	<tbody>
		<tr>
			<td>1</td>
			<td></td>
			<td></td>
			<td></td>
			<td></td>
		</tr>
		<tr>
			<td>2</td>
			<td></td>
			<td></td>
			<td></td>
			<td></td>
		</tr>
	</tbody>
</table>
<pre>
	<? print_r($this->userData);?>
</pre>