<div class="row">
	<div class="col-lg-12">
			<h1 id="overview"><?=$this->translate('details_for_user')?>: <span class="color"><?=$this->userData['username']?></span></h1>
	</div>
</div>
<?=$this->partial('user/admin/navigation.phtml', array('active' => 'transactions', 'user_id' => $this->userData['user_id'])); ?>
<table class="table table-striped table-bordered">
	<thead>
		<tr>
			<th><?=$this->translate('transaction_id')?></th>
			<th><?=$this->translate('date')?></th>
			<th><?=$this->translate('type')?></th>
			<th><?=$this->translate('order_id')?></th>
			<th><?=$this->translate('amount')?></th>
			<th><?=$this->translate('biller')?></th>
			<th><?=$this->translate('biller_transaction_id')?></th>
		</tr>
	</thead>
	<tbody>
		<? foreach($this->transactions as $transaction){?>
		<tr>
			<td><?=$transaction['transaction_id']?></td>
			<td><?=$transaction['transaction_date']?></td>
			<td><?=$transaction['transaction_type']?></td>
			<td><?=$transaction['order_id']?></td>
			<td><?=$this->Currency()->get($transaction['amount'])?></td>
			<td><?=$transaction['biller']?></td>
			<td><?=$transaction['biller_transaction_id']?></td>
		</tr>
		<? } ?>
	</tbody>
</table>
<pre>
	<? print_r($this->transactions);?>
</pre>
