<?php


namespace EuroMillions\web\controllers;


use Doctrine\ORM\EntityManager;
use EuroMillions\shared\services\SiteConfigService;
use EuroMillions\web\entities\Article;
use EuroMillions\web\repositories\ArticleRepository;
use EuroMillions\web\services\AuthService;
use EuroMillions\web\services\CartService;
use EuroMillions\web\services\CurrencyConversionService;
use EuroMillions\web\services\CurrencyService;
use EuroMillions\web\services\LanguageService;
use EuroMillions\web\services\LotteryService;
use EuroMillions\web\services\TransactionService;
use EuroMillions\web\services\UserPreferencesService;
use EuroMillions\web\services\UserService;


//EMTD se hacen llamadas al modelo ya que este controlador es solamente para el SEO

class ArticleController extends PublicSiteControllerBase
{
    /** @var  ArticleRepository */
    protected $articleRepository;

    public function initialize(LotteryService $lotteryService = null,
                               LanguageService $languageService = null,
                               CurrencyService $currencyService = null,
                               UserService $userService = null,
                               AuthService $authService = null,
                               UserPreferencesService $userPreferencesService = null,
                               SiteConfigService $siteConfigService = null,
                               CartService $cartService = null,
                               CurrencyConversionService $currencyConversionService = null,
                               TransactionService $transactionService = null)
    {
        $di = \Phalcon\Di::getDefault();
        /** @var EntityManager entityManager */
        $entityManager = $di->get('entityManager');
        parent::initialize($lotteryService, $languageService, $currencyService, $userService, $authService, $userPreferencesService, $siteConfigService, $cartService, $currencyConversionService, $transactionService); // TODO: Change the autogenerated stub
        $this->articleRepository = $entityManager->getRepository('EuroMillions\web\entities\Article');
    }


    public function discoverAction()
    {
        /** @var Article $article */
        $article = $this->articleRepository->find(1);
        return $this->setViewArticle($article);

    }

    public function rulesAction()
    {
        $article = $this->articleRepository->find(2);
        return $this->setViewArticle($article);
    }

    public function historyAction()
    {
        $article = $this->articleRepository->find(3);
        return $this->setViewArticle($article);
    }

    public function prizeAction()
    {
        $article = $this->articleRepository->find(4);
        return $this->setViewArticle($article);
    }

    /**
     * @param $article
     * @return \Phalcon\Mvc\View
     */
    private function setViewArticle($article)
    {
        $this->view->pick('/article/index');
        return $this->view->setVars([
            'content'       => $article->getContent(),
            'jackpot_value' => $this->userPreferencesService->getJackpotInMyCurrency($this->lotteryService->getNextJackpot('EuroMillions')),
        ]);
    }


}