<?
$currency = Settings::get("S_currency");
?>
<div class="menuwrapper">
	<div class="navbar-header">
		<button data-target=".navbar-collapse" data-toggle="collapse" class="navbar-toggle pull-left" type="button">
			<span class="sr-only"><?=$this->translate('toggle_navigation')?></span>
			<span class="icon-bar"></span>
			<span class="icon-bar"></span>
			<span class="icon-bar"></span>
		</button>
		<a href="<?=$this->baseUrl('/') ?>" class="navbar-brand"><span><?=$this->Customer()->Domain();?></span></a>
	</div>
	<div class="navbar-right">
		<form action="" name="switchlang" id="switchlang" method="POST">
		<input type="hidden" name="act" value="switchlang" />
		<ul class="nav">
			<? if (isLoggedin()){ ?>
				<li class="hidden-s-device <?=($this->translation_prefix == 'user_account_index')? 'active' : ''?>">
					<a href="<?=$this->url(Array(), 'User_Account_Index',true);?>"><?=($this->userData['first_name'] != '') ? $this->userData['first_name'] : $this->userData['username']; ?> - <span id="creditbalance" class="color2"><?=$this->Currency()->get($this->User_Userdata()->getBalance());?></span></a>
				</li>
				<li class="hidden-s-device"><a href="#" class="logout" onclick="$('#logout').submit();"><?=$this->translate('logout')?></a></li>
			<? } else { ?>
				<li style="padding: 0 4px;" class="hidden-s-device">
					<a href="<?=$this->url(Array(),'User_Registration',true)?>"  onclick="return false;" data-act="registration" data-href="<?=$this->url(Array(),'User_Registration',true)?>" class="popup btn btn-default <?=($this->translation_prefix == 'user_auth_registration')? 'active' : ''?>"><?=$this->translate('seo_menu_user_auth_registration')?></a>
				</li>
				<li style="padding: 0 4px;"  class="hidden-s-device">
					<a href="<?=$this->url(Array(),'User_Login',true)?>"  onclick="return false;" data-act="login" data-href="<?=$this->url(Array(),'User_Login',true)?>" class="popup btn btn-default <?=($this->translation_prefix == 'user_auth_login')? 'active' : ''?>"><?=$this->translate('seo_menu_user_auth_login')?></a>
				</li>
			<? } ?>
				<li class="visible-s-device">
					<a href="<?=$this->url(Array(),'Play_Index',true)?>" class="btn eur-primary"><?=$this->translate('seo_menu_play_index_index')?></a>
				</li>

				<?
				$arrLang=$this->trans()->getLanguageList("frontend");
				?>

				<li>
					<select name="lang" onchange="$('#switchlang').submit();" data-style="bootstrap">
						<? foreach( $arrLang as $name=>$lang) { ?>
						<option value="<?=$lang ?>"<?=($lang==Settings::get("S_lang") ? " selected":"") ?>><?=$name ?></option>
						<? } ?>
					</select>
				</li>
				<li>
					<select name="currency" onchange="$('#switchlang').submit();" data-style="bootstrap" data-class="dropdown-menu-right" data-cols="2" data-title="Select Currency">

					<? $count = "odd"; foreach( $this->currencyList as $curr) {
						$count = ($count == "even") ? "odd" : "even";	?>
						<option class="currencybg currency-<?=$curr['currency'] ?> <?=$count ?>" value="<?=$curr['currency'] ?>"<?=($currency==$curr['currency'] ? " selected":"") ?>><?=$curr['currency'] ?></option>
					<? } ?>
					</select>
				</li>
				<li id="shoppingCart">
					<?=$this->Cart()->getLink();?>
				</li>
		</ul>
		</form>
	</div>
	<div class="navbar-collapse collapse" id="navigation">
		<ul class="nav navbar-nav visible-s-device" style="border-bottom:1px solid #ccc;">
			<? if (!isLoggedin()){ ?>
				<li class="<?=($this->translation_prefix == 'user_auth_registration')? 'active' : ''?>">
					<a href="<?=$this->url(Array(),'User_Registration',true)?>"  href="<?=$this->url(Array(),'User_Registration',true)?>" class="<?=($this->translation_prefix == 'user_auth_registration')? 'active' : ''?>"><?=$this->translate('seo_menu_user_auth_registration')?></a>
				</li>
				<li class="<?=($this->translation_prefix == 'user_auth_login')? 'active' : ''?>">
					<a href="<?=$this->url(Array(),'User_Login',true)?>"  style="text-decoration:underline;"><?=$this->translate('seo_menu_user_auth_login')?></a>
				</li>
			<? } else { ?>
				<li class="visible-s-device <?=($this->translation_prefix == 'user_account_index')? 'active' : ''?>"><a href="<?=$this->url(Array(), 'User_Account_Index',true);?>"><?=($this->userData['first_name'] != '') ? $this->userData['first_name'] : $this->userData['username']; ?> - <span id="creditbalance" class="color2"><?=$this->Currency()->get($this->User_Userdata()->getBalance());?></span></a></li>
				<li class="visible-s-device"><a href="#" class="logout " onclick="$('#logout').submit();"><?=$this->translate('logout')?></a></li>
			<? } ?>
		</ul>
		<ul class="nav navbar-nav">
			<li class="<?=($this->translation_prefix == 'play_index_index')? 'active' : ''?>">
				<a href="<?=$this->url(Array(),'Play_Index',true)?>"><?=$this->translate('seo_menu_play_index_index')?></a>
			</li>
			<li class="<?=($this->translation_prefix == 'lottery_index_index')? 'active' : ''?>">
				<a href="<?=$this->url(Array(),'Lottery_Index',true)?>"><?=$this->translate('seo_menu_lottery_index_index')?></a>
			</li>
			<li class="dropdown">
				<a href="#" class="dropdown-toggle <?=($this->translation_prefix == 'article_index_show')? 'color' : ''?>" id="informationmenue" data-toggle="dropdown"><?=$this->translate('seo_menu_information_index_index')?> <span class="caret"></span></a>
				<ul class="dropdown-menu" role="menu" aria-labelledby="informationmenue">
					<li role="presentation" class="<?=($this->translation_prefix == 'article_index_show' && $this->article['key'] == "discover_your_odds_of_winning_the_euromillions")? 'active' : ''?>">
						<a role="menuitem" tabindex="-1" href="{{article_url::discover_your_odds_of_winning_the_euromillions}}" title="<?=$this->translate('main_page_story_1_title')?>"><?=$this->translate('main_page_story_1_title')?></a>
					</li>
					<li role="presentation" class="<?=($this->translation_prefix == 'article_index_show' && $this->article['key'] == "euromillions_rules")? 'active' : '' ?>">
						<a role="menuitem" tabindex="-1" href="{{article_url::euromillions_rules}}" title="<?=$this->translate('main_page_story_2_title')?>"><?=$this->translate('main_page_story_2_title')?></a>
					</li>
					<li role="presentation" class="<?=($this->translation_prefix == 'article_index_show' && $this->article['key'] == "euromillions_history")? 'active' : ''?>">
						<a role="menuitem" tabindex="-1" href="{{article_url::euromillions_history}}" title="<?=$this->translate('main_page_story_3_title')?>"><?=$this->translate('main_page_story_3_title')?></a>
					</li>
					<li role="presentation" class="<?=($this->translation_prefix == 'article_index_show' && $this->article['key'] == "euromillions_prize_structure")? 'active' : ''?>">
						<a role="menuitem" tabindex="-1" href="{{article_url::euromillions_prize_structure}}" title="<?=$this->translate('main_page_story_4_title')?>"><?=$this->translate('main_page_story_4_title')?></a>
					</li>
				</ul>
			</li>
			<li class="dropdown">
				<a href="#" class="dropdown-toggle <?=($this->translation_prefix == 'news_index_show' || $this->translation_prefix == 'news_index_index' || $this->translation_prefix == 'contact_index_index' || $this->translation_prefix == 'faq_index_index')? 'color' : ''?>" type="button" id="aboutmenue" data-toggle="dropdown"><?=$this->translate('seo_menu_about_index_index')?> <span class="caret"></span></a>
				<ul class="dropdown-menu" role="menu" aria-labelledby="aboutmenue">
					<li role="presentation" class="<?=($this->translation_prefix == 'news_index_show' || $this->translation_prefix == 'news_index_show')? 'active' : ''?>">
						<a role="menuitem" href="<?=$this->url(Array("module"=>"news","controller"=>"index","action"=>"index","page"=>1),"News_Index",true);?>"><?=$this->translate('euromillions_news')?></a>
					</li>
					<li role="presentation" class="<?=($this->translation_prefix == 'faq_index_index')? 'active' : ''?>">
						<a href="<?=$this->url(Array(),"Faq_Index",true);?>" role="menuitem"><?=$this->translate('seo_menu_faq_index_index')?></a>
					</li>
					<li role="presentation" class="<?=($this->translation_prefix == 'contact_index_index')? 'active' : ''?>">
						<a href="<?=$this->url(Array(),'Contact_Index_Index',true)?>"  onclick="return false;" data-act="contact" data-href="<?=$this->url(Array(),'Contact_Index_Index',true)?>" class="popup"><?=$this->translate('seo_menu_contact_index_index')?></a>
					</li>
				</ul>
			</li>
		</ul>
	</div><!--/.nav-collapse -->

</div>