<?=$this->render('mail_header.phtml') ?>

	<!-- Picture -->
	<tr>
		<td>
			<img alt="<?=$this->Email()->sitename()?>" src="<?=$this->Email()->imagePath()?>/header/winnings.png" style="width: 100%;" />
			<br /><br /><br />
		</td>
	</tr>

	<!-- Hello -->
	<tr valign="top">
		<td style="border-top: 4px solid #02B3B6;">
			<p style="margin:0;padding:22px 0 15px 0;">
				<b><font style="font-size:20px;color:#02B3B6;"><?=$this->translate('mail_hello_username',Array( 0 => $this->first_name));?></font></b>
			</p>
		</td>
	</tr>


	<!-- Body -->
	<tr valign="top">
		<td>
			<p><?=$this->translate('mail_collectwinnings_text_1')?></p>
			<p><?=$this->translate('mail_collectwinnings_text_2')?></p>
			<p><?=$this->translate('mail_collectwinnings_text_3')?></p><br />
			<a href="mailto:<?=$this->Email()->supportMail()?>" style="color:#0aa2a4; text-decoration: none;"><?=$this->Email()->supportMail()?></a>
		</td>
	</tr>

<!-- FOOTER 1 & COPYRIGHT -->
<?=$this->render('mail_footer.phtml') ?>
