<?=$this->render('mail_header.phtml') ?>

	<!-- Picture -->
	<tr>
		<td>
			<img alt="<?=$this->Email()->sitename()?>" src="<?=$this->Email()->imagePath()?>/header/winner.png" style="width: 100%;" />
			<br /><br /><br />
		</td>
	</tr>

	<!-- Hello -->
	<tr valign="top">
		<td style="border-top: 4px solid #02B3B6;">
			<p style="margin:0;padding:22px 0 15px 0;">
				<b><font style="font-size:20px;color:#02B3B6;"><?=$this->translate('mail_hello_username',Array( 0 => $this->first_name));?></font></b>
			</p>
		</td>
	</tr>


	<!-- Body -->
	<tr valign="top">
		<td>
			<p><?=$this->translate('mail_emwinning_text_1',Array( 0 => $this->draw_date))?></p>
			<br />
			<p><? foreach($this->numbers as $number){ ?>
				<font style="background-color:#02B3B6; padding:3px; border-radius:3px; color:#ffffff; font-size: 18px;"><?=$number?></font>&nbsp;
				<? } ?>
				<? foreach($this->stars as $star){ ?>
				<font style="background-image: url(<?=$this->Email()->imagePath()?>/star.png);background-repeat: no-repeat;background-position: 0px -1px; padding: 10px 13px 6px 9px; color:#3c3c3b; font-size: 18px; text-align: center;"><?=$star?></font>
				<? } ?>
			</p>
			<br />
			<p>
				<?=$this->translate('mail_emwinning_your_ticketnumbers')?> %NUMBERS% <br/>
				<?=$this->translate('mail_emwinning_your_winnings')?> %amount%
			</p>
			<p><?=$this->translate('mail_emwinning_text_2')?></p><br />
			<p>
				<a style="padding: 10px 20px; background-color:#d34833; color:#ffffff; border-radius: 5px; text-decoration: none; margin-left: 1px; margin-right: 1px;" title="<?=$this->translate('mail_emwinning_button')?>" href="<?=$this->url(Array(), 'User_Account_Index',true);?>"><?=$this->translate('mail_emwinning_button')?></a>
			</p><br />
		</td>
	</tr>

<!-- FOOTER 1 & COPYRIGHT -->
<?=$this->render('mail_footer.phtml') ?>