<?=$this->translate('mail_hello_username',Array( 0 => $this->first_name));?><br/><br/>

<?=$this->translate('mail_forgotpassword_your_new_password')?>: <?=$this->new_pw ?><br/><br/>

<?=$this->translate('mail_forgotpassword_text_1')?><br /><br />

<a href="<?=$this->Email()->url()?><?=$this->Url(Array("user_code"=>$this->user_code,"is_mail"=> 1),"User_ResetPw") ?>"><?=$this->translate('mail_forgotpassword_button')?></a>

<br/><br/>
<?=$this->translate('mail_regards')?>,<br/>
<?=$this->translate('mail_sender')?>