				<tr>
					<td>
						<p style="padding:0 0 22px 0;"><?=$this->translate('mail_regards')?><br /><br /><?=$this->translate('mail_sender')?></p>
					</td>
				</tr>
			</table>
		</td>
	</tr>
	<tr valign="top">
		<td style="background-color: #f4f4f4;border-top: 1px solid #02B3B6;border-bottom: 8px solid #02B3B6;">
			<table align="center" height="60" cellpadding="0" cellspacing="0" border="0" style="width:100%;padding : 10px;max-width: 488px!important;">
				<tr>
					<td align="center">
						<p style="font-size:10px;color:#3d3d3d">
							<a href="<?=$this->url(Array(),"Faq_Index",true);?>" style="color:#3d3d3d;text-decoration:none;">FAQ</a> - <a href="" style="color:#3d3d3d;text-decoration:none;">Terms and Conditions</a><br /><br />
							Copyright 2014 - All rights reserved<br />
							Panamedia International Limited<br />
							41, Georita Court, Glieba Street, St. Paul’s Bay - Malta<br /><br />
							To be sure to receive future emails, thank you to add <?=$this->Email()->supportMail()?> in your address book.
						</p>
					</td>
				</tr>
			</table>
		</td>
	</tr>
</table>
</body>
</html>