<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
	<title><?=$this->Email()->sitename()?></title>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
</head>
<body leftmargin="0" marginwidth="0" marginheight="0" offset="0" bgcolor="#fff" style="background-color:#fff">

<table bgcolor="" border="0" cellpadding="0" cellspacing="0" height="100%" style="font-family: Arial, Helvetica; font-size:14px;color:#3d3d3d;width:100%;height:100%;" width="100%">
	<tr>
		<td style="background-color:#29a1a0;height:108px;">
			<!-- Logo -->
			<table align="center" border="0" cellpadding="0" cellspacing="0" style="max-width: 488px!important;width:100%;">
				<tr>
					<td>
						<a href="<?=$this->Email()->url()?>" title="<?=$this->Email()->sitename()?>"><img alt="<?=$this->Email()->domain()?>" src="<?=$this->Email()->imagePath()?>/header/logo_email.png" style="width: 100%;" /></a>
					</td>
				</tr>
			</table>
		</td>
	</tr>
	<tr>
		<td>
			<table align="center" border="0" cellpadding="0" cellspacing="0" style="padding : 10px;max-width: 488px!important;width:100%;">

