<?=$this->render('mail_header.phtml') ?>

	<!-- Picture -->
	<tr>
		<td>
			<img alt="<?=$this->Email()->sitename()?>" src="<?=$this->Email()->imagePath()?>/header/purchase.png" style="width: 100%;" />
			<br /><br /><br />
		</td>
	</tr>

	<!-- Hello -->
	<tr valign="top">
		<td style="border-top: 4px solid #02B3B6;">
			<p style="margin:0;padding:22px 0 15px 0;">
				<b><font style="font-size:20px;color:#02B3B6;"><?=$this->translate('mail_hello_username',Array( 0 => $this->first_name));?></font></b>
			</p>
		</td>
	</tr>


	<!-- Body -->
	<tr valign="top">
		<td>
			<p style="padding:0 0 22px 0;"><?=$this->translate('mail_purchase_text_1')?></p>

			<font style="color:#02B3B6;"><?=$this->translate('mail_purchase_purchase_date')?>: </font><br />

			Ticket ID/Number: XXXXX<br />
			Lines: 2<br />
			No. of draws: 2<br />
			Your active numbers:<br /><br />
			<? foreach($this->numbers as $number){ ?>
			<font style="background-color:#02B3B6; padding:3px; border-radius:3px; color:#ffffff; font-size: 18px;"><?=$number?></font>&nbsp;
			<? } ?>
			<? foreach($this->stars as $star){ ?>
			<font style="background-image: url(<?=$this->Email()->imagePath()?>/star.png);background-repeat: no-repeat;background-position: 0px -1px; padding: 10px 13px 6px 9px; color:#3c3c3b; font-size: 18px; text-align: center;"><?=$star?></font>
			<? } ?>
			<br /><br />

			<? foreach($this->numbers as $number){ ?>
			<font style="background-color:#02B3B6; padding:3px; border-radius:3px; color:#ffffff; font-size: 18px;"><?=$number?></font>&nbsp;
			<? } ?>
			<? foreach($this->stars as $star){ ?>
			<font style="background-image: url(<?=$this->Email()->imagePath()?>/star.png);background-repeat: no-repeat;background-position: 0px -1px; padding: 10px 13px 6px 9px; color:#3c3c3b; font-size: 18px; text-align: center;"><?=$star?></font>
			<? } ?>
			<br /><br /><br />
			<a href="<?=$this->Email()->url()?><?=$this->url(Array(),'Lottery_Index',true)?>" title="My account" style="padding: 10px 20px; background-color:#d34833; color:#ffffff; border-radius: 5px; text-decoration: none; margin-left: 1px; margin-right: 1px;">My account</a><br /><br /><br />

		</td>
	</tr>

<!-- FOOTER 1 & COPYRIGHT -->
<?=$this->render('mail_footer.phtml') ?>
