<div class="page-header">
	<h1 id="overview">LC <?=$this->translate('log')?></h1>
</div>
<div class="panel panel-default">
	<div class="panel-body">
		<form action="<?=$this->url(Array('module' => 'lottery','controller' => 'admin_euromillions_log_lc', 'action' => 'index'),false,true )?>" role="form" method="post" class="col-md-12 form-inline">
			<div class="form-group">
				<label>Status</label>
				<?=$this->Selectmenu('status',$this->statustypes,$this->searchParams['status'],'form-control',$this->translate('please_select')) ?>
			</div>
			<div class="form-group">
				<input type="text"  name="intern_id" class="form-control" placeholder="user_id /order_id / em_ticket_id" value="<?=(isset($this->searchParams['intern_id'])? $this->searchParams['intern_id'] : '');?>"/>
			</div>
			<div class="form-group">
				<input type="text" name="extern_id" class="form-control"  placeholder="lc_id /ticket_id" value="<?=(isset($this->searchParams['extern_id'])? $this->searchParams['extern_id'] : '');?>"/>
			</div>
			<div class="form-group">
				<button class="btn btn-primary" type="submit"><i class="glyphicon glyphicon-repeat"></i></button>
			</div>
		</form>
	</div>
</div>

<table class="table table-striped table-bordered">
	<tr>
		<th>ID</th>
		<th>user id</th>
		<th>ticket_id</th>
		<th>draw_id</th>
		<th><?=$this->translate('duration')?></th>
		<th><?=$this->translate('status')?></th>
		<th><?=$this->translate('options')?></th>
	</tr>
	<? foreach($this->items as $item) {
		$diff = $this->Date($item['transaction_end_date'],'timestamp')-$this->Date($item['transaction_start_date'],'timestamp');
?>
	<tr class="<?=($diff > 5)? 'warning' : '';?>">
		<td><?=$item['id'] ?></td>
		<td><?=$item['user_id'] ?></td>
		<td><?=$item['ticket_id'] ?></td>
		<td><?=$item['id'] ?></td>
		<td><?=$this->Date($item['transaction_end_date'],'timestamp')-$this->Date($item['transaction_start_date'],'timestamp'); ?> s </td>
		<td><?=$item['status'] ?></td>
		<td>
			<a class="popup" href="<?=$this->url(Array('module' => 'lottery','controller' => 'admin_euromillions_log_lc', 'action' => 'details','id' => $item['id']),false,true )?>"><?=$this->translate('details')?></a></td>
		</td>
	</tr>
	<? } ?>
</table>