<? $this->headTitle($this->translate('error_404'))?>
<? $this->headMeta()->prependName('keywords', $this->translate('error_404')); ?>
<? $this->headMeta()->prependName('description', $this->translate('error_page_text')); ?>
<div class="container">
	<? if($this->title) { ?>
	<div id="newslist" class="contentContainer100">
		<h1><?=$this->title?></h1>
		<?=$this->content?>
	</div>
	<? } else { ?>
	<div id="newslist" class="contentContainer100">
		<h1><?=$this->translate('error_404')?></h1>
		<p><?=$this->translate('error_page_text')?></p>
	</div>
	<? } ?>
</div>