<div class="modal-body">
	<div class="systemMessage">
		<div class="icon">
			<i class="glyphicon glyphicon-<?=$this->systemIcon ?> color">&nbsp;</i>
		</div>
		<div class="modal-box">
			<div class="msgText">
				<?=$this->systemText ?>
			</div>
		</div>
		<div class="modal-controls">
			<?

			switch($this->systemType) {
				case 'yesno': ?>
					<a class="pull-left btn btn-primary" title="<?=$this->translate('abort')?>" data-dismiss="modal" aria-hidden="true">
						<?=$this->translate('abort')?>
					</a>
					<a class="confirm pull-right btn btn-primary" title="<?=$this->translate('continue')?>">
						<?=$this->translate('continue')?>
					</a>
			<?		break;
				case 'okreload': ?>
					<a class="reload btn btn-primary pull-right" title="<?=$this->translate('okay')?>" onclick="location.reload(); ">
						<?=$this->translate('okay')?>
					</a>
			<?		break;
				default:
				case 'ok': ?>
					<a class="btn btn-primary pull-right" title="<?=$this->translate('okay')?>" data-dismiss="modal" aria-hidden="true">
						<?=$this->translate('okay')?>
					</a>
			<?		break;
			}?>
			<span class="clear"></span>
		</div>
	</div>
</div>
<script>
	$(document).ready(function() {
		json = <?=(isset($this->json))? $this->json : 'false' ?>;
		$('#Overlay a.reload').click(function(){ $('#Overlay .close').click(); location.reload(); });

		$('#Overlay .confirm').click(function(){
			if (json){
				Popup(json);
			} else {
				$('form.'+id).submit();
			}
		});
	});
</script>
</div>