<?	$l = Zend_Registry::get('Zend_Currency');
	$l = $l->getLocale();
	$minimum_amount = 10;
	$maximum_amount = 6000;
?>
<script>
	settings.currencyRegion = '<?=str_replace(array('_'),array('-'), $l); ?>';
	settings.defaultOption = '<? if($this->userData['budget'] >= $this->cart_price) { ?>account<? } ?>';
</script>

<div class="pagename" id="billing">
		<div class="container">
			<div class="box">
				<div class="inner">
					<h4><?=$this->translate('meta_headline_billing_pay_index')?></h4>
					<form id="step2" action="" method="post" class="form-inline" onsubmit="return checkBillingFormular();">
						<input type="hidden" name="act" value="submit_summary">
						<input type="hidden" name="cart_id" value="<?=$this->cart_id ?>">
						<div id="paytype">
							<div class="formfield paytype">
								<label class="radio checked" for="direct">
									<input type="radio" id="direct" name="billing_type"  value="direct" data-price="<?=$this->Currency()->get($this->total_price)?>" /> <?=$this->translate('direct_payment')?> <small>(<?=$this->translate('additional_transaction_fee',Array($this->Currency()->get('0.35'),$this->Currency()->get($minimum_amount)) )?>)</small>
								</label>
							</div>
							<div class="formfield paytype <? if($this->userData['budget'] < $this->cart_price) { ?>disabled<? } ?>">
								<label class="radio checked" for="account">
									<input type="radio" id="account" name="billing_type" <? if($this->userData['budget'] < $this->cart_price) { ?> disabled="disabled"<? } ?> value="account" data-price="<?=$this->Currency()->get($this->cart_price)?>" /> <?=$this->translate('balance')?> <small>(<?=$this->Currency()->get($this->userData['budget']);?>)</small>
								</label>
							</div>
							<div class="formfield paytype">
								<label class="radio checked" for="deposit">
									<input type="radio" id="deposit" name="billing_type"  value="deposit" /> <?=$this->translate('credit_my_account')?> <small>(<?=$this->translate('save_transaction_fee')?>)</small>
								</label>
								<div class="payinamount">
									<!--<? //=$this->translate('label_deposit_amount')? > <!--input type="number" name="payinamount" id="payinamount" class="form-control input-sm" data-minimum="< ?=$this->Currency()->get($minimum_amount)? >" value="< ?=$this->Currency()->get($minimum_amount,0,false)? >" data-maximum="< ?=$this->Currency()->get($maximum_amount) ? >" /> (min <?=$this->Currency()->get($minimum_amount,0)? > - max < ?=$this->Currency()->get($maximum_amount,0)? > )--> ?
									?>-->
									<?=$this->translate('label_deposit_amount')?> <input type="number" name="amount_payin" id="payinamount" class="form-control" value="<?=$minimum_amount?>" data-minimum="<?=$minimum_amount?>" data-maximum="<?=$maximum_amount?>" /> (min <?=$this->Currency()->get($minimum_amount,0)?> - max <?=$this->Currency()->get($maximum_amount,0)?> )
								</div>
							</div>
							<div class="error"  style="display:none;">
								<?=$this->Notification('info_wrong_payin_amount',false,array('min' => $this->Currency()->get($minimum_amount), 'max' => $this->Currency()->get($maximum_amount)) ) ?>
							</div>
						</div>
						<div id="billers" style="display:none;">
							<hr >
							<h4><?=$this->translate('meta_headline_billing_pay_index_2')?></h4>
							<div class="error" style="display:none;">
								<?=$this->Notification('error_no_biller_selected') ?>
							</div>
							<div class="formfield">
								<label class="radio biller cc" for="mycc1">
									<input type="radio" id="mycc1" name="biller" value="mycc1"/> <?=$this->translate('label_creditcard')?>
								</label>
							</div>
							<div class="formfield">
								<label class="radio biller sofort" for="sofort">
									<input type="radio" id="sofort" name="biller" value="sofort"/> <?=$this->translate('label_sofortueberweisung')?>
								</label>
							</div>
							<div class="formfield">
								<label class="radio biller paysafe" for="paysavecard">
									<input type="radio" id="paysavecard" name="biller" value="paysavecard"/> <?=$this->translate('label_paysafecard')?>
								</label>
							</div>
							<br class="clear" />
						</div>
						<div id="submit">
							<hr />
							<strong><?=$this->translate('amount_to_be_charged')?>: <span class="color finalprice"><?=$this->Currency()->get($this->cart_price)?></span></strong>
							<p id="transactionfee"><?=$this->translate('include_transaction_fee',Array($this->Currency()->get('0.35'),$this->Currency()->get($minimum_amount)) )?></p>

							<div class="submit" style="text-align:center;">
								<button type="submit" class="btn eur-primary">
									<?=$this->translate('continue')?>
								</button>
							</div>
						</div>
					</form>
				</div>
			</div>
		</div>
 	</div>