<div class="pagename" id="billing">
	<div class="container">
		<div class="box">
			<div class="inner">
				<h4><?=$this->translate('meta_headline_billing_pay_summary')?></h4>
				Direct Payment
				
				<form id="step3" action="" method="post">
					<input type="hidden" name="act" value="simulate">
					<input type="hidden" name="cart_id" value="<?=$this->cart_id ?>">
					<input type="hidden" name="biller" value="<?=$this->biller ?>">
					<input type="hidden" name="amount" value="<?=$this->total_price ?>">
					<input type="hidden" name="billing_type" value="<?=$this->billing_type ?>">
					<button type="submit" class="btn eur-primary" value="simulate billing">
				
				</form>
			</div>
		</div>
	</div>
</div>