<? $this->headTitle($this->news['page_title'])?>
<? $this->headMeta()->prependName('keywords', $this->news['meta_keywords']); ?>
<? $this->headMeta()->prependName('description', $this->news['meta_description']); ?>


<div id="newslist" class="contentContainer100">
	<h1><?=$this->news['title']?></h1>
	<p>
		<span class="date">
			<?=$this->translate('Published')?>: <time pubdate="<?=$this->Date($this->news['published_on'])?>"><?=$this->Date($this->news['published_on'])?></time>
		</span>
		<span class="author"> <?=$this->translate('by')?> <?=$this->Authors()->getName($this->news['published_by']);?></span>
	<!-- AddThis Button BEGIN -->
	</p>
	<?=$this->SocialWidgets()->addThis(); ?>
	<? if($this->news['image'] != '' || $this->news['header'] != '') { ?>
	<div id="preamble">
		<? if($this->news['image'] != '') { ?>
			<img src="<?=$this->news['image']?>" alt="<?=$this->news['page_title']?>" style="max-width: 196px;max-height:196px;"/>
		<? } else { ?>
			<img src="<?=$this->baseUrl() ?>/templates/default/images/news/blue-star.png" alt="<?=$this->news['page_title']?>" height="196" width="196" />
		<? } ?>
		<? if($this->news['header'] != '') { ?>
			<h2><?=$this->news['header']?></h2>
		<? } ?>
	</div>
	<? } ?>
	<div id="mainContent" class="ColF">
		<?=$this->news['content']?>
	</div>
</div>
