<? $this->headTitle($this->translate('seo_faq_title'))?>
<? $this->headMeta()->prependName('keywords', $this->translate('seo_faq_keywords')); ?>
<? $this->headMeta()->prependName('description', $this->translate('seo_faq_description')); ?>

<div id="faq" class="pagename">
	<div class="container">
		<h1><span><?=$this->translate('meta_headline_faq_index_index')?></span></h1>
		<div id="corevalues">
		<? if(!empty($this->arrList)){ ?>
			<? foreach($this->arrList as $item) { ?>
					<div class="panel" data-anchor-target="#<?=make_alias($item['question'])?>">
						<a data-toggle="collapse" data-parent="#corevalues" data-target="#<?=make_alias($item['question'])?>"><span><?=$item['question']?></span></a>
				    	<div id="<?=make_alias($item['question'])?>" class="collapse middle"><?=$item['answer']?></div>
					</div>

			<? } ?>
		<? } ?>
		</div>
	</div>
</div>