<div class="container">
	<h1 title="h1">Euromillions Styles <small>h1</small></h1>
	<h2 title="h2">Euromillions Styles</h2>
	<h3 title="h3">Euromillions Styles</h3>
	<h4 title="h4">Euromillions Styles</h4>
	<h5 title="h5">Euromillions Styles</h5>
	<h6 title="h6">Euromillions Styles</h6>
</div>
<div class="container">
	<h3>Alert Styles <small>/templates/default/helpers/Notification.php</small></h3>
	<?=$this->Notification('user_auth_login_error')?>
	<?=$this->Notification('user_auth_forgotpassword_success')?>
	<?=$this->Notification('error_no_biller_selected')?>

	<h3>Buttons</h3>
	<a class="btn eur-primary">.btn .eur-primary</a>
	<a class="btn eur-secondary">.btn .eur-secondary</a>

	<br /><br />
	<div class="box" title=".box">
		<h4>Typical .box headline is H4</h4>
		<div class="inner">
			box inner
		</div>
	</div>

	<div>
		<h3>System E-Mails</h3>
		<p>The system E-Mails are aviable here: <a class="btn btn-xs eur-primary" href="/de/default/test/mail" target="_blank">click here</a></p>
		<h3>Iconsets</h3>
		<p>The Euromillions iconset is aviable here: <a class="btn btn-xs eur-primary" href="/templates/lotto/fonts/euromillons/demo.html" target="_blank">click here</a></p>
	</div>

	<div>
		<h3>Formulars</h3>
	</div>
</div>