<div class="pagination">
    <div class="centered">
        <?php if($pagination['isFirst']){ ?>
        <?php }else { ?>
            <a href="<?= $pagination['first_url'] ?>" class="page gradient"><?= $pagination['translation']['first'] ?></a>
            <a href="<?=$pagination['prev_url'] ?>" class="page gradient"><?= $pagination['translation']['previous'] ?></a>
        <?php } ?>
        <?php foreach($pagination['pages'] as $page): ?>
            <?php if(!$page['isSeparator']): ?>
                <?php if($page['class'] != null): ?>
                    <span class="page active"><?= $page['num'] ?></span>
                <?php else: ?>
                    <a href="<?= $page['url'] ?>" class="page gradient"
                       data-start="<?= $page['num'] ?>">
                        <?= $page['num'] ?>
                    </a>
                <?php endif ?>
            <?php else: ?>
                <span ><?= $page['num']?></span>
            <?php endif; ?>
        <?php endforeach ?>
        <?php if($pagination['isLast']): ?>
        <?php else: ?>
            <a href="<?=$pagination['next_url'] ?>" class="page gradient"><?= $pagination['translation']['next'] ?></a>
            <a href="<?=$pagination['last_url'] ?>" class="page gradient"><?= $pagination['translation']['last'] ?></a>
        <?php endif ?>
    </div>
</div>