<?php


namespace EuroMillions\tests\unit;


use EuroMillions\tests\base\UnitTestBase;

class SiteConfigUnitTest extends UnitTestBase
{

    protected $currencyService_double;
    
    public function setUp()
    {
        $this->currencyService_double = $this->getServiceDouble('CurrencyService');
        parent::setUp(); // TODO: Change the autogenerated stub
    }

    /**
     * method getFeeFormatMoney
     * when 
     * should 
     */
    public function test_getFeeFormatMoney__()
    {
        
    }
    

}