
<div class="page-header">
	<h1 id="overview"><?=$this->translate('edit')?></h1>
</div>
<form action="" name="editdraw" method="post">

	<div class="form-group">
		<label><?=$this->translate('jackpot')?></label>
		<input type="text" name="jackpot" class="form-control" placeholder="Jackpot" value="<?=$this->data['draw']['jackpot'] ?>">
	</div>
	<span class="clear"></span>
	<div class="form-group">
		<label><?=$this->translate('winners')?></label>
		<table class="table table-striped table-bordered">
			<thead>
				<th><?=$this->translate('match')?></th>
				<th><?=$this->translate('prize')?> / €</th>
				<th><?=$this->translate('winners')?></th>
			</thead>
			<? foreach($this->data['winners'] as $winner) { ?>
			<tr>
				<td>
					<label><?=$winner['numbers'] ?>+<?=$winner['luckystars'] ?></label>
				</td>
				<td>
					<input type="text" class="form-control" name="prize[<?=$winner['id'] ?>]" value="<?=$winner['prize'] ?>" />
				</td>
				<td>
					<input type="text" class="form-control"name="winners[<?=$winner['id'] ?>]" value="<?=$winner['winners'] ?>" />
				</td>
			</tr>
			<? } ?>
		</table>
	</div>
	<span class="clear"></span>
	<input type="submit" value="<?=$this->translate('save')?>" class="btn btn-primary pull-right">
</form>
