<div class="page-header">
	<h1 id="overview">Draw History</h1>
</div>
<table class="table table-striped table-bordered">
	<tr>
		<th>Draw ID</th>
		<th><?=$this->translate('date')?></th>
		<th>Jackpot</th>
		<th>Option</th>
	</tr>
	<? foreach($this->list as $item) { ?>
	<tr>
		<td><?=$item->draw_id ?></td>
		<td><?=$this->Date($item['draw_date'],'medium')?></td>
		<td><?=$this->Currency()->get($item['jackpot']); ?></td>
		<td>
		<a href="<?=$this->url(Array("action"=>"edit","id"=>$item->draw_id)) ?>">
			<?=$this->translate('edit')?>
		</a>
		</td>
	</tr>
	<? } ?>
</table>