<div class="container pagename" id="ticketdetails">
	<div class="box">
		<h2><?=$this->translate('user_account_ticket_details_headline')?></h2>
	<hr >
	<dl  class="col1 sumarycol">
		<dt><i class="icon-date"></i> <?=$this->translate('date')?>:</dt>
		<dd><?=$this->Date($this->details['start_draw_date'])?></dd>
		<dt><i class="icon-draws"></i> <?=$this->translate('number_draws')?>:</dt>
		<dd><?=$this->details['num_of_draws'] ?></dd>

	</dl>
	<dl class="col2 sumarycol">
		<dt><i class="icon-label"></i> <?=$this->translate('total_price')?>:</dt>
		<dd><?=$this->Currency()->get($this->details['total_price']);?></dd>
		<dt><i class="icon-spiderpig"></i> <?=$this->translate('my_winnings')?>:</dt>
		<dd><?=$this->Currency()->get($this->details['win']);?></dd>

	</dl>
	<span class="clear"></span>
<hr >
		<table class="table table-striped">
<? foreach($this->details['items'] as $line){ ?>

			<tr>
				<td style="vertical-align:middle;"><i class="icon-tickettype icon-product-type-em-single color"></i></td>
				<td>
					<?  foreach($line['numbers'] as $number){ ?>
						<i class="playnumber selected icon-playnumber-<?=$number?>"></i>
					<? } ?>
				</td>
				<td>
					<?  foreach($line['numbers'] as $star){ ?>
						<i class="playstar selected icon-playstar-<?=$star?>"></i>
					<? } ?>
				</td>
			</tr>

<? } ?>
		</table>
<br />
		<h4><?=$this->translate('draw_results');?></h4>
			<table>
				<thead>
					<tr>
						<th><?=$this->translate('draw');?></th>
						<th><?=$this->translate('date');?></th>
						<th><?=$this->translate('status');?></th>
						<th><?=$this->translate('winnings');?></th>
					</tr>
				</thead>
				<? foreach($this->draws as $draw){ ?>
				<tr>
					<td><?=$draw['draw_id']?></td>
					<td><?=$this->Date($draw['draw_date'])?></td>
					<td><?=$draw['status']?></td>
					<td><?=$draw['winnings']?></td>
				</tr>
				<? } ?>

			</table>
	</div>
</div>

<pre>
	<? print_r($this->details)?>
</pre>