<? if(!$this->ajaxload) { ?>

<? $this->headTitle($this->translate('seo_news_title'))?>
<? $this->headMeta()->prependName('keywords', $this->translate('seo_news_keywords')); ?>
<? $this->headMeta()->prependName('description', $this->translate('seo_news_description')); ?>
<script>
	var currentPage = <?=$this->currentPage?>;
	var currentAction = 'newslist';
	var pageCount = <?=$this->pageCount?>;
</script>
<div id="newslist" class="pagename">
	<div class="container">
<h1><?=$this->translate('seo_news_title')?></h1>
<? } ?>
<? if(!empty($this->list)){ ?>
	<? foreach($this->list as $news) { ?>
	<div class="newsitem box" id="nid<?=$news['id'] ?>">
		<div class="thumb">
			<? if($news['image'] != '') { ?>
				<img src="<?=$news['image']?>" />
			<? } else { ?>
				<img alt="<?=$this->translate('seo_news_title')?>" src="<?=$this->baseUrl() ?>/templates/default/images/news/blue-star.png" />
			<? } ?>
		</div>
		<div class="text">
			<div class="title">
				<a href="<?=$news['detail_link']?>"><?=$news['page_title']?></a>
			</div>
			<div class="meta">
				<i class="glyphicon glyphicon-calendar"></i> <?=$this->Date($news['published_on'])?>
				<? if($news['published_by_name']){ ?>&nbsp;&nbsp;&nbsp;&nbsp;<i class="glyphicon glyphicon-user"></i> <?=$news['published_by_name']?><? } ?>
			</div>
			<p><?=$news['meta_description']?>... <a href="<?=$news['detail_link']?>"><?=$this->translate('read_more')?></a></p>
		</div>
	</div>
	<? } ?>
	<?=$this->paginator ?>
<? } else { ?>
	<p><?=$this->translate('no_news_aviable')?></p>
<? } ?>
<? if(!$this->ajaxload) { ?>
	</div>
</div>
<? } ?>