<? $this->headTitle($this->news['page_title'])?>
<? $this->headMeta()->prependName('keywords', $this->news['meta_keywords']); ?>
<? $this->headMeta()->prependName('description', $this->news['meta_description']); ?>

<div id="newsitem" class="pagename">
	<div class="container">
		<h1><?=$this->news['title']?></h1>
		<div class="meta">
			<i class="glyphicon glyphicon-calendar"></i> <?=$this->translate('Published')?>: <time pubdate="<?=$this->Date($this->news['published_on'])?>"><?=$this->Date($this->news['published_on'])?></time>
			1<?=$this->news['published_by']?>2
			<? if($this->news['published_by'] != ''){ ?> &nbsp;&nbsp;&nbsp;&nbsp;<i class="glyphicon glyphicon-user"></i> <?=$this->news['published_by_name']?><? } ?>
		</div>
		<!-- AddThis Button BEGIN -->
		<?=$this->SocialWidgets()->addThis(); ?>
		<? if($this->news['image'] != '' || $this->news['header'] != '') { ?>
		<div id="preamble">
			<? if($this->news['image'] != '') { ?>
				<img src="<?=$this->news['image']?>" alt="<?=$this->news['page_title']?>" style="max-width: 196px;max-height:196px;"/>
			<? } else { ?>
				<img src="<?=$this->baseUrl() ?>/templates/default/images/news/blue-star.png" alt="<?=$this->news['page_title']?>" height="196" width="196" />
			<? } ?>
			<? if($this->news['header'] != '') { ?>
				<h2><?=$this->news['header']?></h2>
			<? } ?>
		</div>
		<? } ?>

		<div id="mainContent" class="ColF">
			<?=$this->news['content']?>
		</div>

	</div>
</div>
