---
- name: Installing git and mysql clients from repository
  apt: name=git,mysql-client-5.6 state=present
- name: Install composer libraries
  composer: command="install" working_dir="/var/www" no_dev=no
- name: Set softlink for doctrine command line utilities
  file: src=/var/www/vendor/bin/doctrine dest=/usr/local/bin/doctrine state=link mode="u+x,g+x,o+x"
- name: Update npm
  shell: npm update -g npm
- name: Npm install
  shell: npm install
  args:
    chdir: /var/www/react
- name: Npm watch
  shell: npm run watch &
  args:
    chdir: /var/www/react

- name: Get GeoIP IPv4 database
  shell: wget http://geolite.maxmind.com/download/geoip/database/GeoLiteCountry/GeoIP.dat.gz
  shell: gzip -d GeoIP.dat.gz
  args:
    chdir: /var/www/data/geoipdatabase

- name: Get GeoIP IPv6 database
  shell: wget http://geolite.maxmind.com/download/geoip/database/GeoIPv6.dat.gz
  shell: gzip -d GeoIPv6.dat.gz
  args:
    chdir: /var/www/data/geoipdatabase
