---
- name: Installing git and mysql clients from repository
  apt: name=gzip,git,python-pip,mysql-client-5.6 state=present
- name: Install composer libraries
  composer: command="install" working_dir="/var/www" no_dev=no
- name: Set softlink for doctrine command line utilities
  file: src=/var/www/vendor/bin/doctrine dest=/usr/local/bin/doctrine state=link mode="u+x,g+x,o+x"
- name: Npm prepare
  shell: rm -r node_modules & npm cache clean --force
  args:
    chdir: /var/www/react
- name: Npm install
  shell: npm --no-bin-links install
  args:
    chdir: /var/www/react
- name: Npm watch
  shell: npm run watch &
  args:
    chdir: /var/www/react

- name: Translations angular2 dependencies install
  shell: npm install
  args:
    chdir: /var/www/public/a/js/angular-admin

- name: Translation angular2 start spa
  shell: npm start &
  args:
    chdir: /var/www/public/a/js/angular-admin

- name: Get GeoIP IPv4 database
  shell: wget -nc http://geolite.maxmind.com/download/geoip/database/GeoLiteCountry/GeoIP.dat.gz
  args:
    chdir: /var/www/data/geoipdatabase

- name: Get GeoIP IPv6 database
  shell: wget -nc http://geolite.maxmind.com/download/geoip/database/GeoIPv6.dat.gz
  args:
    chdir: /var/www/data/geoipdatabase

- name: Uncompress geoip database
  shell: gzip -fd GeoIP.dat.gz
  args:
    chdir: /var/www/data/geoipdatabase

- name: Uncompress geoip database
  shell: gzip -fd GeoIPv6.dat.gz
  args:
    chdir: /var/www/data/geoipdatabase


- name: install the required packages
  apt: pkg={{ item }} state=present update_cache=yes
  with_items:
   - python-pip

- name: Install docker-py as a workaround for Ansible issue
  pip: name=docker-py version=1.2.3
